*0160_TOP
[bgm storage="bgm01" time=100]
[backlay][bg storage="BG05b"][trans time=500 method=crossfade][wt2]
[sysbt_meswin]
*1304|
[fc]
[【央】]
「おお……」[pcms][endhact]
*1305|
[fc]
食堂中に広がるカレーのにおい。[pcms]
*1306|
[fc]
腹が減ってる時のカレーのにおいって暴力的だよな……。[r]
拷問に使えるレベルだ。[pcms]
*1307|
[fc]
香ばしいスパイスの香りに、腹が切実な鳴き声を上げ、[r]
早く早くと求めてしまっている。[pcms]
*1308|
[fc]
それは俺だけじゃなく、食堂にいるみんなが同じ思いのようで、[r]
それぞれの目の前に置かれたカレーを見つめている。[pcms]
*1309|
[fc]
深いブラウンのルーの中には、人参にジャガイモ、[r]
それに豚肉の姿が見える。[pcms]
*1310|
[fc]
オーソドックスなポークカレーのようだが、[r]
この奇をてらわない姿が余計に期待感を高めてくれる。[pcms]
*1311|
[fc]
嗚呼、早く食べたい……号令はまだか。[r]
累先輩は一体どこに行ったんだ。[pcms]
[backlay][rui_lo_03_ガスマスク layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1312|
[fc]
[vo_ru s="rui0089"]
[【？？？】]
「さあ、本日の夕食だ！　遠慮なく存分に味わってくれたまえ、諸君！」[pcms][endhact]
*1313|
[fc]
[【央】]
「……は？」[pcms][endhact]
*1314|
[fc]
誰だ、一体……。[pcms]
*1315|
[fc]
食堂に現れたジャージにガスマスクのあからさまな不審人物が、[r]
恐ろしく陽気な声で食事の開始を宣言する。[pcms]
*1316|
[fc]
が、ついさっきまで空腹に追い詰められていた全員がその姿にに呆気に[r]
とられてしまい、スプーンを取ることすら忘れてしまっている。[pcms]
[backlay][mis_lo_03_f10 layer=3 x="&sf.mi_lo_x[3]" y="&sf.mi_lo_y[0]"][trans time=150 method=crossfade][wt]
*1317|
[fc]
[vo_mo s="misuzu0024"]
[【子野日】]
「……誰なんですか？　あの人……」[pcms][endhact]
*1318|
[fc]
俺の隣で、不満げな声でささやく子野日さん。[pcms]
*1319|
[fc]
不満の原因は、今晩の料理当番から外れたことだろう。[pcms]
*1320|
[fc]
折角、西野君の胃袋を掴もうと舌なめずりをしていたのに、[r]
合宿初日は三年生が料理当番をするという伝統に阻まれてしまったからだ。[pcms]
*1321|
[fc]
味とともに部活の伝統や心などを継承してほしい、[r]
という意味でのことらしいんだけど……。[pcms]
*1322|
[fc]
でも、少なくともウチの部には、ガスマスクの不審人物が[r]
食事開始の合図をするなんて伝統は去年までなかったはずだ。[pcms]
[backlay][rui_lo_03_ガスマスク layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1323|
[fc]
[vo_ru s="rui0090"]
[【？？？】]
「ん？　どうしたんだ、諸君。いつでも食べていいんだぞ？」[pcms][endhact]
*1324|
[fc]
戸惑ったようにみんなを促すジャージガスマスクだが……。[pcms]
*1325|
[fc]
誰だろう、なんだか俺にとってとても大切な人物のような気がするような、[r]
しないような……。[pcms]
[backlay][rir_lo_03_f10 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*1326|
[fc]
[vo_ri s="riri0083"]
[【梨里】]
「存分にって、確かに美味しそうだけど……え？　なに？[r]
　そんなの着けて作らなきゃいけない料理なの？　食べて大丈夫なの？」[pcms][endhact]
*1327|
[fc]
声を上げたのは隣に座っている梨里だったけど、[r]
言葉の内容はその場にいる全員の疑問を代弁したものだった。[pcms]
[backlay][rui_lo_03_ガスマスク layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1328|
[fc]
[vo_ru s="rui0091"]
[【？？？】]
「え？　ああ！　いや、すまない、タマネギを切るのに身に着けていたら、[r]
　思いの外馴染んでしまってね。取るのをすっかり忘れていたよ」[pcms][endhact]
[backlay][rui_lo_03_f01 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1329|
[fc]
[【央】]
「る、累先輩！？」[pcms][endhact]
[backlay][sud_lo_03_f31 layer=3 x="&sf.su_lo_x[3]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*1330|
[fc]
[【須田】]
「げっ……部長っ！？」[pcms][endhact]
[backlay][rui_lo_03_f01 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1331|
[fc]
ガスマスクの下から現れた顔は、累先輩のものだった。[pcms]
*1332|
[fc]
そうか、三年生が料理をするということは、累先輩も……！[pcms]
[backlay][mis_lo_03_f10 layer=3 x="&sf.mi_lo_x[3]" y="&sf.mi_lo_y[0]"][trans time=150 method=crossfade][wt]
*1333|
[fc]
[vo_mo s="misuzu0025"]
[【子野日】]
「ずっとそれを着けてたって、会……部長、[r]
　ずっとタマネギ切ってたんですか？」[pcms][endhact]
*1334|
[fc]
俺たちの戦慄に気付いていないようで、[r]
子野日さんが果敢にも累先輩に質問をぶつけた。[pcms]
*1335|
[fc]
その質問に、累先輩の端正な顔が崩れ……。[pcms]
[backlay][rui_lo_03_f12 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1336|
[fc]
[vo_ru s="rui0092"]
[【累】]
「だ、だって、みんな僕にそれしかやらせてくれなかったんだもん！[r]
　僕だってみんなのために、色々やりたかったのに！」[pcms][endhact]
*1337|
[fc]
頬を膨らませ、完全に拗ねた様子で地団太を踏む累先輩。[r]
その様子に、梨里も子野日さんも茫然としてしまっている。[pcms]
[backlay][rir_lo_03_f07 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*1338|
[fc]
[vo_ri s="riri0084"]
[【梨里】]
「え～、と……どういうこと？」[pcms][endhact]
*1339|
[fc]
[【央】]
「ああ、そうか……オマエもマネージャーも、去年はいなかったもんな」[pcms][endhact]
*1340|
[fc]
去年は、陸上部は別の場所で合宿をしていたし、[r]
子野日さんはまだ入学もしていなかった。[pcms]
[fadeoutbgm time=500]
[backlay][chara_int][bg storage="BGskyb"][trans time=500 method=crossfade][wt2]
*1341|
[fc]
だから知らないんだよな、去年の惨劇を……。[pcms]
[bgm storage="bgm11" time=1000]
[backlay][chara_int][bg storage="BGskyb" grayscale=true rgamma=1.3 ggamma=1.1][trans method=universal rule="wave" vague=100 time=1000][wt2]
*1342|
[fc]
去年の合宿での累先輩の料理当番の日、[r]
そこには地獄絵図が広がったのだ。[pcms]
*1343|
[fc]
みんなの意見を取り入れ、最高に美味しい夕飯を作ろうとした累先輩は、[r]
全ての意見を取り入れすぎたカレーを作り上げた。[pcms]
*1344|
[fc]
累先輩命名、『友情カレー』は、後に『新鮮な残飯』と呼ばれるようになった代物であり、[r]
地獄の晩餐に供されるような呪われた合成獣カレーだった。[pcms]
[backlay][red_toplayer][trans method=universal rule="wave" vague=300 time=1000][wt2][hide_chara_int]
[layopt layer=0 grayscale=false]
[layopt layer=3 grayscale=false]
*1345|
[fc]
それらは俺や、累先輩のファンを自認する男子生徒たちの尊い犠牲によって[r]
何とか処理されたものの、あの悲劇は長く語り継がれる黒歴史となった。[pcms]
[fadeoutbgm time=500]
[backlay][bg storage="BG05b"]
[rui_lo_03_f12 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"]
[trans method=universal rule="wipe" vague=300 time=500][wt2]
*1346|
[fc]
まさかそれが、今年もまた……！[pcms]
[bgm storage="bgm01" time=100]
*1347|
[fc]
目の前が真っ暗になりそうな衝撃を受けつつも、[r]
気力を振り絞りスプーンに手を伸ばして……。[pcms]
[backlay][rui_lo_03_f04 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1348|
[fc]
[vo_ru s="rui0093"]
[【累】]
「誰にだって得手不得手というものがあるだろう！？[r]
　僕にだってひとつやふたつあったっていいじゃないか！」[pcms][endhact]
[backlay][rui_lo_03_f05 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1349|
[fc]
完全に拗ねてしまった累先輩を横目で見るたびに、[r]
頬を流れる冷たい汗の雫が増えていく。[pcms]
*1350|
[fc]
せめて……せめて、去年よりはマシであってくれ……。[pcms]
[backlay][sud_lo_03_f10 layer=3 x="&sf.su_lo_x[3]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*1351|
[fc]
[【須田】]
「ま、まあ、部長がタマネギを切るのしかやってないんなら、[r]
　きっと大丈夫なはず……」[pcms][endhact]
*1352|
[fc]
須田も震える手で、なんとかスプーンを持ち上げた。[r]
悲壮としか言いようのない表情は、鏡に映った俺の顔だ。[pcms]
[backlay][rir_lo_03_f08 layer=1 x="&sf.ri_lo_x[1]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*1353|
[fc]
[vo_ri s="riri0085"]
[【梨里】]
「え……？　ちょっ……ホントに大丈夫なんだよね？[r]
　食べてもいいんだよね……？」[pcms][endhact]
[backlay][mis_lo_03_f10 layer=2 x="&sf.mi_lo_x[2]" y="&sf.mi_lo_y[0]"][trans time=150 method=crossfade][wt]
*1354|
[fc]
[vo_mo s="misuzu0026"]
[【子野日】]
「ど、どうなんでしょう……よくわからないですけど、[r]
　先輩たちの反応は……」[pcms][endhact]
*1355|
[fc]
俺たちの様子に、梨里や子野日さんにも悲愴感が伝播してしまったようで、[r]
食堂全体がお通夜のような雰囲気になってしまった。[pcms]
[backlay][chara_int][rui_up_03_f04 layer=3 x="&sf.ru_up_x[3]" y="&sf.ru_up_y[0]"][trans time=150 method=crossfade][wt]
*1356|
[fc]
[vo_ru s="rui0094"]
[【累】]
「もーっ！　もぉぉーーっっ！！　大丈夫だってば！」[pcms][endhact]
*1357|
[fc]
[vo_ru s="rui0095"]
[【累】]
「今年は陸上部の最上君が味を調えてくれたから！[r]
　ちゃんと美味しくなってるよ！　僕のと違ってね！！」[pcms][endhact]
[backlay][chara_int][rui_up_03_f14 layer=3 x="&sf.ru_up_x[3]" y="&sf.ru_up_y[0]"][trans time=150 method=crossfade][wt]
*1358|
[fc]
とうとう目尻に涙を浮かべながら、累先輩が絶叫してしまった。[pcms]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*1359|
[fc]
その言葉は、食堂にいる全員の視線を一点に――[r]
陸上部の最上先輩へと集めた。[pcms]
*1360|
[fc]
思わぬところで注目された最上先輩は、照れたような困ったような感じの笑顔を浮かべて、[r]
手の仕草でみんなにカレーを勧めてくれた。[pcms]
*1361|
[fc]
累先輩と比べたら、地味めで素朴な感じの人だけど、[r]
今この時は大地母神のような慈愛が後光のように差して見える。[pcms]
*1362|
[fc]
[ns【]西野[】nse]
「最上先輩のカレーなんですね。いやぁ、楽しみだなぁ～」[pcms][endhact]
*1363|
[fc]
浮きたった笑顔でマスクを取り、スプーンを持つ西野君。[r]
彼女の手料理ともなれば、嬉しさ百倍だろうな。[pcms]
[backlay][mis_lo_03_g05 layer=3 x="&sf.mi_lo_x[3]" y="&sf.mi_lo_y[0]"][trans time=150 method=crossfade][wt]
*1364|
[fc]
[vo_mo s="misuzu0027"]
[【子野日】]
「……ちっ、どうせマズイに決まってるわよ……わたしの方が……」[pcms][endhact]
*1365|
[fc]
そんな西野君とは対照的に、暗く重く落ち込んでいく子野日さん。[r]
本当に面倒臭いメガネだな、コイツは。[pcms]
[backlay][sud_lo_03_f10 layer=3 x="&sf.su_lo_x[3]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*1366|
[fc]
[【須田】]
「ま、まあ、部長がタマネギしか切ってなくて、[r]
　調理担当が他の人ならきっと大丈夫だろう、うん」[pcms][endhact]
*1367|
[fc]
自分に言い聞かせるような口調の須田が、ボソリと呟く。[pcms]
*1368|
[fc]
ああ、そうだといいな……累先輩が、[r]
無駄に張り切ってそうなことだけが心配だけど……。[pcms]
[backlay][rui_up_03_f02 layer=3 x="&sf.ru_up_x[3]" y="&sf.ru_up_y[0]"][trans time=150 method=crossfade][wt]
*1369|
[fc]
[vo_ru s="rui0096"]
[【累】]
「ほらっ、みんな手を合わせて！　いただきます！！」[pcms][endhact]
*1370|
[fc]
これが、俺たちの最後の晩餐になった……、[r]
なんてことにならなきゃいいな……。[pcms]
[stopse_all]
[sysbt_meswin clear]
[backlay][chara_int][bg storage="BGskyb"][trans time=1000 method=crossfade][wt2]
[wait2 time=500]
[backlay][bg storage="BGskyc"][trans time=1000 method=crossfade][wt2]
[wait2 time=500]
[backlay][bg storage="BG05c"][trans time=500 method=crossfade][wt2]
[sysbt_meswin]
*1371|
[fc]
[【央】]
「うん、美味い。ちゃんとしたカレーだ」[pcms][endhact]
[backlay][sud_lo_03_f01 layer=3 x="&sf.su_lo_x[3]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*1372|
[fc]
[【須田】]
「ああ、どうやら命永らえたみたいだな、俺たち」[pcms][endhact]
[backlay][rir_lo_03_f20 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*1373|
[fc]
[vo_ri s="riri0086"]
[【梨里】]
「もう、アンタたちが脅かすから、あたしまで怖くなっちゃったじゃない」[pcms][endhact]
[backlay][mis_lo_03_g02 layer=3 x="&sf.mi_lo_x[3]" y="&sf.mi_lo_y[0]"][trans time=150 method=crossfade][wt]
*1374|
[fc]
[vo_mo s="misuzu0028"]
[【子野日】]
「うぅっ……わ、わたしの方が美味しく作れる……はず……」[pcms][endhact]
[backlay][rui_lo_03_f01 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1375|
[fc]
[vo_ru s="rui0097"]
[【累】]
「本当に失礼だね、渋江君も須田君も……うん、美味しいな。[r]
　都内の名店で食べる欧州風カレーにも負けてない」[pcms][endhact]
*1376|
[fc]
まだ若干、拗ねた様子を残しているものの、[r]
いつもの調子を取り戻した累先輩がカレーを食べ、満足そうに論評する。[pcms]
*1377|
[fc]
[【央】]
「そんな店に行ったことがあるんですか？」[pcms][endhact]
[backlay][rui_lo_03_f07 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1378|
[fc]
[vo_ru s="rui0098"]
[【累】]
「ん？　ああ、両親の薦めでね」[pcms][endhact]
[backlay][rui_lo_03_f01 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1379|
[fc]
[vo_ru s="rui0099"]
[【累】]
「歌舞伎や舞台劇などのライブでしか味わえない芸術に触れた方がいいと、[r]
　月に一度は都内に行って観劇をしているんだよ。その時にね」[pcms][endhact]
*1380|
[fc]
おお……流石にお嬢様だな。[pcms]
[backlay][rir_lo_03_f01 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*1381|
[fc]
[vo_ri s="riri0087"]
[【梨里】]
「蘆名先輩がよく上京してるって噂だったけど、ホントだったんですね」[pcms][endhact]
[backlay][rui_lo_03_f26 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1382|
[fc]
[vo_ru s="rui0100"]
[【累】]
「まあ、我が家の教育方針というようなものかな。有り難く甘えさせて[r]
　もらっているよ。お陰で美味しい物の食べ歩きも出来ているしね」[pcms][endhact]
[backlay][rui_lo_03_f01 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1383|
[fc]
確かに、累先輩が練習を休む時が月に一度はあるし、[r]
連休の時はほぼ必ずと言っていいくらい休んでいる。[pcms]
*1384|
[fc]
部活に熱心な累先輩が休むなんて珍しい、と思っていたけど、[r]
そんな理由があったのか。[pcms]
*1385|
[fc]
[vo_ru s="rui0101"]
[【累】]
「映画だったら明田市内の涼ヶ陵モールのシネコンに行けば済むんだけれど、[r]
　大きめの舞台や歌舞伎となると、どうしてもね」[pcms][endhact]
*1386|
[fc]
楽しそうに語る累先輩の様子からも、本当に楽しんでいるんだなと思える。[r]
お金持ちの娯楽はスケールが大きいや。[pcms]
[backlay][mis_lo_03_f07 layer=3 x="&sf.mi_lo_x[3]" y="&sf.mi_lo_y[0]"][trans time=150 method=crossfade][wt]
*1387|
[fc]
[vo_mo s="misuzu0029"]
[【子野日】]
「泊りがけで行っているんですか？　日帰りはちょっと無理でしょうし」[pcms][endhact]
[backlay][rui_lo_03_f01 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1388|
[fc]
[vo_ru s="rui0102"]
[【累】]
「そうだね。都内の大学に通っている従兄の部屋にお世話になっているよ。[r]
　食べ歩きの時も付き合ってもらっていて、助かってるよ」[pcms][endhact]
*1389|
[fc]
むぅっ……累先輩とひとつ屋根の下で、[r]
さらにはデートまで……なんて羨ましいんだ。[pcms]
*1390|
[fc]
一回くらい代わってほしいぞ。[pcms]
[backlay][sud_lo_03_f07 layer=3 x="&sf.su_lo_x[3]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*1391|
[fc]
[【須田】]
「そういや、涼ヶ陵モールといえば、先々週だっけ？　ウチの女子連中が、[r]
　あそこでデートしてる高橋ちゃんと大久保コーチを見たって言ってたの」[pcms][endhact]
*1392|
[fc]
[【央】]
「ああ、そういやそんな話してたけど……」[pcms][endhact]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*1393|
[fc]
先々週にデートをして、今、二人一緒に夏風邪って。[r]
何だか生々しいな。飯食ってる時にあんまり想像したくないぞ。[pcms]
*1394|
[fc]
とはいえ、涼ヶ陵モールで二人を見かけたっていうのは、[r]
そんなに不思議なことじゃないだろう。[pcms]
*1395|
[fc]
涼ヶ陵モールは県内最大の郊外型モールで、[r]
県内のみならず県外からも客が集まるくらいの場所だし。[pcms]
*1396|
[fc]
ショッピングセンターのみならずレジャー施設も充実しているから、[r]
デートスポットとしては最適だ。[pcms]
*1397|
[fc]
その余波を受けて、地元の商店街が大打撃をうけてしまったっていう、[r]
あんまり喜べない話もあるけど。[pcms]
*1398|
[fc]
そういや、梨里と顕悟も涼ヶ陵モールに一緒に行って、[r]
ケンカしたってこともあったな。[pcms]
*1399|
[fc]
ケンカばっかりしてるな、コイツら。[r]
もっと素直になればいいのに。[pcms]
*1400|
[fc]
そんなことを考えながら、梨里に目を向ける。[pcms]
[backlay][rir_up_03_f07 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*1401|
[fc]
[vo_ri s="riri0088"]
[【梨里】]
「んむ？　にゃによぉ」[pcms][endhact]
*1402|
[fc]
[【央】]
「いや、何でもない」[pcms][endhact]
*1403|
[fc]
視線に気付いた梨里が、口いっぱいにカレーを頬張りながら不思議そうに[r]
見返してくる。[pcms]
*1404|
[fc]
確かに美味いカレーだけど、そこまでがっつかなくてもいいだろうに。[pcms]
*1405|
[fc]
ちょっと呆れながら、梨里の頬っぺたについたカレーのルーを拭いてやろうと[r]
ナプキンを手に取ると……。[pcms]
[backlay][jun_lo_04_f01 layer=3 x="&sf.ju_lo_x[3]" y="&sf.ju_lo_y[0]"][trans time=150 method=crossfade][wt]
*1406|
[fc]
[vo_ju s="jun0016"]
[【純】]
「おっ、いたいた。やっほー、梨里。一緒していい？」[pcms][endhact]
[backlay][chara_int]
[rir_up_03_f07 layer=1 x="&sf.ri_up_x[1]" y="&sf.ri_up_y[0]"]
[jun_up_04_f01 layer=2 x="&sf.ju_up_x[2]" y="&sf.ju_up_y[0]"][trans time=150 method=crossfade][wt]
*1407|
[fc]
[vo_ri s="riri0089"]
[【梨里】]
「んぐっ、むぐ……おー、純ちんもご飯？」[pcms][endhact]
*1408|
[fc]
トレイをもった五十嵐さんが、梨里の隣にひょっこりと現れ、[r]
返事よりも先にそこに座った。[pcms]
[backlay][chara_int][sud_lo_03_f08 layer=3 x="&sf.su_lo_x[3]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*1409|
[fc]
[【須田】]
「おい、誰だよこのカワイイ子」[pcms][endhact]
*1410|
[fc]
予想通りというかなんというか、[r]
一番最初に五十嵐さんに反応したのはやっぱり須田だった。[pcms]
*1411|
[fc]
だが、五十嵐さんは須田なんかよりも梨里の食べているカレーの方に[r]
興味があるみたいだから、わざわざ紹介しなくてもいいかな。[pcms]
[backlay][chara_int]
[rir_up_03_f01 layer=1 x="&sf.ri_up_x[1]" y="&sf.ri_up_y[0]"]
[jun_up_04_f01 layer=2 x="&sf.ju_up_x[2]" y="&sf.ju_up_y[0]"][trans time=150 method=crossfade][wt]
*1412|
[fc]
[vo_ju s="jun0017"]
[【純】]
「そのカレーって、梨里んトコで作ったの？　ん～、それも楽しそう。[r]
　ウチはセンターで用意してくれてるご飯だからなぁ」[pcms][endhact]
[backlay]
[rir_up_03_f02 layer=1 x="&sf.ri_up_x[1]" y="&sf.ri_up_y[0]"]
[jun_up_04_f01 layer=2 x="&sf.ju_up_x[2]" y="&sf.ju_up_y[0]"][trans time=150 method=crossfade][wt]
*1413|
[fc]
[vo_ri s="riri0090"]
[【梨里】]
「そう？　純のも美味しそうじゃん。ポークソテー？　一枚ちょーだい！」[pcms][endhact]
[backlay]
[rir_up_03_f02 layer=1 x="&sf.ri_up_x[1]" y="&sf.ri_up_y[0]"]
[jun_up_04_f04 layer=2 x="&sf.ju_up_x[2]" y="&sf.ju_up_y[0]"][trans time=150 method=crossfade][wt]
*1414|
[fc]
[vo_ju s="jun0018"]
[【純】]
「ヤダっ！　三枚しかないのに一枚あげたら足りなくなっちゃうじゃん！」[pcms][endhact]
[backlay]
[rir_up_03_f02 layer=1 x="&sf.ri_up_x[1]" y="&sf.ri_up_y[0]"]
[jun_up_04_f05 layer=2 x="&sf.ju_up_x[2]" y="&sf.ju_up_y[0]"][trans time=150 method=crossfade][wt]
*1415|
[fc]
純さんが加わっただけで、随分とにぎやかになったな。[r]
その方が合宿の夜って感じのにぎやかさで楽しいけど。[pcms]
[backlay]
[rir_up_03_g01 layer=1 x="&sf.ri_up_x[1]" y="&sf.ri_up_y[0]"]
[jun_up_04_f07 layer=2 x="&sf.ju_up_x[2]" y="&sf.ju_up_y[0]"][trans time=150 method=crossfade][wt]
*1416|
[fc]
[vo_ri s="riri0091"]
[【梨里】]
「純のケチー……あ、そういえばさ、午後にパトカー来てたんだけど、[r]
　知ってる？」[pcms][endhact]
*1417|
[fc]
[【央】]
「パトカー？」[pcms][endhact]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*1418|
[fc]
午後はプールにいたから、外の様子はわからなかったけど……。[r]
パトカーなんて、一体何だろう。[pcms]
*1419|
[fc]
来る時の事故のことでなのか、それとも午前中に見たどこかの学校の[r]
サッカー部の流血事故のことでなのか。[pcms]
[backlay][jun_lo_04_f07 layer=3 x="&sf.ju_lo_x[3]" y="&sf.ju_lo_y[0]"][trans time=150 method=crossfade][wt]
*1420|
[fc]
[vo_ju s="jun0019"]
[【純】]
「そう言えば、他の学園のサッカー部で乱闘事件があったみたいだよ？[r]
　練習中にケンカになって、ヘッドバット入れたんだって」[pcms][endhact]
[backlay][sud_lo_03_f08 layer=3 x="&sf.su_lo_x[3]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*1421|
[fc]
[【須田】]
「はぁ？　いくらなんでもチームメイトに頭突きかますか？」[pcms][endhact]
[backlay][rui_lo_03_f10 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1422|
[fc]
[vo_ru s="rui0103"]
[【累】]
「ああ、そんなことがあったみたいだね。でも、練習中のいざこざで[r]
　警察を呼んだりするかな」[pcms][endhact]
[backlay][rir_up_03_f07 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*1423|
[fc]
[vo_ri s="riri0092"]
[【梨里】]
「いや、それとは関係なくて、周回道路にランニングに出てた長距離組から[r]
　聞いた話なんだけどね」[pcms][endhact]
*1424|
[fc]
カレーをパクつきながら、話を進めていく梨里。[pcms]
*1425|
[fc]
いつの間にか、累先輩も五十嵐さんも、[r]
須田も子野日さんもみんなが梨里の話に聞き入っている。[pcms]
*1426|
[fc]
まあ、今日は朝からあんな調子だったから、[r]
実はみんな内心ピリピリしているのかもしれないな。[pcms]
[backlay][rir_up_03_f08 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*1427|
[fc]
[vo_ri s="riri0093"]
[【梨里】]
「周回道路に、車が置きっぱなしになってたんだって。[r]
　路駐とかじゃなくて、ドアも開いててキーもつけっぱなしって状態で」[pcms][endhact]
[backlay][rui_up_03_f05 layer=3 x="&sf.ru_up_x[3]" y="&sf.ru_up_y[0]"][trans time=150 method=crossfade][wt]
*1428|
[fc]
[vo_ru s="rui0104"]
[【累】]
「ふむ、それはなかなか不用心なことだね。いくら田舎だといっても、[r]
　車の管理はきっちりしないと」[pcms][endhact]
*1429|
[fc]
福神漬けを皿に追加しながら、累先輩が軽く首を傾げた。[pcms]
*1430|
[fc]
家の鍵をかけないことはよくあっても、流石に車のキーをつけっぱなしというのは[r]
こんな田舎だとしてもまずありえない。[pcms]
[backlay][rir_up_03_f07 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*1431|
[fc]
[vo_ri s="riri0094"]
[【梨里】]
「それが路肩に止めてたとかじゃなくて、道に斜めに停めてあったらしいんで[r]
　すよ。そして、ボンネットには何かをはねた跡があって……」[pcms][endhact]
[backlay][sud_up_03_f07 layer=3 x="&sf.su_up_x[3]" y="&sf.su_up_y[0]"][trans time=150 method=crossfade][wt]
*1432|
[fc]
[【須田】]
「熊でもはねたんじゃないの？　そうでなきゃカモシカとか」[pcms][endhact]
[backlay][mis_up_03_f07 layer=3 x="&sf.mi_up_x[3]" y="&sf.mi_up_y[0]"][trans time=150 method=crossfade][wt]
*1433|
[fc]
[vo_mo s="misuzu0030"]
[【子野日】]
「熊もカモシカもこの辺りまでは降りてこないでしょう。[r]
　仮に熊が降りてきていたとしたら、それはそれで大変ですよ？」[pcms][endhact]
*1434|
[fc]
それぞれ、てんでバラバラに梨里の話を聞きながら茶々を入れている。[r]
大人しく聞いてるのは俺と五十嵐さんだけじゃないか。[pcms]
*1435|
[fc]
……って、五十嵐さん、食べるのにメッチャ集中してるな……。[r]
聞いてるのか怪しいところだ。[pcms]
[backlay][rir_up_03_f07 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*1436|
[fc]
[vo_ri s="riri0095"]
[【梨里】]
「それで、誰かを轢いた運転手が、その人もろとも田澤湖に入って自殺[r]
　したんじゃないかとか、センターに助けを求めに来たんじゃないかとか」[pcms][endhact]
*1437|
[fc]
[vo_ri s="riri0096"]
[【梨里】]
「それでパトカーが事情を聞きに来たみたいなの」[pcms][endhact]
*1438|
[fc]
[【央】]
「運転手がいないって、それって……」[pcms][endhact]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*1439|
[fc]
俺の漏らした呟きに、みんなの顔が軽く強張り、[r]
誰からともなく小さく頷いた。[pcms]
*1440|
[fc]
事故車から運転手が失踪するっていう状況は……。[pcms]
[backlay][jun_up_04_f12 layer=3 x="&sf.ju_up_x[3]" y="&sf.ju_up_y[0]"][trans time=150 method=crossfade][wt]
*1441|
[fc]
[vo_ju s="jun0020"]
[【純】]
「あ、聞いたよ、その事故の話。梨里たちが来る時に[r]
　巻き込まれちゃったってヤツでしょ？　気味悪いよねー」[pcms][endhact]
*1442|
[fc]
お、聞いてたみたいだ。[r]
っていうか、朝の事故のことも聞いてたんだな。[pcms]
*1443|
[fc]
口の中に残ったものを飲み込み、五十嵐さんが軽く体を乗り出してきた。[pcms]
*1444|
[fc]
シャツにポークソテーのソースが付かないかちょっと気になったが、[r]
五十嵐さん的にはそれどころじゃないらしい。[pcms]
[backlay][jun_up_04_f05 layer=3 x="&sf.ju_up_x[3]" y="&sf.ju_up_y[0]"][trans time=150 method=crossfade][wt]
*1445|
[fc]
[vo_ju s="jun0021"]
[【純】]
「これって、ウチの先輩から聞いた話なんだけどね……」[pcms][endhact]
[stopse_all]
[sysbt_meswin clear]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
fadeoutbgm time=500]
[wait2 time=1000]
[bgm storage="bgm11" time=500]
[backlay][bg storage="BG05c"]
[jun_up_04_f05 layer=3 x="&sf.ju_up_x[3]" y="&sf.ju_up_y[0]"]
[trans time=500 method=crossfade][wt2]
[sysbt_meswin]
*1446|
[fc]
[vo_ju s="jun0022"]
[【純】]
「……っていう話なんだけどね」[pcms][endhact]
[backlay][rir_lo_03_f10 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*1447|
[fc]
[vo_ri s="riri0097"]
[【梨里】]
「いや……ちょっとそれ、マジで怖いヤツじゃん……」[pcms][endhact]
*1448|
[fc]
五十嵐さんの話が終わり、梨里が軽く青ざめた顔で呟いた。[pcms]
*1449|
[fc]
カレーを全部食べ終わった後で良かったな。[r]
途中だったら食欲を無くしてたかもしれないな、これは。[pcms]
[backlay][rui_lo_03_f07 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1450|
[fc]
[vo_ru s="rui0105"]
[【累】]
「ふむ……どうにも穏やかじゃない話だね。[r]
　そういう事件が多発しているっていうことなのかな」[pcms][endhact]
*1451|
[fc]
一方の累先輩は、これといって怖がっている様子はない。[r]
流石……って言っていいのかな。[pcms]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*1452|
[fc]
五十嵐さんの話は、彼女の先輩が見てきたことだそうだ。[pcms]
*1453|
[fc]
田澤湖のお土産屋やレストランのある辺りに行ったときに、[r]
やっぱり警官が来ていたのだそうだ。[pcms]
*1454|
[fc]
店の人の話では、駐車場に何日も停められている車があって、[r]
持ち主が行方不明らしい。[pcms]
*1455|
[fc]
両親と子供二人の家族四人が駐車していったのは憶えていたそうだけど、[r]
その家族が戻ってきたところを誰も見ていないそうだ。[pcms]
*1456|
[fc]
つまり、一家心中したんじゃ……と、五十嵐さんのトコじゃ今、[r]
もっぱらの噂になっているそうだ。[pcms]
*1457|
[fc]
[【央】]
「一家心中って言っても……」[pcms][endhact]
[backlay][bg storage="BG01c"][trans time=500 method=crossfade][wt2]
*1458|
[fc]
梨里が怯えたような表情で見ていた窓の外に、[r]
俺も視線を向けた。[pcms]
*1459|
[fc]
そこに広がっているのは、黄昏時の田澤湖の景色。[pcms]
*1460|
[fc]
昼間はあんなにもキレイだったのに、[r]
この話を聞いたせいか奇妙な不気味さを湖面から感じてしまう。[pcms]
*1461|
[fc]
この辺りで一家心中っていったら、やっぱり……。[pcms]
[backlay]
[bg storage="BG05c"]
[mis_lo_03_f07 layer=3 x="&sf.mi_lo_x[3]" y="&sf.mi_lo_y[0]"]
[trans time=500 method=crossfade][wt2]
*1462|
[fc]
[vo_mo s="misuzu0031"]
[【子野日】]
「今朝のニュースにあった新幹線の中での暴力事件みたいに、[r]
　暴漢に襲われて行方不明になったっていう可能性もありそうですね」[pcms][endhact]
*1463|
[fc]
子野日さんの言葉に、俺も梨里も窓の外から視線を戻す。[pcms]
*1464|
[fc]
[【央】]
「最近、多いみたいだしね」[pcms][endhact]
*1465|
[fc]
なるほど、そういう可能性もあるな。[r]
あとは、単純に事故とか。一家心中って決まったわけじゃないんだし。[pcms]
[backlay][chara_int]
[rir_lo_03_f08 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[jun_lo_04_f07 layer=5 x="&sf.ju_lo_x[5]" y="&sf.ju_lo_y[0]"][trans time=150 method=crossfade][wt]
*1466|
[fc]
[vo_ri s="riri0098"]
[【梨里】]
「え？　なにそれ、そんなことあったの？」[pcms][endhact]
[backlay]
[rir_lo_03_f07 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[jun_lo_04_f07 layer=5 x="&sf.ju_lo_x[5]" y="&sf.ju_lo_y[0]"][trans time=150 method=crossfade][wt]
*1467|
[fc]
[vo_ju s="jun0023"]
[【純】]
「わたしも初耳。どういう事件なの、それ」[pcms][endhact]
*1468|
[fc]
そういえば、梨里には教えてなかったな、新幹線の緊急停止の話。[pcms]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*1469|
[fc]
顕悟が乗っているかも、ということは言わないまま、[r]
簡単に事件の内容をかいつまんで話す。[pcms]
[backlay][rui_lo_03_f05 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1470|
[fc]
[vo_ru s="rui0106"]
[【累】]
「なるほど……だが、それは新幹線や電車だから緊急停止で済んだが、[r]
　走っているバスの中だったりしたら……」[pcms][endhact]
*1471|
[fc]
累先輩も初耳だったようで、少し考え込んだ後で、[r]
そんな感想を口にした。[pcms]
*1472|
[fc]
確かに、先輩の言う通りだな。[r]
運転手が襲われたら一般道でも危ないし、高速道路だったら大惨事確実だ。[pcms]
[backlay][sud_lo_03_f07 layer=3 x="&sf.su_lo_x[3]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*1473|
[fc]
[【須田】]
「そういえば、ネットニュースで見たんだけど……」[pcms][endhact]
*1474|
[fc]
と、切り出した須田の話は、[r]
失踪者のほとんどがちゃんと見つかっているらしいというものだった。[pcms]
*1475|
[fc]
ただし、その大半が脳疾患なのか心神喪失なのか。[pcms]
*1476|
[fc]
精神状態がおかしくなっているそうで、[r]
まともな証言が得られていないのだという。[pcms]
[backlay][sud_lo_03_f05 layer=3 x="&sf.su_lo_x[3]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*1477|
[fc]
[【須田】]
「そうじゃないのは行き倒れて死んでるとかだってさ。そういうのは、[r]
　自殺とか病死で片付けられてるらしいよ」[pcms][endhact]
*1478|
[fc]
[【須田】]
「そうなると事件性はないってことになるみたいだし」[pcms][endhact]
[backlay][rui_lo_03_f07 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1479|
[fc]
[vo_ru s="rui0107"]
[【累】]
「病気……渋江君、例のあのオカルト系サイトの話」[pcms][endhact]
*1480|
[fc]
[【央】]
「ええ」[pcms][endhact]
*1481|
[fc]
俺も累先輩と同じように、あの話を思い出していた。[r]
米軍のウイルス云々という、あの話。[pcms]
*1482|
[fc]
与太話だと思って今の今まで忘れていたけど、[r]
こうなると信憑性があるような気がしてならない。[pcms]
[backlay][rir_lo_03_f07 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*1483|
[fc]
[vo_ri s="riri0099"]
[【梨里】]
「なに、オカルト系サイトの話って……」[pcms][endhact]
*1484|
[fc]
顔を軽く青ざめさせた梨里が、恐る恐るといった調子で聞いてくる。[r]
そんなに怖いのなら聞かない方がいいんじゃないかって思うんだけど……。[pcms]
*1485|
[fc]
でも、梨里だけじゃなく他のみんなも聞きたそうにしている。[pcms]
*1486|
[fc]
俺は少し考え、例のサイトの推論を話した。[pcms]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*1487|
[fc]
軍が作ったウイルス、っていう点はあまりにも無理があるから、[r]
そこだけを省いて。[pcms]
*1488|
[fc]
話を終えると、無駄ににぎやかな須田でさえも、言葉を失っていた。[pcms]
*1489|
[fc]
そして、食堂の中を固い動きで見回して――[pcms]
[backlay][sud_lo_03_f10 layer=3 x="&sf.su_lo_x[3]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*1490|
[fc]
[【須田】]
「……マスクしてるヤツ、結構いるよな」[pcms][endhact]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*1491|
[fc]
先生やコーチの固まっているテーブルだと、[r]
マスクをしていないのは陸上コーチの畠山さんだけだし……。[pcms]
*1492|
[fc]
生徒の中だと西野君や佐竹先輩以外にもちらほらいる。[pcms]
*1493|
[fc]
他にも、風邪気味だけど咳は出ていないからと、[r]
マスクをしていないのも何人かいたはずだ。[pcms]
*1494|
[fc]
余所の学園の中にも、マスク姿の生徒が目立つ。[pcms]
*1495|
[fc]
イヤな空気が、俺たちのテーブルの上に落ちる。[r]
何を話せばいいのか。何を話しても明るい話題にはなりそうにない。[pcms]
[backlay][jun_lo_04_f05 layer=3 x="&sf.ju_lo_x[3]" y="&sf.ju_lo_y[0]"][trans time=150 method=crossfade][wt]
*1496|
[fc]
[vo_ju s="jun0024"]
[【純】]
「……脅かすわけじゃないんだけどさ……央君の話、信憑性があるかも」[pcms][endhact]
*1497|
[fc]
沈黙を破ったのは、五十嵐さんだった。[r]
出来れば、もう少し明るい感じで破ってほしかったけど。[pcms]
*1498|
[fc]
そんな、ますます暗くなりそうな出だしで始まった五十嵐さんの話は、[r]
やっぱり明るさとは無縁のものだった。[pcms]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*1499|
[fc]
明田市内の大学病院で、外来で来ていたお爺さんが暴れ出す、[r]
っていう事件があったらしい。[pcms]
*1500|
[fc]
そのお爺さんは、夏風邪をひいたといって診察してもらいに来た。[pcms]
*1501|
[fc]
だが、警察に連れて行かれた後、ニュースにはなっていないがその翌日、[r]
急死したという。[pcms]
[backlay][rir_lo_03_f16 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*1502|
[fc]
[vo_ri s="riri0100"]
[【梨里】]
「……マジで？」[pcms][endhact]
*1503|
[fc]
本格的に青ざめてきた梨里に、大きく頷く五十嵐さん。[r]
この流れでそんな話じゃ、梨里じゃなくても真っ青になるっての。[pcms]
[backlay][jun_lo_04_f05 layer=3 x="&sf.ju_lo_x[3]" y="&sf.ju_lo_y[0]"][trans time=150 method=crossfade][wt]
*1504|
[fc]
[vo_ju s="jun0025"]
[【純】]
「マジマジ。大学病院で看護師してる、[r]
　勇二のお母さんから聞いた話だから確かよ」[pcms][endhact]
[backlay][sud_lo_03_f05 layer=3 x="&sf.su_lo_x[3]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*1505|
[fc]
[【須田】]
「……勇二？　誰？」[pcms][endhact]
*1506|
[fc]
須田の間の抜けた声に、五十嵐さんがキョトンとし、[r]
そしてすぐに赤面していく。[pcms]
[backlay][jun_lo_04_f11 layer=3 x="&sf.ju_lo_x[3]" y="&sf.ju_lo_y[0]"][trans time=150 method=crossfade][wt]
*1507|
[fc]
[vo_ju s="jun0026"]
[【純】]
「え、え～と……か、彼氏……？」[pcms][endhact]
*1508|
[fc]
[【央】]
「チッ！」[pcms][endhact]
[backlay][sud_up_03_f05 layer=3 x="&sf.su_up_x[3]" y="&sf.su_up_y[0]"][trans time=150 method=crossfade][wt]
*1509|
[fc]
[【須田】]
「チッ！」[pcms][endhact]
[backlay][mis_up_03_g05 layer=3 x="&sf.mi_up_x[3]" y="&sf.mi_up_y[0]"][trans time=150 method=crossfade][wt]
*1510|
[fc]
[vo_mo s="misuzu0032"]
[【子野日】]
「チッ！」[pcms][endhact]
[backlay][rir_up_03_g02 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*1511|
[fc]
[vo_ri s="riri0101"]
[【梨里】]
「チッ！」[pcms][endhact]
[backlay][rui_up_03_g03 layer=3 x="&sf.ru_up_x[3]" y="&sf.ru_up_y[0]"][trans time=150 method=crossfade][wt]
*1512|
[fc]
[vo_ru s="rui0108"]
[【累】]
「いやキミは別にいいんじゃないのかな？」[pcms][endhact]
[fadeoutbgm time=500]
*1513|
[fc]
累先輩のツッコミで、張り詰めていた空気が一気に弛緩した。[pcms]
*1514|
[fc]
ちょっと気に入らないけど、あんな空気のままでいるよりはまだマシだ。[pcms]
[backlay][jun_lo_04_f01 layer=3 x="&sf.ju_lo_x[3]" y="&sf.ju_lo_y[0]"][trans time=150 method=crossfade][wt]
*1515|
[fc]
[vo_ju s="jun0027"]
[【純】]
「ま、まあ、こういう怖い話ってついつい入り込んじゃうよね～」[pcms][endhact]
[bgm storage="bgm11" time=100]
[backlay][mis_lo_03_g01 layer=3 x="&sf.mi_lo_x[3]" y="&sf.mi_lo_y[0]"][trans time=150 method=crossfade][wt]
*1516|
[fc]
[vo_mo s="misuzu0033"]
[【子野日】]
「夏は怪談ですからね。たとえば……このスポーツセンターに伝わる話とか」[pcms][endhact]
[sysbt_meswin clear]
[backlay][evcg storage="EV42_01" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
[sysbt_meswin]
*1517|
[fc]
子野日さんのメガネが照明を受けてキラリと光り、[r]
声のトーンが一段下がる。[pcms]
*1518|
[fc]
ただそれだけで、梨里の口から小さな悲鳴が漏れた。[pcms]
*1519|
[fc]
[vo_mo s="misuzu0034"]
[【子野日】]
「夜になると、田澤湖に身投げした女の人が、全裸のまま『どこ……、[r]
　どこ……』って呟きながら、何かを探し求めて歩き回るそうです……」[pcms][endhact]
[backlay]
[bg storage="BG05c"]
[jun_lo_04_f07 layer=3 x="&sf.ju_lo_x[3]" y="&sf.ju_lo_y[0]"]
[trans time=500 method=crossfade][wt]
*1520|
[fc]
[vo_ju s="jun0028"]
[【純】]
「あ、その話、涼ヶ陵に住んでる従姉妹の朋美ねえちゃんに聞いた！」[pcms][endhact]
[backlay][rir_lo_03_f16 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*1521|
[fc]
[vo_ri s="riri0102"]
[【梨里】]
「う、ウソでしょ？　ウソよね？　ウソに決まってるんだからっ」[pcms][endhact]
*1522|
[fc]
体を震わせ、寄りかかってくる梨里。[r]
こういうの弱いからな、コイツ。[pcms]
*1523|
[fc]
物理攻撃無効が弱点だな。[pcms]
[backlay][mis_lo_03_f07 layer=3 x="&sf.mi_lo_x[3]" y="&sf.mi_lo_y[0]"][trans time=150 method=crossfade][wt]
*1524|
[fc]
[vo_mo s="misuzu0035"]
[【子野日】]
「あとは、紙袋を被った怪人とか……」[pcms][endhact]
[backlay][sud_lo_03_f10 layer=3 x="&sf.su_lo_x[3]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*1525|
[fc]
[【須田】]
「それは映画の話じゃないのか？」[pcms][endhact]
[backlay][mis_lo_03_f07 layer=3 x="&sf.mi_lo_x[3]" y="&sf.mi_lo_y[0]"][trans time=150 method=crossfade][wt]
*1526|
[fc]
[vo_mo s="misuzu0036"]
[【子野日】]
「その他にもありますよ……たとえば……」[pcms][endhact]
[backlay][rir_lo_03_f17 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*1527|
[fc]
[vo_ri s="riri0103"]
[【梨里】]
「お、オバケなんていないんだよ～……そんなの幻覚なんだから～……」[pcms][endhact]
*1528|
[fc]
耳を塞ぎ、小声で呟きながらグイグイと強く寄りかかってきた。[r]
そんなに押されるとイスから落ちちゃうからやめてほしいんだけど。[pcms]
[backlay][sud_lo_03_f07 layer=3 x="&sf.su_lo_x[3]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*1529|
[fc]
[【須田】]
「……あれ？」[pcms][endhact]
*1530|
[fc]
[【央】]
「なんだよ……あっ！」[pcms][endhact]
[backlay][jun_lo_04_f07 layer=3 x="&sf.ju_lo_x[3]" y="&sf.ju_lo_y[0]"][trans time=150 method=crossfade][wt]
*1531|
[fc]
[vo_ju s="jun0029"]
[【純】]
「お、ど、どうしたの？」[pcms][endhact]
*1532|
[fc]
思わず声を上げてしまった俺と須田。[pcms]
*1533|
[fc]
子野日さんの語る怪談のひとつめ、女の霊には心当たりがあるからだ。[pcms]
*1534|
[fc]
慌てて顔を伏せ、視線をシャットアウトする。[r]
そんな俺たちを見て――[pcms]
[backlay][rui_up_03_g03 layer=3 x="&sf.ru_up_x[3]" y="&sf.ru_up_y[0]"][trans time=150 method=crossfade][wt]
*1535|
[fc]
[vo_ru s="rui0109"]
[【累】]
「う～ん……多分その、夜中に歩いている全裸の女の幽霊というのは、[r]
　多分だけど僕のことなんじゃないかな」[pcms][endhact]
[backlay][mis_lo_03_f07 layer=3 x="&sf.mi_lo_x[3]" y="&sf.mi_lo_y[0]"][trans time=150 method=crossfade][wt]
*1536|
[fc]
[vo_mo s="misuzu0037"]
[【子野日】]
「……は？」[pcms][endhact]
[backlay][jun_lo_04_f07 layer=3 x="&sf.ju_lo_x[3]" y="&sf.ju_lo_y[0]"][trans time=150 method=crossfade][wt]
*1537|
[fc]
[vo_ju s="jun0030"]
[【純】]
「え？　それって……どういうことなんです？」[pcms][endhact]
[backlay][rir_lo_03_f17 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*1538|
[fc]
[vo_ri s="riri0104"]
[【梨里】]
「ヤダヤダヤダっ……幻よ、ウソなのよぉ～……」[pcms][endhact]
*1539|
[fc]
困惑の声を上げる子野日さんと五十嵐さん。[pcms]
*1540|
[fc]
梨里はというと、累先輩のカミングアウトも耳に入らないまま、[r]
まだ俺をイスから追い落とそうとしてきている。[pcms]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*1541|
[fc]
まあ、そんな梨里は放っておくとして。[pcms]
*1542|
[fc]
先輩の存在が怪異として伝えられていることについては、[r]
画仙水泳部が封印した禁断の記憶……。[pcms]
*1543|
[fc]
『真夜中のお散歩事件』を紐解かねばなるまい――[pcms]
[stopse_all]
[sysbt_meswin clear]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
[wait2 time=500]
[backlay][bg storage="BG03d"][trans method=universal rule="wave" vague=300 time=500][wt2]
[wait2 time=500]
[backlay][tak_lo_03a_f10 layer=3 x="&sf.ta_lo_x[3]" y="&sf.ta_lo_y[0]"][trans time=150 method=crossfade][wt]
[sysbt_meswin]
*1544|
[fc]
[vo_mo s="takahasi0007"]
[【高橋】]
「ううっ、やだなぁ……こんな広いところ、一人で見回りなんて……。[r]
　早く終わらせて……」[pcms][endhact]
*1545|
[fc]
[vo_mo s="takahasi0008"]
[【高橋】]
「ヒィッ！？　な、なに！？　足音っ……だ、誰かいるの！？」[pcms][endhact]
[sysbt_meswin clear]
[backlay][evcg storage="EV43_03" layer=0 page=back visible=true left=0 top=0][trans method=universal rule="TtoD" vague=300 time=200][wt2]
[sysbt_meswin]
*1546|
[fc]
[vo_mo s="takahasi0009"]
[【高橋】]
「ぃひぁっ……きぃぁぁあああああぁぁぁぁぁぁぁぁっっ！！！！！」[pcms][endhact]
[backlay][bg storage="BG03d"]
[rui_lo_06_k03 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=300 method=crossfade][wt2]
[wait2 time=500]
[backlay][rui_lo_06_k04 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=500 method=crossfade][wt2]
*1547|
[fc]
[vo_ru s="rui0110"]
[【累】]
「……ムニャムニャ……どこ～……お手洗い……どこぉ～……」[pcms][endhact]
[stopse_all]
[sysbt_meswin clear]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
[fadeoutbgm time=500]
[wait2 time=500]
[bgm storage="bgm09" time=100]
[backlay][bg storage="BG05c"]
[rui_lo_03_f01 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"]
[trans method=universal rule="wave" vague=300 time=500][wt2]
[sysbt_meswin]
*1548|
[fc]
[vo_ru s="rui0111"]
[【累】]
「……と、まあ、そんな感じだったようでね。僕は自宅の部屋では基本的に[r]
　全裸でいるものでね。寝る時もそのままなんだ」[pcms][endhact]
[backlay][rir_lo_03_f08 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*1549|
[fc]
[vo_ri s="riri0105"]
[【梨里】]
「…………はぁ？」[pcms][endhact]
*1550|
[fc]
無理矢理聞かせた梨里が、呆けた顔で累先輩のカミングアウトを聞いている。[r]
五十嵐さんと子野日さんも同じような顔になってしまっていた。[pcms]
[backlay][rui_lo_03_f01 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1551|
[fc]
[vo_ru s="rui0112"]
[【累】]
「合宿でも、布団に入ったら脱いでいたんだけど、[r]
　どうやら寝惚けてそのままお手洗いに向かってしまったみたいでね」[pcms][endhact]
*1552|
[fc]
悪びれた様子もなく朗らかに笑う累先輩の姿に、呆れを通り越して[r]
絶句してしまっている梨里と五十嵐さんと子野日さん。[pcms]
*1553|
[fc]
そりゃ、こんなしょうもない怪談の真相なんか聞いたら、[r]
そんな顔にもなるだろうさ。[pcms]
[backlay][rui_lo_03_f26 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1554|
[fc]
[vo_ru s="rui0113"]
[【累】]
「まあ、アレだね。傾国の美少女と言っても差し支えのない、[r]
　僕の裸体を目撃したのが高橋先生で良かったよ」[pcms][endhact]
[backlay][rui_lo_03_f02 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1555|
[fc]
[vo_ru s="rui0114"]
[【累】]
「男子だったら、あまりの美しさに目が潰れていたんじゃないかな」[pcms][endhact]
*1556|
[fc]
三人の反応に珍しく焦ったのか、[r]
照れ隠しなのか自己弁護なのかよくわからない言葉を口走る累先輩。[pcms]
[backlay][rir_lo_03_g01 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*1557|
[fc]
[vo_ri s="riri0106"]
[【梨里】]
「ねえ、央……前からチョイチョイ思ってたんだけど……この人って、[r]
　アホなの？」[pcms][endhact]
[backlay][rui_lo_03_f04 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1558|
[fc]
[vo_ru s="rui0115"]
[【累】]
「なーっ！　失敬な！　アホじゃない！　アホじゃないよ！！[r]
　渋江君、キミからも言ってくれたまえ！　僕はアホなんかじゃないって！」[pcms][endhact]
*1558a|
[fc]
梨里の言葉に抗議の声を上げてこちらを見てくる累先輩から、[r]
さりげなさを装いつつ視線を外す俺と須田。[pcms]
*1559|
[fc]
だって……なぁ。[pcms]
[backlay][rui_lo_03_g01 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1560|
[fc]
[vo_ru s="rui0116"]
[【累】]
「こらっ、キミがフォローしてくれないと僕が本格的に[r]
　残念な感じになっちゃうじゃないか！　須田君！　渋江君！！」[pcms][endhact]
*1561|
[fc]
……今日は早めに寝てしまった方が良さそうだ。[pcms]
[stopse_all]
[sysbt_meswin clear]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
[fadeoutbgm time=500]
[wait2 time=1000]
[jump storage="0170.ks"]
