*0190_TOP
[bgm storage="bgm08" time=100]
[backlay][bg storage="BG05a"][trans time=500 method=crossfade][wt2]
[sysbt_meswin]
*1683|
[fc]
And so, the second day of the training camp begins--[pcms]
[backlay][rui_lo_03_f01 layer=3 x="&sf.ru_lo_x[3]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1684|
[fc]
[vo_ru s="rui0122"]
[y—İz]
u‚¨‚Í‚æ‚¤A”ŒNB¡“ú‚àŒ³‹C‚É—ûK‚µ‚æ‚¤Iv[pcms][endhact]
*1685|
[fc]
Starting with early morning voluntary practice, breakfast, and the[r]
morning meeting--[pcms]
[backlay][chara_int][bg storage="BG11a"][trans method=universal rule="blindX" vague=50 time=1000][wt2]
*1686|
[fc]
Morning practice, lunch, and afternoon practice.[pcms]
*1687|
[fc]
It's nothing but practice all day long.[pcms]
*1688|
[fc]
With the addition of morning practice, the strain on the afternoon[r]
sessions feels heavier than expected.[pcms]
*1689|
[fc]
If you don't rest your body properly during the break after lunch,[r]
you'll tire out quickly.[pcms]
*1690|
[fc]
But... I have to do at least this much, otherwise it's all for naught.[r]
After all, I'm someone who originally doesn't last long trying to[r]
achieve something.[pcms]
[backlay][mis_lo_01_f01 layer=3 x="&sf.mi_lo_x[3]" y="&sf.mi_lo_y[0]"][trans time=150 method=crossfade][wt]
*1691|
[fc]
[vo_mo s="misuzu0039"]
[yq–ì“úz]
u‚¨”æ‚ê—l‚Å‚·Iv[pcms][endhact]
[backlay][sud_lo_01_f02 layer=2 x="&sf.su_lo_x[2]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*1692|
[fc]
[y{“cz]
u‚¨Ağ“ú‚æ‚èƒ^ƒCƒ€L‚Ñ‚Ä‚ñ‚¶‚á‚ñB’²q‚¢‚¢‚ñ‚¶‚á‚È‚¢‚©Hv[pcms][endhact]
[backlay][rui_lo_01_f01 layer=1 x="&sf.ru_lo_x[1]" y="&sf.ru_lo_y[0]"][trans time=150 method=crossfade][wt]
*1693|
[fc]
[vo_ru s="rui0123"]
[y—İz]
"Hehe... It seems like the disadvantage of starting conditions is[r]
steadily being overcome. I need to take a leaf out of your book."[pcms]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*1694|
[fc]
Although I feel fatigue throughout my body, there's also a sense of[r]
fulfillment like I've never felt before, both physically and mentally.[pcms]
*1695|
[fc]
[nsy]‘å‹v•Û[znse]
u‚à‚Á‚ÆƒtƒH[ƒ€‚ğˆÓ¯‚µ‚ÄccƒSƒzƒbAƒQƒzƒbAƒQƒzƒbccIv[pcms][endhact]
[backlay][tak_lo_03_f12a layer=3 x="&sf.ta_lo_x[3]" y="&sf.ta_lo_y[0]"][trans time=150 method=crossfade][wt]
*1696|
[fc]
[vo_mo s="takahasi0010"]
[y‚‹´z]
"It's important to work hard, but that's different from overdoing it.[r]
So make sure you push yourself within reasonable limits... Phew"[pcms]
[backlay][mis_lo_01_f10 layer=1 x="&sf.mi_lo_x[1]" y="&sf.mi_lo_y[0]"][trans time=150 method=crossfade][wt]
*1697|
[fc]
[vo_mo s="misuzu0040"]
[yq–ì“úz]
"Good work, teacher... Are you okay? If it's too tough, maybe you[r]
should rest in the infirmary..."[pcms]
[backlay][tak_lo_03_f10a layer=3 x="&sf.ta_lo_x[3]" y="&sf.ta_lo_y[0]"][trans time=150 method=crossfade][wt]
*1698|
[fc]
[vo_mo s="takahasi0011"]
[y‚‹´z]
"Thank you, Konohi-san. I'm sorry for being in such a state during[r]
such an important training camp... I'm such a failure as a teacher."[pcms]
*1699|
[fc]
It seems like both Takahashi-sensei and Okubo-coach are suffering from[r]
worsening summer colds.[pcms]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*1700|
[fc]
They're instructing us without getting in the water... but well, with[r]
Rui-senpai here, the order of the club will be maintained, so there[r]
seems to be no need to worry.[pcms]
[stopse_all]
[sysbt_meswin clear]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
[fadeoutbgm time=500]
[wait2 time=500]
[bgm storage="bgm01" time=100]
[backlay][bg storage="BG05b"]
[rui_up_03_f02 layer=3 x="&sf.ru_up_x[3]" y="&sf.ru_up_y[0]"]
[trans time=500 method=crossfade][wt2]
[sysbt_meswin]
*1701|
[fc]
[vo_ru s="rui0124"]
[y—İz]
"Yum, this is delicious! The shiso in the miso sauce for this pork[r]
belly stir-fry really brings out a great flavor. It refreshes the rich[r]
taste."[pcms]
[backlay][rir_up_03_f02 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*1702|
[fc]
[vo_ri s="riri0119"]
[y—œ—¢z]
"Tonight's meal was prepared by the second-year track and field[r]
members~! There's plenty for seconds, so please eat up~!"[pcms]
*1703|
[fc]
Wow, not bad at all, Riri.[pcms]
[backlay][rir_up_03_f01 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*1704|
[fc]
[vo_ri s="riri0120"]
[y—œ—¢z]
u‚Ç‚¤A‰›B”ü–¡‚µ‚¢Hv[pcms][endhact]
*1705|
[fc]
[y‰›z]
"Ah, I had no idea Riri was such a good cook. Ken'go would surely be[r]
happy too."[pcms]
[backlay][rir_up_03_f02 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*1706|
[fc]
[vo_ri s="riri0121"]
[y—œ—¢z]
"Ahaha, thanks. But this seasoning... I learned it from Mogami-senpai.[r]
It would've been impossible just by ourselves."[pcms]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*1707|
[fc]
Following yesterday's performance, today too is Mogami-senpai's fine[r]
play. I can't even sleep facing Mogami-senpai's room.[pcms]
*1708|
[fc]
[vo_mo s="mogami0001"]
[nsy]Åã[znse]
u‚Ó‚Ó‚ÁA‚Ç‚¤H@”ü–¡‚µ‚¢Hv[pcms][endhact]
*1709|
[fc]
[nsy]¼–ì[znse]
u‚Í‚¢I@‚Æ‚Á‚Ä‚à”ü–¡‚µ‚¢‚Å‚·Aæ”y‚ÁIv[pcms][endhact]
[backlay][mis_up_03_g05 layer=3 x="&sf.mi_up_x[3]" y="&sf.mi_up_y[0]"][trans time=150 method=crossfade][wt]
*1710|
[fc]
[vo_mo s="misuzu0041"]
[yq–ì“úz]
u‚¿‚ÁA‚¿‚Ácc‚¿‚¡‚¡‚ÁIv[pcms][endhact]
*1711|
[fc]
Ah, today's meal is delicious too.[pcms]
[stopse_all]
[sysbt_meswin clear]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
[wait2 time=500]
[backlay][bg storage="BG04c"][trans time=500 method=crossfade][wt2]
[sysbt_meswin]
*1712|
[fc]
[y‰›z]
u‚Í‚Ÿ‚Ÿcc‚¢‚¢‚¨“’‚¾‚Á‚½v[pcms][endhact]
*1713|
[fc]
After getting out of the bath, sleepiness is already creeping up on[r]
me.[pcms]
*1714|
[fc]
Still, it's nice to have time to talk in depth with people from[r]
different classes who I usually don't get a chance to speak with.[pcms]
*1715|
[fc]
I guess it wouldn't hurt to put up a bit of a fight against the[r]
sleepiness.[pcms]
[backlay][sud_lo_03_f02 layer=3 x="&sf.su_lo_x[3]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*1716|
[fc]
[y{“cz]
"Let's go! Tonight we set off for our dream city, Shangri-La! Brave[r]
warriors, follow me!"[pcms]
*1717|
[fc]
[y‰›z]
ucc‚¨‚â‚·‚İv[pcms][endhact]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*1718|
[fc]
Under Suda's command, warmed up to the brain by the bathwater,[r]
everyone rushes out into the already darkened hallway.[pcms]
[backlay][bg storage="BG04d"][trans time=500 method=crossfade][wt2]
*1719|
[fc]
I alone dive into my futon--[pcms]
*1719a|
[fc]
[vo_ru s="rui0119a"]
[yHHHz]
uE‚µ‚Äƒ}ƒ}IIv[pcms][endhact]
*1720|
[fc]
[y‰›z]
u‚¨ccv[pcms][endhact]
*1721|
[fc]
A voice saying "Kill me, Mama!!" can be heard from not too far away.[r]
Looks like the Lakeside Phantom made an appearance quite close by[r]
tonight.[pcms]
*1722|
[fc]
To escape from the foolish warriors' screams, I pull the futon over my[r]
head and close my eyes.[pcms]
*1723|
[fc]
Alright, let's do our best in practice tomorrow too.[pcms]
*1724|
[fc]
--The second day passed by just like that in the blink of an eye.[pcms]
[stopse_all]
[sysbt_meswin clear]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
[fadeoutbgm time=500]
[wait2 time=1000]
[jump storage="0191.ks"]
