*0225_TOP
[backlay][evcg storage="EV06_02" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[sysbt_meswin]
*1993|
[fc]
[vo_ri s="riri0622"]
[ns]Riri[nse]
"Uwaa...ah..."[pcms]
*1994|
[fc]
In Riri's line of sight were her friend, Igarashi Jun, and her[r]
boyfriend, Yuujia man. Both were literally strangers to me.[pcms]
*1995|
[fc]
I've exchanged greetings with Jun through Riri and even had a light[r]
conversation with her at dinner, but that's about it.[pcms]
*1996|
[fc]
However, Riri is Jun's best friend. Witnessing her best friend's sex[r]
must be shocking for her.[pcms]
[backlay][evcg storage="EV06_03" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*1997|
[fc]
[vo_ri s="riri0623"]
[ns]Riri[nse]
"Jun and... Yuuji-kun... to do such things..."[pcms]
*1998|
[fc]
Riri was secretly watching the two of them have sex. And here I was,[r]
in the complex situation of secretly watching Riri.[pcms]
*1999|
[fc]
Originally, I caught Riri about to start masturbating here, and I was[r]
trying to sneak a peek.[pcms]
*2000|
[fc]
Then Jun and Yuuji arrived, started their lovey-dovey act, and Riri[r]
had to stop her masturbation, becoming a mere spectator like me.[pcms]
[backlay][evcg storage="EV06_01" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*2001|
[fc]
[vo_ri s="riri0624"]
[ns]Riri[nse]
"It's amazing... to do that sort of thing... when you're lovers... I'm[r]
still... not ready..."[pcms]
*2002|
[fc]
My gaze, drawn by Riri, naturally shifted towards Jun and Yuuji. It[r]
was a strong shock for me as well.[pcms]
[stopse buf=1]
[backlay][evcg storage="EV07_02" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*2003|
[fc]
[vo_ju s="jun0235"]
[ns]Jun[nse]
"Fuaaaa... Yuuji-kun... that was amazing... my body is tingling... I'm[r]
embarrassed but I came again..."[pcms]
*2004|
[fc]
Jun murmured sadly while still in the position of sticking her butt[r]
out with her hands on the vaulting box. Yuuji, who had just brought[r]
her to climax with his mouth and tongue, was still excited.[pcms]
*2005|
[fc]
[ns]Yuuji[nse]
"Jun becomes so docile when we have sex, it's cute. It gets me so[r]
excited... I can't stand it. My dick is rock hard... I need to do[r]
something about it."[pcms]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
*2006|
[fc]
Saying that, Yuuji slid down his pants and underwear, exposing his[r]
erect penis.[pcms]
*2007|
[fc]
[vo_ju s="jun0236"]
[ns]Jun[nse]
"Yuuji-kun?"[pcms]
*2008|
[fc]
Perhaps feeling something off with the sound of clothing rustling, Jun[r]
tried to look back, but before she could, Yuuji pressed the tip of his[r]
penis against her wet private parts.[pcms]
[se buf=1 storage="se_sex02" loop=true]
[backlay][evcg storage="EV07_14" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*2009|
[fc]
[vo_ju s="jun0237"]
[ns]Jun[nse]
"Fuaah... hyahaaaan!?"[pcms]
*2010|
[fc]
Jun reacted with an erotic voice. The stimulation was apparently too[r]
much for her freshly climaxed slit.[pcms]
;*2011|
;[fc]
;[vo_ju s="jun0238"]
[ns]Jun[nse]
"It's hot... so hot! Yuuji-kun... without a condom... does it feel[r]
this different?"[pcms]
;*2012|
;[fc]
[ns]Yuuji[nse]
"Seriously... this is crazy. It feels so different without a condom."[pcms]
*2013|
[fc]
Both Jun and Yuuji seemed to be entranced and even moved by the warmth[r]
of each other's genitals, something they seemed to be experiencing for[r]
the first time. At least that's how it appeared to me.[pcms]
*2014|
[fc]
[ns]Yuuji[nse]
"Can we keep going like this?"[pcms]
[backlay][evcg storage="EV07_15" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*2015|
[fc]
[vo_ju s="jun0239"]
[ns]Jun[nse]
"Like last time... you just press your penis against me and move it[r]
around there, right?"[pcms]
*2016|
[fc]
In response to Yuuji's question, Jun replied with a question of her[r]
own. From their exchange, it was clear to me that they had already[r]
been maintaining a certain physical relationship.[pcms]
*2017|
[fc]
[ns]Yuuji[nse]
"No, it's not that... it's about time we have proper sex. That's what[r]
I think... so let's continue..."[pcms]
*2018|
[fc]
[vo_ju s="jun0240"]
[ns]Jun[nse]
"No way... if we don't use a condom, I could get pregnant... and it's[r]
my first time... it will probably hurt and I'll cry..."[pcms]
*2019|
[fc]
From Jun's perspective as a girl, her resistance was natural, but as a[r]
man secretly watching, I couldn't help but sympathize with Yuuji.[pcms]
*2020|
[fc]
[ns]Yuuji[nse]
"Sorry Jun... I can't hold back anymore... we're going to do it now."[pcms]
*2021|
[fc]
If I were in Yuuji's shoes, I'd probably say the same thing. It would[r]
be a joke to stop now after coming this far.[pcms]
[backlay][evcg storage="EV07_14" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*2022|
[fc]
[vo_ju s="jun0241"]
[ns]Jun[nse]
"No... ahn... don't Yuuji-kun... your penis rubbing against me there[r]
is bad... fuaaaahn!"[pcms]
*2023|
[fc]
It seemed that Yuuji had no intention of forcing himself on Jun[r]
without her consent, so he continued to stimulate her private parts[r]
using just the tip of his penis while remaining close to her.[pcms]
*2024|
[fc]
[vo_ju s="jun0242"]
[ns]Jun[nse]
"I just came a moment ago... it feels so intense... no way... no[r]
way... I'm going to come again... I feel like I'm about to come!"[pcms]
*2025|
[fc]
Yuuji restrained himself from penetration and desperately rubbed[r]
against her private parts, which for Jun meant being stimulated right[r]
after reaching climax on her sensitive body.[pcms]
*2026|
[fc]
[ns]Yuuji[nse]
"I want to come too! I want to take Jun's first time... make her a[r]
woman with me... and be the first man to ejaculate inside Jun's[r]
vagina!"[pcms]
*2027|
[fc]
The way Yuuji spoke struck a chord with me. It was because I had been[r]
holding back my feelings for Riri out of consideration for our[r]
friendship.[pcms]
[backlay][evcg storage="EV07_15" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*2028|
[fc]
[vo_ju s="jun0243"]
[ns]Jun[nse]
"Yuuji-kun... me too... I want it to be Yuuji-kun... only you...[r]
you're the only one I want to do such naughty things with... because I[r]
love you so much."[pcms]
*2029|
[fc]
In the face of the rising pleasure and Yuuji's passionate confession,[r]
Jun's reason was paralyzed. It wouldn't be long before she gave in to[r]
his desires in this flow of events.[pcms]
*2030|
[fc]
But surely, even in this situation, they wouldn't proceed to direct[r]
sex right awayor so I thought lightly.[pcms]
*2031|
[fc]
[vo_ju s="jun0244"]
[ns]Jun[nse]
"I'm sorry... I'm scared... but I want to be connected with Yuuji-[r]
kun... if I run away here, I feel like I'll always keep running[r]
away... so it's okay."[pcms]
*2032|
[fc]
[ns]Yuuji[nse]
"...Are you really sure?"[pcms]
*2033|
[fc]
[vo_ju s="jun0245"]
[ns]Jun[nse]
"Yes... Yuuji-kun... I want you to have my first time... Please,[r]
Yuuji-kun... don't think I'm a naughty girl, okay?"[pcms]
*2034|
[fc]
[ns]Yuuji[nse]
"Of course! Jun! I love you too! I love you!"[pcms]
*2035|
[fc]
While uttering fervent lines, Yuuji penetrates Jun's drenched secret[r]
place with his erect penis.[pcms]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[evcg白フラ storage="EV07_03" layer=0 page=back visible=true left=0 top=0]
*2036|
[fc]
[vo_ju s="jun0246"]
[ns]Jun[nse]
"Ah... ah... Yuuji-kun... it hurts... it hurts! Please... more[r]
slowly... please!"[pcms]
[se buf=1 storage="se_sex02" loop=true]
*2037|
[fc]
Jun pleads with a twisted face from the pain of defloration, but Yuuji[r]
seemed to have no room to consider that.[pcms]
*2038|
[fc]
[ns]Yuuji[nse]
"I'm sorry, Jun... this feels so good... it's my first time too... I[r]
can't stop because it feels too good!"[pcms]
*2039|
[fc]
[vo_ju s="jun0247"]
[ns]Jun[nse]
"Aaaaah... ah... aguuuu... Yuuji-kun!"[pcms]
*2040|
[fc]
Finally, most of Yuuji's penis was thrust inside Jun. The blood from[r]
her defloration ran down her thighs.[pcms]
*2041|
[fc]
[ns]Yuuji[nse]
"I'm sorry, Jun... but... inside you... it feels amazing."[pcms]
[backlay][evcg storage="EV07_05" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*2042|
[fc]
[vo_ju s="jun0248"]
[ns]Jun[nse]
"I'm glad... that Yuuji-kun feels good..."[pcms]
*2043|
[fc]
Enduring the pain and with tears mixed in her expression, Jun bravely[r]
smiles. I, empathizing with Yuuji, was deeply moved as well.[pcms]
*2044|
[fc]
[vo_ju s="jun0249"]
[ns]Jun[nse]
"Hey, you can move if you want? Men... feel better that way, right?"[pcms]
*2045|
[fc]
Jun says this while still enduring the pain. However, for some reason,[r]
Yuuji hardly moved after achieving penetration.[pcms]
*2046|
[fc]
[ns]Yuuji[nse]
"It's okay, just like this. If I move carelessly, it feels too good[r]
and I might... ejaculate too soon... I'll stay like this until Jun[r]
calms down..."[pcms]
*2047|
[fc]
It seemed more like Yuuji was enduring the urge to ejaculate due to[r]
the stimulation inside the vagina than being considerate of Jun.[pcms]
*2048|
[fc]
[vo_ju s="jun0250"]
[ns]Jun[nse]
"Yuuji-kun, you're so kind... I'm happy... I love you..."[pcms]
*2049|
[fc]
Jun misunderstands Yuuji's words as consideration for her just after[r]
losing her virginity and murmurs happily.[pcms]
[backlay][evcg storage="EV06_01" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*2050|
[fc]
[vo_ri s="riri0625"]
[ns]Riri[nse]
"Lucky you, Jun... I also want to be like that with someone I love[r]
soon."[pcms]
*2051|
[fc]
Riri's envious words pierced my ears. There's no doubt that the person[r]
she loves is her boyfriend Kenki.[pcms]
*2052|
[fc]
I'm flooded with regret for not confessing to Riri before Kenki and[r]
officially dating her.[pcms]
*2053|
[fc]
If only I had done so, I would have been united with Riri long ago and[r]
would have been indulging in erotic things just like Jun and Yuuji![pcms]
[backlay][evcg storage="EV06_03" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*2054|
[fc]
[vo_ri s="riri0626"]
[ns]Riri[nse]
"I'm happy for you... Jun..."[pcms]
*2055|
[fc]
I was on the verge of attacking Riri out of jealousy and lust.[pcms]
*2056|
[fc]
But then a change occurred between Jun and Yuuji, distracting me.[pcms]
[backlay][evcg storage="EV07_05" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*2057|
[fc]
[vo_ju s="jun0251"]
[ns]Jun[nse]
"Hauh... mmm... fuhah... I'm okay now..."[pcms]
*2058|
[fc]
Jun started moving her hips on her own, encouraging Yuuji.[pcms]
*2059|
[fc]
[ns]Yuuji[nse]
"Ah, ahh... I've gotten a bit used to the feeling inside Jun's vagina[r]
too... I'll move... ah... ugh..."[pcms]
*2060|
[fc]
Yuuji began to thrust his penis in and out. It was a cautious movement[r]
that gradually accelerated amidst unknown pleasures and moans.[pcms]
*2061|
[fc]
[vo_ju s="jun0252"]
[ns]Jun[nse]
"Uwahh... ah... the shape of your penis... I can feel it inside my[r]
stomach... I didn't know that..."[pcms]
*2062|
[fc]
The pain seemed to have subsided considerably, and there was a sweet,[r]
coquettish tone in Jun's voice.[pcms]
*2063|
[fc]
[vo_ju s="jun0253"]
[ns]Jun[nse]
"My place down there... is now shaped like Yuuji-kun's penis..."[pcms]
*2064|
[fc]
Jun said shyly, writhing her hips. It must have been a provocative[r]
statement for Yuuji as well.[pcms]
*2065|
[fc]
[ns]Yuuji[nse]
"That's right... Jun's pussy is shaped by my dick... It will always be[r]
like that from now on... forever... Jun!"[pcms]
[se buf=1 storage="se_sex03" loop=true]
*2066|
[fc]
In the heat of desire, Yuuji thrust his hips. Jun responded earnestly,[r]
dancing innocently and lewdly.[pcms]
[backlay][evcg storage="EV07_04" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*2067|
[fc]
[vo_ju s="jun0254"]
[ns]Jun[nse]
"Fuaahh... yahh... mmm... something feels strange..."[pcms]
*2068|
[fc]
Clearly, Jun was once again becoming disheveled by pleasure. The[r]
awkwardness from when she was enduring pain was gone.[pcms]
*2069|
[fc]
[ns]Yuuji[nse]
"Are you feeling it again?"[pcms]
*2070|
[fc]
[vo_ju s="jun0255"]
[ns]Jun[nse]
"It's embarrassing... even though it's my first time having a penis[r]
inside me... I read in a book that the first time is supposed to hurt[r]
only..."[pcms]
*2071|
[fc]
[ns]Yuuji[nse]
"If it feels good for me, then it's okay for Jun to feel good too![r]
Kuhh... I'm at my limit, Jun... I'm going to cum like I usually do on[r]
your butt!"[pcms]
*2072|
[fc]
Yuuji's thrusting movements accelerated even more.[pcms]
[backlay][evcg storage="EV07_05" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*2073|
[fc]
[vo_ju s="jun0256"]
[ns]Jun[nse]
"Yeah... cum on my butt... I want to feel good and ejaculate!"[pcms]
*2074|
[fc]
[ns]Yuuji[nse]
"Kuooo! I love you, Jun!"[pcms]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[射精フラA]
[backlay][evcg storage="EV07_07" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[射精フラB]
*2075|
[fc]
At that moment, Yuuji pulled his penis out from inside her and, as he[r]
had warned, showered Jun's butt with his semen.[pcms]
[backlay][evcg storage="EV07_08" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
*2076|
[fc]
[vo_ju s="jun0257"]
[ns]Jun[nse]
"Haaan... it feels... somehow the semen is hotter and stickier than[r]
usual... Yuuji-kun... did it feel good for you, my first time?"[pcms]
*2077|
[fc]
It seemed that Jun was showing a sexual response and gaining pleasure,[r]
but apparently, she had not yet reached climax.[pcms]
*2078|
[fc]
[ns]Yuuji[nse]
"It was the best... I'm seriously moved... I never knew making love to[r]
someone I like could feel this good."[pcms]
*2079|
[fc]
I'm so jealous of Yuuji! I want to have sex with a girl too, with Riri[r]
or even with Senpai Ashina![pcms]
*2080|
[fc]
[vo_ju s="jun0258"]
[ns]Jun[nse]
"You better not cheat on me with another girl... Yuuji-kun..."[pcms]
*2081|
[fc]
[ns]Yuuji[nse]
"Of course not. After putting Jun through such painful and tough[r]
times, I couldn't possibly do that. I'm all about Jun, so don't[r]
worry."[pcms]
*2082|
[fc]
[vo_ju s="jun0259"]
[ns]Jun[nse]
"Yeah... Yuuji-kun... I love you♪ My first time and from now on, I'm[r]
only for Yuuji-kun."[pcms]
*2083|
[fc]
Just watching their embarrassingly sweet conversation made Riri blush,[r]
and I felt oddly restless myself.[pcms]
*2084|
[fc]
[ns]Yuuji[nse]
"Kuuu... this is bad..."[pcms]
*2085|
[fc]
Despite having ejaculated and gone flaccid, his penis was becoming[r]
erect again in this short interval.[pcms]
*2086|
[fc]
[vo_ju s="jun0260"]
[ns]Jun[nse]
"What's wrong, Yuuji-kun?"[pcms]
*2087|
[fc]
[ns]Yuuji[nse]
"Hey Jun... can we do it one more time? You say such cute things that[r]
I got excited again... my dick's getting hard..."[pcms]
*2088|
[fc]
[vo_ju s="jun0261"]
[ns]Jun[nse]
"Geez... Yuuji-kun, you're so lewd..."[pcms]
*2089|
[fc]
[ns]Yuuji[nse]
"Is that... a no?"[pcms]
*2090|
[fc]
[vo_ju s="jun0262"]
[ns]Jun[nse]
"It's not like that... besides, I've calmed down... and started[r]
feeling good again... It's frustrating to leave it halfway... I want[r]
to do it."[pcms]
*2091|
[fc]
[ns]Yuuji[nse]
"This time... can I... cum inside for the first time... is it okay to[r]
ejaculate inside?"[pcms]
*2092|
[fc]
[vo_ju s="jun0263"]
[ns]Jun[nse]
"Yeah... because it's our first time tonight... it's special... so[r]
it's okay, you can cum inside."[pcms]
*2093|
[fc]
Blushing shyly, Jun answered, and Yuuji pressed his penis, still dirty[r]
with semen and love juices, against his lover's private parts once[r]
again.[pcms]
*2094|
[fc]
[ns]Yuuji[nse]
"Here I go, Jun!"[pcms]
[se buf=0 storage="se_sex01"]
[evcg白フラ storage="EV07_09" layer=0 page=back visible=true left=0 top=0]
[se buf=1 storage="se_sex02" loop=true]
*2095|
[fc]
And then, the second insertion after losing her virginity was[r]
performed. This time Jun was enjoying the pleasure without contorting[r]
her face in pain.[pcms]
*2096|
[fc]
[vo_ju s="jun0264"]
[ns]Jun[nse]
"Fwaaaahh... your penis is coming in!"[pcms]
*2097|
[fc]
Excited by the second insertion, Yuuji was thrusting his hips[r]
vigorously, a stark contrast to his initial caution.[pcms]
*2098|
[fc]
[ns]Yuuji[nse]
"Kuuuh... it's amazing again... Jun's vagina... the fine flesh is[r]
entangling my dick... and squeezing it!"[pcms]
[backlay][evcg storage="EV07_10" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
*2099|
[fc]
[vo_ju s="jun0265"]
[ns]Jun[nse]
"It's taking the shape of Yuuji-kun's again! Fuhhaaaaan!"[pcms]
*2100|
[fc]
Jun had cast aside the pain of losing her virginity and was responding[r]
to Yuuji with pleasure. She was actively moving to draw his penis[r]
deeper inside her.[pcms]
*2101|
[fc]
[ns]Yuuji[nse]
"Somehow it feels like the tip of my dick is going deeper than before,[r]
Jun... Does it feel better this way?"[pcms]
*2102|
[fc]
[vo_ju s="jun0266"]
[ns]Jun[nse]
"Fwaaaaaan... yes... deeper... right to the back of my stomach, Yuuji-[r]
kun's penis is... when you hit here, I feel so much!"[pcms]
*2103|
[fc]
[ns]Yuuji[nse]
"I'll thrust! I'll thrust as much as needed and this time I'll make[r]
you cum, Jun!"[pcms]
[se buf=1 storage="se_sex03" loop=true]
*2104|
[fc]
Once Yuuji confirmed the sensitive spots where Jun reacted, he began[r]
to thrust his penis back and forth dramatically, powerfully attacking[r]
those areas.[pcms]
[backlay][evcg storage="EV07_11" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
*2105|
[fc]
[vo_ju s="jun0267"]
[ns]Jun[nse]
"No wayyy... if you do that... I'm going to cum... I'm about to cum[r]
already!"[pcms]
*2106|
[fc]
[ns]Yuuji[nse]
"Let's cum together... you're going to cum, Jun! Thrust by my dick!"[pcms]
*2107|
[fc]
Yuuji thrust his hips while closely attached to her, intensively[r]
hitting that part deep inside her vagina over and over.[pcms]
*2108|
[fc]
[vo_ju s="jun0268"]
[ns]Jun[nse]
"Hiaaaaahh... yaaaahhhn... Yuuji-kun I'm gonna cummm... cummingggg...[r]
I'm cummingggg!"[pcms]
[stopse buf=1]
[メスフラ]
*2109|
[fc]
The moment Jun shook her body greatly and climaxed. But Yuuji did not[r]
ejaculate; he gritted his teeth and endured the pleasure.[pcms]
*2110|
[fc]
[ns]Yuuji[nse]
"When Jun cums... the vagina gets incredibly tight... if I wasn't[r]
careful I would have cum too... it feels so good..."[pcms]
[backlay][evcg storage="EV07_10" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
*2111|
[fc]
[vo_ju s="jun0269"]
[ns]Jun[nse]
"Huaaahh... you said it was okay to cum inside... we were supposed to[r]
feel good together... you're mean, Yuuji-kun... that's cruel..."[pcms]
*2112|
[fc]
[ns]Yuuji[nse]
"Sorry, Jun. Next time we'll do that. But when you were being thrust[r]
at and cumming in such a lewd way, Jun... you were so erotic and[r]
cute... I fell for you all over again."[pcms]
*2113|
[fc]
[vo_ju s="jun0270"]
[ns]Jun[nse]
"Idiot! Yuuji-kun, you're such a pervert! I don't care anymore!"[pcms]
*2114|
[fc]
Blushing furiously at Yuuji's words, Jun felt embarrassed. Yuuji,[r]
seemingly satisfied with his lover's expression, grinned.[pcms]
*2115|
[fc]
[ns]Yuuji[nse]
"Then... next time, together... okay?"[pcms]
[backlay][evcg storage="EV07_09" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
*2116|
[fc]
[vo_ju s="jun0271"]
[ns]Jun[nse]
"Yeah... next time... properly... okay?"[pcms]
[se buf=1 storage="se_sex03" loop=true]
*2117|
[fc]
After a brief rest for Jun's recovery, Yuuji once again thrust his[r]
penis into her wet vagina.[pcms]
[backlay][evcg storage="EV07_10" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
*2118|
[fc]
[vo_ju s="jun0272"]
[ns]Jun[nse]
"Fwaaaah! Your penis is so hot! It's like I'm getting burned!"[pcms]
*2119|
[fc]
Jun writhed as their hips slammed together intensely. Her voice and[r]
body were completely immersed in the pleasure of sex.[pcms]
*2120|
[fc]
[ns]Yuuji[nse]
"What are you saying! Jun's pussy is hot too! It feels like it's[r]
melting my dick... ghh... it's so tight!"[pcms]
*2121|
[fc]
Perhaps to avoid ejaculating too soon, Yuuji kept moving his penis,[r]
repeatedly thrusting with intense movements.[pcms]
[backlay][evcg storage="EV07_11" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
*2122|
[fc]
[vo_ju s="jun0273"]
[ns]Jun[nse]
"Yahaaah... if you do it that strongly... I'm going to... I'm going to[r]
cum again... because I just came earlier... it feels so intense!"[pcms]
*2123|
[fc]
[ns]Yuuji[nse]
"Me too... I'm feeling it too... melting inside Jun... I'm about to[r]
ejaculate and become the first man to cum inside Jun's vagina!"[pcms]
*2124|
[fc]
[vo_ju s="jun0274"]
[ns]Jun[nse]
"It's not just the first time... from now on... forever... until[r]
death... it's only going to be Yuuji-kun!"[pcms]
*2125|
[fc]
[ns]Yuuji[nse]
"Uooo! Jun! What are you saying! I love you!"[pcms]
[backlay][evcg storage="EV07_10" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
*2126|
[fc]
[vo_ju s="jun0275"]
[ns]Jun[nse]
"Hyaah? Your penis, it's getting even bigger inside me!"[pcms]
*2127|
[fc]
[ns]Yuuji[nse]
"Jun! I'm at my limit... I'm going to... ejaculate inside your[r]
vagina!"[pcms]
*2128|
[fc]
With a dramatic movement as if it were the last, Yuuji deeply gouged[r]
into Jun's vaginal depths.[pcms]
*2129|
[fc]
[vo_ju s="jun0276"]
[ns]Jun[nse]
"I, I'm also... with Yuuji-kun... together... Fuaaah... Fwaaah... I'm[r]
cumming, being ejaculated into by Yuuji-kun's penis!"[pcms]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[射精フラA]
[backlay][evcg storage="EV_12" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[射精フラB]
*2130|
[fc]
From the trembling of their bodies, it seemed that their long-awaited[r]
ejaculation and climax occurred at almost the same time.[pcms]
*2131|
[fc]
[ns]Yuuji[nse]
"Uooo? It won't stop... still... being squeezed by the pussy... and,[r]
coming outttt?"[pcms]
*2132|
[fc]
[vo_ju s="jun0277"]
[ns]Jun[nse]
"Fuaa... ah... hyaa... it's hot... my belly is filled with Yuuji-kun's[r]
semen... it's sloshing around..."[pcms]
*2133|
[fc]
[ns]Yuuji[nse]
"Haa... haa... ah... Jun... you're okay, right?"[pcms]
*2134|
[fc]
[vo_ju s="jun0278"]
[ns]Jun[nse]
"Yeah... I thought I was going to faint but... Yuuji-kun's penis was[r]
so hot and I could feel that... so I was fine?"[pcms]
*2135|
[fc]
[ns]Yuuji[nse]
"It felt good... we were able to cum together properly, Jun."[pcms]
[se buf=0 storage="se_sex01"]
[backlay][evcg storage="EV_13" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*2136|
[fc]
Gently pulling his penis out of Jun's vagina, Yuuji spoke.[pcms]
*2137|
[fc]
[vo_ju s="jun0279"]
[ns]Jun[nse]
"Fwaaah... ah... yaaahn..."[pcms]
*2138|
[fc]
Even that action alone seemed to bring pleasure to the sensitive Jun,[r]
sounding erotic.[pcms]
*2139|
[fc]
[vo_ju s="jun0280"]
[ns]Jun[nse]
"I've never felt this good before... and to think it was with Yuuji-[r]
kun... I'm so happy..."[pcms]
*2140|
[fc]
Jun replied with a dreamy voice. Her expression was one of contented[r]
happiness.[pcms]
*2141|
[fc]
[ns]Yuuji[nse]
"Hey Jun... if it's okay with you, after resting a little bit more...[r]
I want to do it again... is that alright?"[pcms]
*2142|
[fc]
No, surely by now, the girl must be physically exhausted; she would[r]
likely gently refuse.[pcms]
*2143|
[fc]
At least, that's what I thought. But that seemed to be a naive thought[r]
unique to an inexperienced virgin.[pcms]
*2144|
[fc]
[vo_ju s="jun0281"]
[ns]Jun[nse]
"Yeah... I also want to become happier with Yuuji-kun♪)[pcms]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
*2145|
[fc]
In the end, Jun and Yuuji continued their intense sex and generously[r]
achieved simultaneous climaxes.[pcms]
*2146|
[fc]
[ns]Yuuji[nse]
"Can you walk, Jun? I'll lend you my shoulder."[pcms]
*2147|
[fc]
[vo_ju s="jun0282"]
[ns]Jun[nse]
"Ehehehe♪ Thank you, Yuuji-kun[pcms]
*2148|
[fc]
After getting dressed and finishing the cleanup, the lovey-dovey[r]
foolish couple left the gymnasium with the air of newlyweds,[r]
affectionately close to each other.[pcms]
[if exp="tf.scene_mode == 1 && tf.all_play == 0"]
	[jump storage="b_scene.ks" target=*back_from_SR]
[endif]
[jump storage="0225_2.ks"]
