*SRP07
[eval exp="sf.SRP07 = 1"]
[if exp="tf.scene_mode"]
	
	[bgm storage="bgm14" time=100 cond="tf.all_play == 0"]
	[jump target=*scene_start]
[endif]
[sysbt_meswin clear]
[backlay][black_toplayer][trans time=500 method=crossfade][wt2][hide_chara_int]
*scene_start
[backlay][evcg storage="EV15_01" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
[wait2 time=500]
[sysbt_meswin]
*4421|
[fc]
[ns]佐竹[nse]
"Kiyohara... How could a distinguished female student of our school[r]
accept another school's male's penis inside her vagina? What does this[r]
mean?"[pcms]
*4422|
[fc]
Senior Satake lay on his back and had Riri straddle him in a cowgirl[r]
position on top of him.[pcms]
*4423|
[fc]
After being violated repeatedly, Riri was too exhausted to resist or[r]
escape, and could only obediently comply.[pcms]
*4424|
[fc]
[vo_ri s="riri0190"]
[ns]Riri[nse]
"It was against my will! I didn't want it and tried to escape, but[r]
there were so many people... I couldn't do anything!"[pcms]
*4425|
[fc]
[ns]佐竹[nse]
"What a pathetic excuse, Kiyohara! I saw it... I've been watching[r]
since just before you had sex with that guy from another school named[r]
Yuuji!"[pcms]
*4426|
[fc]
While shouting, Senior Satake rubbed his huge penis--his massive[r]
member--from the valley of Riri's buttocks to her secret place.[pcms]
[se buf=1 storage="se_sex02" loop=true]
[backlay][evcg storage="EV15_02" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4427|
[fc]
[vo_ri s="riri0191"]
[ns]Riri[nse]
"Fhyawaa? Wh-what's this big thing? Can a penis really get this big?"[pcms]
*4428|
[fc]
The sensation of being rubbed made Riri exclaim in surprise. The shock[r]
was something I, Suda, and Yuuji, who had become spectators, could all[r]
relate to.[pcms]
*4429|
[fc]
[ns]佐竹[nse]
"As a third-year... I cannot overlook the moral and ethical[r]
degradation of a female student like Kiyohara! Therefore, I will take[r]
the place of the teachers in charge of student discipline and[r]
administer punishment!"[pcms]
*4430|
[fc]
I had already heard similar rhetoric from the vice-captain, Kato-[r]
senpai. In hindsight, it felt like Kato-senpai was imitating Satake-[r]
senpai's way of speaking.[pcms]
*4431|
[fc]
[vo_ri s="riri0192"]
[ns]Riri[nse]
"Please stop! I don't want any more penises!"[pcms]
*4432|
[fc]
[ns]佐竹[nse]
"Excuses are futile! This is the hammer of justice, Kiyohara!"[pcms]
[se buf=0 storage="se_sex01"]
[evcg白フラ storage="EV15_03" layer=0 page=back visible=true left=0 top=0]
[se buf=1 storage="se_sex02" loop=true]
*4433|
[fc]
Senior Satake effortlessly lifted Riri's body with both hands,[r]
skillfully aligned his penis's glans with her slit, and then completed[r]
the insertion.[pcms]
*4434|
[fc]
[vo_ri s="riri0193"]
[ns]Riri[nse]
"Higufu... Uguahh... It's too big... How can it fit..."[pcms]
*4435|
[fc]
However, Riri's feminine functions betrayed her words, and over time,[r]
they steadily accommodated Senior Satake's massive member inside her[r]
vagina.[pcms]
*4436|
[fc]
[ns]佐竹[nse]
"Oooh? So this is what the inside of a woman's pussy feels like...[r]
Kiyohara... I'm grateful! With this, I graduate from being a virgin![r]
I've become a splendid upperclassman who won't shame my juniors!"[pcms]
[backlay][evcg storage="EV15_04" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4437|
[fc]
[vo_ri s="riri0194"]
[ns]Riri[nse]
"Fuhah! Kihii! Uaaaah!"[pcms]
*4438|
[fc]
But Riri, gasping for breath and in agony, had no leeway to respond or[r]
throw back any sarcasm.[pcms]
*4439|
[fc]
[ns]佐竹[nse]
"Uoooh? What's this? It feels like my fingers are being devoured by a[r]
sea anemone... Kuhaaah! I have no choice but to ejaculate!"[pcms]
[backlay][evcg storage="EV15_05" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4440|
[fc]
[vo_ri s="riri0195"]
[ns]Riri[nse]
"Higihiiii! Stop it! I'm going to break!"[pcms]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[射精フラA]
[backlay][evcg storage="EV15_06" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[射精フラB]
*4441|
[fc]
In the end, Senior Satake ejaculated inside Riri while his huge penis[r]
was still inserted. When it was pulled out from the gap in her[r]
underwear, semen overflowed like a waterfall.[pcms]
[backlay][evcg storage="EV15_07" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4442|
[fc]
[ns]佐竹[nse]
"Phew... So this is a woman... I've devoted myself to abstinence and[r]
diligence in both literary and martial arts, but it seems that such[r]
things are no more useful than cheap candy."[pcms]
*4443|
[fc]
As Senior Satake reflected deeply, I had already forgotten to give[r]
instructions to the followers from the beginning and was completely[r]
engrossed as a bystander.[pcms]
*4444|
[fc]
[ns]小野寺[nse]
"Satake! How dare you, a mere student, ejaculate inside Kiyohara[r]
without my permission as a teacher! Take my place!"[pcms]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
*4445|
[fc]
The track and field advisor teacher, Mr. Onodera, who had been hiding[r]
somewhere until now, pounced on Riri.[pcms]
[backlay][evcg storage="EV15a_08" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4446|
[fc]
[vo_ri s="riri0196"]
[ns]Riri[nse]
"Mr. Onodera... please stop... help me..."[pcms]
*4447|
[fc]
Riri no longer bothered to mention trivial things like her opponent's[r]
eyes being red; she just weakly begged for help.[pcms]
*4448|
[fc]
But Mr. Onodera mercilessly tore off the track uniform Riri was[r]
wearing. It was clear that he was one of us; his eyes were red too.[pcms]
*4449|
[fc]
[ns]小野寺[nse]
"What is this T-back? I've been meaning to warn you about this! Why[r]
hide it when the line of your underwear is clearly visible?"[pcms]
*4450|
[fc]
[vo_ri s="riri0197"]
[ns]Riri[nse]
"Because it's embarrassing if it shows... obviously..."[pcms]
*4451|
[fc]
Mr. Onodera himself mentioned the answer to his question within the[r]
question. Clearly, his behavior was off-kilter just like ours.[pcms]
*4452|
[fc]
[ns]小野寺[nse]
"This is outrageous, Kiyohara! Hiding the beauty of a woman from the[r]
eyes of men! I will not acknowledge such selfish reasoning! As[r]
punishment, you will be disciplined!"[pcms]
*4453|
[fc]
Mr. Onodera shifted the semen-soaked T-back aside with great force and[r]
then suddenly--[pcms]
[se buf=0 storage="se_sex01"]
[evcg白フラ storage="EV15a_09" layer=0 page=back visible=true left=0 top=0]
*4454|
[fc]
[vo_ri s="riri0198"]
[ns]Riri[nse]
"Mughahaaa? Aguhiiiiii!"[pcms]
[se buf=1 storage="se_sex02" loop=true]
*4455|
[fc]
Despite the muddiness from Senior Satake's recent copious ejaculation,[r]
Mr. Onodera inserted his penis deep into Riri's vagina without any[r]
preparation.[pcms]
*4456|
[fc]
Upon closer inspection, his penis was as massive as Senior Satake's.[r]
As a man, it was a size that inspired a bit of envy or admiration.[pcms]
[backlay][evcg storage="EV15a_09" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4457|
[fc]
[vo_ri s="riri0199"]
[ns]Riri[nse]
"Stop it Mr. Onodera! I can't take this anymore!"[pcms]
*4458|
[fc]
[ns]小野寺[nse]
"I won't allow such selfishness! Fulfill your duty before asserting[r]
yourself! Any misconduct that disrupts the order of the group will not[r]
be tolerated! As collective responsibility, all the girls will be[r]
violated!"[pcms]
*4459|
[fc]
[vo_ri s="riri0200"]
[ns]Riri[nse]
"No, stop it! I can't bear the thought of all the girls suffering[r]
because of me!"[pcms]
*4460|
[fc]
[ns]佐竹[nse]
"Hey Kiyohara! Since you're at it... suck my dick! Your mouth is[r]
free... give me that 'cleanup fellatio' thing!"[pcms]
*4461|
[fc]
As Riri, shaken, tries to turn her face away in rejection, Senior[r]
Satake thrusts his revived massive penis into her mouth. However, Mr.[r]
Onodera does not allow her to refuse.[pcms]
*4462|
[fc]
[ns]小野寺[nse]
"Kiyohara, this is educational guidance from the club advisor! Give[r]
Satake a cleanup blowjob! This is an official order. If you resist,[r]
I'll ejaculate inside every female club member!"[pcms]
[backlay][evcg storage="EV15a_10" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4463|
[fc]
[vo_ri s="riri0201"]
[ns]Riri[nse]
"I understand... I'll give you a cleanup blowjob... so please stop[r]
this... ugh... Kengi... I... really shouldn't be doing this..."[pcms]
*4464|
[fc]
After making excuses to Kengi, Riri brings her face close to Senior[r]
Satake's penis and awkwardly starts to lick the surface with the tip[r]
of her tongue.[pcms]
[backlay][evcg storage="EV15a_11" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4465|
[fc]
[vo_ri s="riri0202"]
[ns]Riri[nse]
「はぷ……ふ……ん……う……く、くさいよ……おちんちん……」[pcms][endhact]
*4466|
[fc]
While suffering from the sensation of Mr. Onodera's massive penis[r]
thrusting inside her vagina, Riri desperately licks and cleans Senior[r]
Satake's protruding penis.[pcms]
*4467|
[fc]
[ns]佐竹[nse]
「失礼だぞ清原！　これは青春の汗が宿したかぐわしい芳香だッ！」[pcms][endhact]
*4468|
[fc]
Enraged, Senior Satake thrusts his penis not just into Riri's mouth[r]
but deep into her throat.[pcms]
[backlay][evcg storage="EV15a_12" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4469|
[fc]
[vo_ri s="riri0203"]
[ns]Riri[nse]
「むがもぎんぐひんんんんんッ？」[pcms][endhact]
*4470|
[fc]
Riri struggles, almost writhing in agony as her breathing becomes[r]
restricted.[pcms]
*4471|
[fc]
[ns]小野寺[nse]
"Hahahaha! Have you tightened up, Kiyohara? Did giving Satake a[r]
cleanup blowjob awaken you to the spirit of service and the joy of[r]
being a woman?"[pcms]
*4472|
[fc]
The cheerful Mr. Onodera rapidly accelerates his thrusting hips. What[r]
was supposed to be a cleanup blowjob has now turned into deep-[r]
throating, and Senior Satake is doing the same.[pcms]
*4473|
[fc]
[ns]小野寺[nse]
「教え子に膣内射精するうううッ！」[pcms][endhact]
*4474|
[fc]
[ns]佐竹[nse]
「後輩女子にお掃除フェラさせて、二発目発射ァああああッ！」[pcms][endhact]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[射精フラA]
[backlay][evcg storage="EV15a_13" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[射精フラB]
*4475|
[fc]
[vo_ri s="riri0204"]
[ns]Riri[nse]
「んがんっぐひっ……むぐはああああああッ！」[pcms][endhact]
*4476|
[fc]
Having been ejaculated inside her vagina and then in her mouth, Riri[r]
reaches the peak of discomfort and disgust, continuing to suffer as[r]
she vomits what seems to be remnants of her dinner.[pcms]
[backlay][evcg storage="EV15a_14" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4477|
[fc]
[vo_ri s="riri0205"]
[ns]Riri[nse]
「んぐああ……うあ……あ……」[pcms][endhact]
*4478|
[fc]
[ns]小野寺[nse]
「がははははは！　清原はゲロを吐いたか！」[pcms][endhact]
*4479|
[fc]
[ns]佐竹[nse]
"I can't stand it! After I generously gave you protein for beauty and[r]
health... and you vomit it out... Unforgivable!"[pcms]
[backlay][evcg storage="EV15a_15" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4480|
[fc]
[vo_ri s="riri0206"]
[ns]Riri[nse]
「も、もう……許して……くだ……さい……」[pcms][endhact]
*4481|
[fc]
[ns]佐竹[nse]
「根性を注入してやるッ！　今一度、この俺のビッグマグナムでな！」[pcms][endhact]
*4482|
[fc]
Despite having just ejaculated inside her vagina and then in her[r]
mouth, Senior Satake's penis was still erect and majestic.[pcms]
*4483|
[fc]
[ns]佐竹[nse]
「小野寺先生、交代よろしいですね？」[pcms][endhact]
*4484|
[fc]
[ns]小野寺[nse]
「いいだろう。俺も見届けてやる」[pcms][endhact]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
*4485|
[fc]
Having been satisfied with the ejaculation inside her vagina, Mr.[r]
Onodera moved away from Riri's body and joined Suda and Yuuji,[r]
becoming a spectator near me.[pcms]
*4486|
[fc]
[ns]佐竹[nse]
「そりゃあああ根性注入だ清原ァあああああッ！」[pcms][endhact]
[se buf=0 storage="se_sex01"]
[evcg白フラ storage="EV15_17" layer=0 page=back visible=true left=0 top=0]
*4487|
[fc]
[vo_ri s="riri0207"]
[ns]Riri[nse]
「ひぎあああああッ！」[pcms][endhact]
[se buf=1 storage="se_sex02" loop=true]
*4488|
[fc]
Then Senior Satake lies on his back again, making Riri straddle him in[r]
a cowgirl position, and inserts his massive penis into her vagina.[pcms]
*4489|
[fc]
This time, the insertion was even more violent and wild than before.[r]
It reminded me of the mating of tigers or bears I've seen on TV.[pcms]
[backlay][evcg storage="EV15_18" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4490|
[fc]
[vo_ri s="riri0208"]
[ns]Riri[nse]
「ひぐはあああッ！　顕悟！　たすけてえ！　央っ！」[pcms][endhact]
*4491|
[fc]
Riri is calling my name. And she's provoking me. The way she's shaking[r]
her butt, she must be inviting me.[pcms]
[backlay][evcg storage="EV15_19" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4492|
[fc]
[ns]Akira[nse]
「今、助けるぞ梨里ッ！」[pcms][endhact]
*4493|
[fc]
I rush over with my head and groin boiling with lust.[pcms]
*4494|
[fc]
[vo_ri s="riri0209"]
[ns]Riri[nse]
「央……たすけて……たすけてえ……お願い……」[pcms][endhact]
*4495|
[fc]
[ns]佐竹[nse]
「邪魔する気か渋江？」[pcms][endhact]
*4496|
[fc]
[ns]Akira[nse]
"I was called by Riri, so I'm just going to do anal sex as she[r]
requested. Riri, I'll take your anal virginity too, since I'm your[r]
boyfriend, right?"[pcms]
*4497|
[fc]
After saying that, I change my position to the opposite side of Senior[r]
Satake and press the tip of my penis against her anal opening.[pcms]
*4498|
[fc]
[vo_ri s="riri0210"]
[ns]Riri[nse]
"Akira... please... stop... I used to love you... even after Kengi[r]
confessed... I was still unsure..."[pcms]
*4499|
[fc]
[ns]Akira[nse]
"Don't joke around, Riri. Haven't we always been in love with each[r]
other, as boyfriend and girlfriend? Isn't that right, Senior Satake?"[pcms]
*4500|
[fc]
[ns]佐竹[nse]
"Hmm. As a senior, I'm just helping Shibue discipline Kiyohara. Thank[r]
you, Senior Satake!"[pcms]
*4501|
[fc]
[ns]Akira[nse]
??? "Do it, Shibue! Splendidly scatter the anal virginity of Kiyohara[r]
as her lover!"[pcms]
*4502|
[fc]
[ns]佐竹[nse]
"Yes! Here I go, Riri! It's the start of our journey into anal sex!"[pcms]
*4503|
[fc]
[ns]Akira[nse]
Fortunately, the slickness from the semen that everyone had released[r]
in abundance helped, and I forcefully pushed the tip of my penis into[r]
her anus.[pcms]
*4504|
[fc]
"Nngahh... my ass... my ass is being penetrated by Akira's penis[r]
again!"[pcms]
[se buf=0 storage="se_sex01"]
[evcg白フラ storage="EV15_20" layer=0 page=back visible=true left=0 top=0]
*4505|
[fc]
[vo_ri s="riri0211"]
[ns]Riri[nse]
As my penis fully entered, it seemed to tear at the entrance, and like[r]
when I took her virginity, fresh blood ran down Riri's thighs.[pcms]
*4506|
[fc]
"I did it, Riri! My penis has entered your anal hole!"[pcms]
*4507|
[fc]
[ns]Akira[nse]
The area clenched tightly around the base of the invading penis while[r]
simultaneously conveying pleasure with a warm embrace deep inside.[pcms]
*4508|
[fc]
But immediately after, I remembered that I had already taken her anal[r]
virginity the night before.[pcms]
*4509|
[fc]
"Sorry, Riri. That's right, I already took your anal virginity last[r]
night. I got so excited I completely forgot."[pcms]
*4510|
[fc]
[ns]Akira[nse]
"Shibue... you've used me, your senior, quite skillfully. You cheeky[r]
brat."[pcms]
*4511|
[fc]
[ns]佐竹[nse]
"Hehehe, sorry about that. I seriously forgot."[pcms]
*4512|
[fc]
[ns]Akira[nse]
"Fine. I'll enjoy myself in Kiyohara's vagina to relieve my[r]
frustration!"[pcms]
*4513|
[fc]
[ns]佐竹[nse]
"Kihh... nkuahhh... it hurts... my ass feels like it's tearing!"[pcms]
[se buf=1 storage="se_sex03" loop=true]
[backlay][evcg storage="EV15_21" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4514|
[fc]
[vo_ri s="riri0212"]
[ns]Riri[nse]
Even though it felt so good for me, Riri was crying her eyes out. But[r]
this is also part of her punishment, so it can't be helped.[pcms]
*4515|
[fc]
"Kiyohara... to think you're getting double penetrated at your age,[r]
aren't you a precocious girl? But since we're at it, why don't you[r]
give me a cleanup blowjob and make it a triple penetration debut♪"[pcms]
*4516|
[fc]
[ns]小野寺[nse]
Professor Onodera was now able to make Riri obey without having to[r]
threaten her with raping all the female members and ejaculating inside[r]
them.[pcms]
*4517|
[fc]
"Nguh... muhyua... nguah... ogufu... ngh!"[pcms]
[backlay][evcg storage="EV15_22" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4518|
[fc]
[vo_ri s="riri0213"]
[ns]Riri[nse]
While giving Professor Onodera a cleanup blowjob, Senior Satake[r]
stirred up her vagina with his huge cock, and my penis ravaged her[r]
rectum, continuing the triple assault.[pcms]
*4519|
[fc]
"Being bitten by the canine teeth hurts, but this is also good in its[r]
own way!"[pcms]
[backlay][evcg storage="EV15_23" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4520|
[fc]
[ns]小野寺[nse]
"Kiyohara's pussy... is the best!"[pcms]
*4521|
[fc]
[ns]佐竹[nse]
"Riri... your anal hole feels so good... I can't help but ejaculate!"[pcms]
*4522|
[fc]
[ns]Akira[nse]
At my words, both Professor Onodera and Senior Satake reached the[r]
limits of their excitement and lust and ejaculated as well.[pcms]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[射精フラA]
[backlay][evcg storage="EV15_24" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
[射精フラB]
*4523|
[fc]
I ejaculated inside her rectum, Senior Satake inside her vagina, and[r]
Professor Onodera in her mouth. Riri accepted it all.[pcms]
*4524|
[fc]
"Mugagufugihh... nmgugagaahhh!"[pcms]
[backlay][evcg storage="EV15_25" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4525|
[fc]
[vo_ri s="riri0214"]
[ns]Riri[nse]
But when we each pulled our penises out of Riri's body, she expelled[r]
semen from all three holes and then vomited again.[pcms]
*4526|
[fc]
Each time she gagged and struggled, semen dripped from her secret slit[r]
and anus, which was indecent.[pcms]
[backlay][evcg storage="EV15_26" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[se buf=0 storage="seD017"]
*4527|
[fc]
"You look like you're having a tough time, Riri? But the punishment[r]
isn't over yet."[pcms]
*4528|
[fc]
[ns]Akira[nse]
As I emphasized this point, another new participant declared their[r]
intention to join.[pcms]
*4529|
[fc]
"May I take care of Kiyohara-kun's physical and mental care?"[pcms]
*4530|
[fc]
[ns]大久保[nse]
It was Coach Okubo from our swimming team, a handsome man. His eyes[r]
were also red.[pcms]
*4531|
[fc]
"Even Coach Okubo has... gone mad?"[pcms]
*4532|
[fc]
[vo_ri s="riri0215"]
[ns]Riri[nse]
I didn't reply, but Coach Okubo took that as consent and approached[r]
Riri.[pcms]
*4533|
[fc]
I didn't reply, but Coach Okubo took that as consent and approached[r]
Riri.[pcms]
[if exp="tf.scene_mode == 1 && tf.all_play == 0"]
	[jump storage="b_scene.ks" target=*back_from_SR]
[endif]
[jump storage="0392_3.ks"]
