*SRP07
[eval exp="sf.SRP07 = 1"]
[if exp="tf.scene_mode"]
	
	[bgm storage="bgm14" time=100 cond="tf.all_play == 0"]
	[jump target=*scene_start]
[endif]
[sysbt_meswin clear]
[backlay][black_toplayer][trans time=500 method=crossfade][wt2][hide_chara_int]
*scene_start
[backlay][evcg storage="EV15_01" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
[wait2 time=500]
[sysbt_meswin]
*4421|
[fc]
[ns【]佐竹[】nse]
"Kiyohara... What does it mean for a distinguished female student of[r]
our school to accept another school's male's penis inside her vagina?"[pcms]
*4422|
[fc]
Satake-senpai lay on his back and had Riri straddle him in a cowgirl[r]
position.[pcms]
*4423|
[fc]
Having been thoroughly violated, Riri was too exhausted to resist or[r]
escape, and could only passively comply.[pcms]
*4424|
[fc]
[vo_ri s="riri0190"]
[【梨里】]
"It was against my will! I didn't want it and tried to escape, but[r]
there were too many people... I couldn't do anything!"[pcms]
*4425|
[fc]
[ns【]佐竹[】nse]
"What a pathetic excuse, Kiyohara! I saw it... I've been watching[r]
since just before you had sex with that guy Yuuji from another[r]
school!"[pcms]
*4426|
[fc]
While shouting, Satake-senpai rubbed his huge penis--his massive[r]
member--from the valley of Riri's buttocks to her secret place.[pcms]
[se buf=1 storage="se_sex02" loop=true]
[backlay][evcg storage="EV15_02" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4427|
[fc]
[vo_ri s="riri0191"]
[【梨里】]
"Fufyaaah? What, what is this big thing? Can a penis really get this[r]
big?"[pcms]
*4428|
[fc]
Riri exclaimed in surprise at the sensation of it being rubbed against[r]
her, a surprise that I, Suda, and Yuuji, who had become spectators,[r]
could all share.[pcms]
*4429|
[fc]
[ns【]佐竹[】nse]
"As a third-year... I cannot overlook the moral and ethical disorder[r]
of a female student like Kiyohara! Therefore, I will take the place of[r]
the teachers in charge of student discipline and administer[r]
punishment!"[pcms]
*4430|
[fc]
I had already heard similar rhetoric from the vice-captain, Katou-[r]
senpai. In hindsight, it felt like Katou-senpai was imitating Satake-[r]
senpai's manner of speaking.[pcms]
*4431|
[fc]
[vo_ri s="riri0192"]
[【梨里】]
「やめてください！　もうあたし、おちんちんは嫌ッ！」[pcms][endhact]
*4432|
[fc]
[ns【]佐竹[】nse]
「言い訳は無用ッ！　これは正義の鉄槌だ清原ッ！」[pcms][endhact]
[se buf=0 storage="se_sex01"]
[evcg白フラ storage="EV15_03" layer=0 page=back visible=true left=0 top=0]
[se buf=1 storage="se_sex02" loop=true]
*4433|
[fc]
Satake-senpai effortlessly lifted Riri's body with both hands,[r]
skillfully aligned his penis's glans with her slit, and then completed[r]
the insertion.[pcms]
*4434|
[fc]
[vo_ri s="riri0193"]
[【梨里】]
「ひぐふッ……うぐああッ……お、大きすぎるッ……こんな入るわけ……」[pcms][endhact]
*4435|
[fc]
However, Riri's function as a woman betrayed her words, and over time[r]
she steadily accommodated Satake-senpai's massive member inside her[r]
vagina.[pcms]
*4436|
[fc]
[ns【]佐竹[】nse]
"Oooh? So this is the inside of a woman's pussy... Kiyohara... I'm[r]
grateful! Now I've graduated from being a virgin! I've become a[r]
splendid upperclassman who won't shame my juniors!"[pcms]
[backlay][evcg storage="EV15_04" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4437|
[fc]
[vo_ri s="riri0194"]
[【梨里】]
「ふはーっ！　きひいいっ！　うああああっ！」[pcms][endhact]
*4438|
[fc]
But Riri, gasping for breath and in pain, had no room to reply or[r]
throw back any sarcasm.[pcms]
*4439|
[fc]
[ns【]佐竹[】nse]
"Uooooh? What's this? It feels like my fingers are being swallowed by[r]
an anemone... Kuhahaa! There's nothing to do but ejaculate!"[pcms]
[backlay][evcg storage="EV15_05" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4440|
[fc]
[vo_ri s="riri0195"]
[【梨里】]
「ひぎひいいいいッ！　やめてえッ！　あたし壊れちゃううううッ！」[pcms][endhact]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[射精フラA]
[backlay][evcg storage="EV15_06" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[射精フラB]
*4441|
[fc]
In the end, Satake-senpai ejaculated inside Riri while his huge penis[r]
was still inserted. When it was pulled out from the gap in her[r]
underwear, semen overflowed like a waterfall.[pcms]
[backlay][evcg storage="EV15_07" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4442|
[fc]
[ns【]佐竹[】nse]
"Phew... So this is a woman... I've devoted myself to abstinence and[r]
diligence in both literary and martial arts, but it seems that was[r]
nothing more than a trifle as insignificant as cheap candy."[pcms]
*4443|
[fc]
While listening to Satake-senpai's deep reflections, I had completely[r]
forgotten to give instructions to the guys who had followed me from[r]
the start and was fully engrossed as a bystander.[pcms]
*4444|
[fc]
[ns【]小野寺[】nse]
"Satake! How dare you, a mere student, ejaculate inside Kiyohara[r]
without my permission as a teacher! Take my place!"[pcms]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
*4445|
[fc]
Out of nowhere, Teacher Onodera, who also advises the track team,[r]
attacked Riri.[pcms]
[backlay][evcg storage="EV15a_08" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4446|
[fc]
[vo_ri s="riri0196"]
[【梨里】]
「お、小野寺……せんせえ……もうやめてえ……たすけて……」[pcms][endhact]
*4447|
[fc]
Riri no longer bothered to mention trivial things like her opponent's[r]
eyes being red. She just weakly sought salvation.[pcms]
*4448|
[fc]
But Teacher Onodera mercilessly tore off the track wear Riri was[r]
wearing. It was clear that he was one of us; his eyes were red too.[pcms]
*4449|
[fc]
[ns【]小野寺[】nse]
"What's with this T-back? I've been meaning to warn you about this![r]
Why hide it when the underwear line shows through like this?"[pcms]
*4450|
[fc]
[vo_ri s="riri0197"]
[【梨里】]
「そんなの見えたら……恥ずかしいからに……決まって……ます……」[pcms][endhact]
*4451|
[fc]
Teacher Onodera himself mentioned the answer to his question within[r]
the question. Clearly, his behavior was off-kilter just like ours.[pcms]
*4452|
[fc]
[ns【]小野寺[】nse]
"This is unacceptable, Kiyohara! To hide the beauty of a woman from[r]
the eyes of men! I won't acknowledge such selfish reasoning! As[r]
punishment, you will be disciplined!"[pcms]
*4453|
[fc]
Teacher Onodera shifted the semen-covered T-back aside and then[r]
suddenly[pcms]
[se buf=0 storage="se_sex01"]
[evcg白フラ storage="EV15a_09" layer=0 page=back visible=true left=0 top=0]
*4454|
[fc]
[vo_ri s="riri0198"]
[【梨里】]
「むぐはあああッ？　あぐひいいいいいッ！」[pcms][endhact]
[se buf=1 storage="se_sex02" loop=true]
*4455|
[fc]
Despite the slickness from Satake-senpai's recent copious ejaculation,[r]
Teacher Onodera inserted his penis deep into Riri's vagina without any[r]
preparation.[pcms]
*4456|
[fc]
Upon closer inspection, it was as massive as Satake-senpai's member.[r]
As a man, it was a size that inspired a bit of envy or admiration.[pcms]
[backlay][evcg storage="EV15a_09" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4457|
[fc]
[vo_ri s="riri0199"]
[【梨里】]
「やめて小野寺せんせえッ！　もうあたし、こんなの耐えらんない！」[pcms][endhact]
*4458|
[fc]
[ns【]小野寺[】nse]
"I won't allow such selfishness! Fulfill your duties before asserting[r]
yourself! Any misconduct that disrupts the order of the group will not[r]
be tolerated! As collective responsibility, all female students will[r]
be violated!"[pcms]
*4459|
[fc]
[vo_ri s="riri0200"]
[【梨里】]
"No, stop it! It's not fair for all the girls to suffer because of[r]
me... Noooo!"[pcms]
*4460|
[fc]
[ns【]佐竹[】nse]
"Hey Kiyohara! Since we're at it... suck my dick! Your mouth is[r]
free... give me that 'cleanup fellatio' thing!"[pcms]
*4461|
[fc]
Riri tried to turn her face away in rejection as Satake-senpai thrust[r]
his revived member towards her mouth. However, Teacher Onodera did not[r]
allow her to refuse.[pcms]
*4462|
[fc]
[ns【]小野寺[】nse]
"Kiyohara, as an advisor to the club, this is educational guidance![r]
Give Satake a cleanup fellatio! This is official. If you resist, all[r]
female club members will receive vaginal ejaculations!"[pcms]
[backlay][evcg storage="EV15a_10" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4463|
[fc]
[vo_ri s="riri0201"]
[【梨里】]
"I understand... I'll give you a cleanup fellatio... so please stop[r]
that... ugh... Kengi... I really don't want this..."[pcms]
*4464|
[fc]
After making excuses to Kengi, Riri brought her face close to Satake-[r]
senpai's penis and awkwardly ran her tongue over its surface.[pcms]
[backlay][evcg storage="EV15a_11" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4465|
[fc]
[vo_ri s="riri0202"]
[【梨里】]
「はぷ……ふ……ん……う……く、くさいよ……おちんちん……」[pcms][endhact]
*4466|
[fc]
While suffering from the sensation of being thrust into by Teacher[r]
Onodera's massive member, Riri desperately licked Satake-senpai's[r]
protruding penis clean.[pcms]
*4467|
[fc]
[ns【]佐竹[】nse]
「失礼だぞ清原！　これは青春の汗が宿したかぐわしい芳香だッ！」[pcms][endhact]
*4468|
[fc]
Satake-senpai furiously thrust his penis not just into Riri's mouth[r]
but deep into her throat.[pcms]
[backlay][evcg storage="EV15a_12" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4469|
[fc]
[vo_ri s="riri0203"]
[【梨里】]
「むがもぎんぐひんんんんんッ？」[pcms][endhact]
*4470|
[fc]
Riri struggled as if she were going to convulse from the inability to[r]
breathe properly.[pcms]
*4471|
[fc]
[ns【]小野寺[】nse]
"Gahaha! Has it gotten tighter, Kiyohara? By giving Satake a cleanup[r]
fellatio have you awakened to the spirit of service and the joy of[r]
being a woman?"[pcms]
*4472|
[fc]
Teacher Onodera, in high spirits, rapidly accelerated his thrusting[r]
movements. It was no longer just cleanup fellatio; Satake-senpai's[r]
actions had turned into irrumatio as well.[pcms]
*4473|
[fc]
[ns【]小野寺[】nse]
「教え子に膣内射精するうううッ！」[pcms][endhact]
*4474|
[fc]
[ns【]佐竹[】nse]
「後輩女子にお掃除フェラさせて、二発目発射ァああああッ！」[pcms][endhact]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[射精フラA]
[backlay][evcg storage="EV15a_13" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[射精フラB]
*4475|
[fc]
[vo_ri s="riri0204"]
[【梨里】]
「んがんっぐひっ……むぐはああああああッ！」[pcms][endhact]
*4476|
[fc]
Riri, having been ejaculated inside and then in her mouth, seemed to[r]
have reached the peak of her discomfort and disgust, vomiting what[r]
looked like remnants of her dinner and continuing to writhe in agony.[pcms]
[backlay][evcg storage="EV15a_14" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4477|
[fc]
[vo_ri s="riri0205"]
[【梨里】]
「んぐああ……うあ……あ……」[pcms][endhact]
*4478|
[fc]
[ns【]小野寺[】nse]
「がははははは！　清原はゲロを吐いたか！」[pcms][endhact]
*4479|
[fc]
[ns【]佐竹[】nse]
"I can't stand it! After I generously gave you protein for beauty and[r]
health... and you vomit it out... unforgivable!"[pcms]
[backlay][evcg storage="EV15a_15" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4480|
[fc]
[vo_ri s="riri0206"]
[【梨里】]
「も、もう……許して……くだ……さい……」[pcms][endhact]
*4481|
[fc]
[ns【]佐竹[】nse]
「根性を注入してやるッ！　今一度、この俺のビッグマグナムでな！」[pcms][endhact]
*4482|
[fc]
Despite the recent vaginal ejaculation and the one before that in her[r]
mouth, Satake-senpai's member was still proudly erect.[pcms]
*4483|
[fc]
[ns【]佐竹[】nse]
「小野寺先生、交代よろしいですね？」[pcms][endhact]
*4484|
[fc]
[ns【]小野寺[】nse]
「いいだろう。俺も見届けてやる」[pcms][endhact]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
*4485|
[fc]
Having satisfied himself with the vaginal ejaculation, Teacher Onodera[r]
moved away from Riri's body, joining Suda and Yuuji as a spectator[r]
near me.[pcms]
*4486|
[fc]
[ns【]佐竹[】nse]
「そりゃあああ根性注入だ清原ァあああああッ！」[pcms][endhact]
[se buf=0 storage="se_sex01"]
[evcg白フラ storage="EV15_17" layer=0 page=back visible=true left=0 top=0]
*4487|
[fc]
[vo_ri s="riri0207"]
[【梨里】]
「ひぎあああああッ！」[pcms][endhact]
[se buf=1 storage="se_sex02" loop=true]
*4488|
[fc]
Once again, Satake-senpai lay on his back and had Riri straddle him in[r]
a cowgirl position, inserting his huge cock into her vagina.[pcms]
*4489|
[fc]
This time, the insertion was even more violent and wild than before.[r]
It reminded me of the mating of tigers or bears I had seen on TV.[pcms]
[backlay][evcg storage="EV15_18" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4490|
[fc]
[vo_ri s="riri0208"]
[【梨里】]
「ひぐはあああッ！　顕悟！　たすけてえ！　央っ！」[pcms][endhact]
*4491|
[fc]
Riri is calling my name. And she's provoking me. Shaking her ass like[r]
that must be an invitation.[pcms]
[backlay][evcg storage="EV15_19" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4492|
[fc]
[【央】]
「今、助けるぞ梨里ッ！」[pcms][endhact]
*4493|
[fc]
I rushed over, conscious of my head boiling with lust and my groin[r]
swelling with desire.[pcms]
*4494|
[fc]
[vo_ri s="riri0209"]
[【梨里】]
「央……たすけて……たすけてえ……お願い……」[pcms][endhact]
*4495|
[fc]
[ns【]佐竹[】nse]
「邪魔する気か渋江？」[pcms][endhact]
*4496|
[fc]
[【央】]
"I'm just responding to Riri's call, giving her anal sex as requested.[r]
Riri, I'll take your anal virginity as your boyfriend, okay?"[pcms]
*4497|
[fc]
After saying that, I moved to the opposite side of Satake-senpai and[r]
pressed the tip of my penis against her anal opening.[pcms]
*4498|
[fc]
[vo_ri s="riri0210"]
[【梨里】]
"Kengi... please... stop... I used to love you... even after you[r]
confessed... I was still unsure..."[pcms]
*4499|
[fc]
[【央】]
"Don't joke around, Riri. We've always been in love, boyfriend and[r]
girlfriend, right? Isn't that right, Satake-senpai?"[pcms]
*4500|
[fc]
[ns【]佐竹[】nse]
"Hmm. As a senior, I'm just helping Shibu-e give Kiyohara some[r]
discipline. This is a manifestation of friendship wishing for the[r]
healthy growth of a junior!"[pcms]
*4501|
[fc]
[【央】]
「ありがとうございます佐竹先輩ッ！」[pcms][endhact]
*4502|
[fc]
[ns【]佐竹[】nse]
「やれ渋江ッ！　清原の尻穴処女を恋人として見事に散らしてやれッ！」[pcms][endhact]
*4503|
[fc]
[【央】]
「はいッ！　いくぞ梨里ッ！　俺たちのアナルセックスへの旅立ちだッ！」[pcms][endhact]
*4504|
[fc]
Luckily, the slickness from everyone's semen helped as I forcefully[r]
and aggressively pushed the head of my penis into her anal opening.[pcms]
[se buf=0 storage="se_sex01"]
[evcg白フラ storage="EV15_20" layer=0 page=back visible=true left=0 top=0]
*4505|
[fc]
[vo_ri s="riri0211"]
[【梨里】]
「んぐあああっ……お尻っ……お尻に、また央のおちんちんがあッ！」[pcms][endhact]
*4506|
[fc]
As my penis fully entered, it seemed to tear at the entrance like when[r]
taking a virginity, and fresh blood ran down Riri's thighs.[pcms]
*4507|
[fc]
[【央】]
「やったぞ梨里！　俺のが梨里のお尻の穴の中に入ったぞッ？」[pcms][endhact]
*4508|
[fc]
The place where my penis invaded clenched around its base with[r]
incredible force while deeper inside it enveloped me with a soft[r]
warmth that transmitted pleasure.[pcms]
*4509|
[fc]
But immediately after, I remembered that I had already taken her anal[r]
virginity the night before.[pcms]
*4510|
[fc]
[【央】]
"Sorry, Riri. I just remembered that I already took your anal[r]
virginity last night. Got so excited I completely forgot."[pcms]
*4511|
[fc]
[ns【]佐竹[】nse]
「渋江め……先輩の俺を上手く利用したな。生意気なやつ」[pcms][endhact]
*4512|
[fc]
[【央】]
「へへへっ、すいません。マジでド忘れしてたんスよ」[pcms][endhact]
*4513|
[fc]
[ns【]佐竹[】nse]
「いいだろう。その分は清原の膣内で楽しんで、鬱憤を晴らすからなッ！」[pcms][endhact]
[se buf=1 storage="se_sex03" loop=true]
[backlay][evcg storage="EV15_21" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4514|
[fc]
[vo_ri s="riri0212"]
[【梨里】]
「きひっ……んくあああっ……痛いっ……お尻裂けちゃうようッ！」[pcms][endhact]
*4515|
[fc]
I felt so good yet Riri was crying her eyes out. But this was also[r]
part of her punishment, so it couldn't be helped.[pcms]
*4516|
[fc]
[ns【]小野寺[】nse]
"Kiyohara... at your young age, a double penetration? What a[r]
precocious girl. But since we're at it, why not give me a cleanup[r]
fellatio and make it a triple penetration debut♪"[pcms]
*4517|
[fc]
Teacher Onodera no longer needed to threaten to rape all the female[r]
club members or ejaculate inside them to make Riri obey.[pcms]
[backlay][evcg storage="EV15_22" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4518|
[fc]
[vo_ri s="riri0213"]
[【梨里】]
「んぐ……むひゅあ……んぐあ……おぐふっ……ん！」[pcms][endhact]
*4519|
[fc]
While giving Teacher Onodera a cleanup fellatio and having Satake-[r]
senpai stir inside her vagina with his huge cock, I ravaged her rectum[r]
with my penis in a triple assault.[pcms]
[backlay][evcg storage="EV15_23" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4520|
[fc]
[ns【]小野寺[】nse]
「犬歯で噛まれると痛いが、これはこれでいいッ！」[pcms][endhact]
*4521|
[fc]
[ns【]佐竹[】nse]
「清原のマンコ……最高だッ！」[pcms][endhact]
*4522|
[fc]
[【央】]
「梨里ッ……お尻の穴が気持ち良くて……俺もう射精するしかないッ！」[pcms][endhact]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[射精フラA]
[backlay][evcg storage="EV15_24" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
[射精フラB]
*4523|
[fc]
At my words, both Teacher Onodera and Satake-senpai reached the limits[r]
of their excitement and lust, ejaculating then and there.[pcms]
*4524|
[fc]
I ejaculated inside her rectum, Satake-senpai in her vagina, and[r]
Teacher Onodera in her mouth. Riri accepted it all.[pcms]
[backlay][evcg storage="EV15_25" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4525|
[fc]
[vo_ri s="riri0214"]
[【梨里】]
「むぐあぐふぎひっ……んむぎぐがあああああッ！」[pcms][endhact]
*4526|
[fc]
But when we each pulled our penises out of Riri's body, she expelled[r]
semen from all three holes and then vomited again.[pcms]
[backlay][evcg storage="EV15_26" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[se buf=0 storage="seD017"]
*4527|
[fc]
Each time she retched in agony, semen dripped from her secret slit and[r]
anus, which was indecent.[pcms]
*4528|
[fc]
[【央】]
「しんどそうだな梨里？　けど、まだお仕置きは終わってないからな」[pcms][endhact]
*4529|
[fc]
As I emphasized my point, another new participant stepped forward to[r]
join.[pcms]
*4530|
[fc]
[ns【]大久保[】nse]
「清原君のフィジカルとメンタルのケア、私に任せてくれないか？」[pcms][endhact]
*4531|
[fc]
It was Coach Okubo from our swimming club, also known for his good[r]
looks. His eyes were red too.[pcms]
*4532|
[fc]
[vo_ri s="riri0215"]
[【梨里】]
「大久保コーチまで……おかしく……なって……るの？」[pcms][endhact]
*4533|
[fc]
I didn't respond specifically, but Coach Okubo took that as consent[r]
and approached Riri.[pcms]
[if exp="tf.scene_mode == 1 && tf.all_play == 0"]
	[jump storage="b_scene.ks" target=*back_from_SR]
[endif]
[jump storage="0392_3.ks"]
