*0392_TOP
*SRP06
[eval exp="sf.SRP06 = 1"]
[if exp="tf.scene_mode"]
	
	[jump target=*scene_start]
[endif]
[bgm storage="bgm07" time=100]
[backlay][bg storage="BG03b"][trans time=500 method=crossfade][wt2]
[sysbt_meswin]
*4164|
[fc]
[【央】]
「ふううっ……なんか俺……酔っ払ってんのかな……」[pcms][endhact]
*4165|
[fc]
累先輩、子野日さん、そして最上さん、黒沢さん、岩瀬さんと、[r]
セックス三昧で疲れた……とか？[pcms]
*4166|
[fc]
[【央】]
「確かにさっき少し休んだけど……でもそんなに疲れてないし」[pcms][endhact]
*4167|
[fc]
疲労で身体が重いというわけでもない。[r]
むしろ性欲も体力も有り余っている感じだ。[pcms]
*4168|
[fc]
自分自身でも驚きなのは、女の子たちを相手に射精しまくりなのに、[r]
俺の精力も精液も天井知らずなことだ。[pcms]
*4169|
[fc]
[【央】]
「エロマンガとかじゃあるまいし……なんか今日の俺って無敵？」[pcms][endhact]
*4170|
[fc]
とある超有名なゲームの主役のイタリアの配管工が星を取って、[r]
無敵モードになったみたいに活力がみなぎっている。[pcms]
*4171|
[fc]
[【央】]
「セックスすればするほど調子いいな……けど、どうせならやっぱり[r]
　梨里と……好きな女の子とセックスしたい」[pcms][endhact]
*4172|
[fc]
そうだった。[r]
俺は梨里を探していたんだった。[pcms]
*4173|
[fc]
[【央】]
「お～い、梨里～？」[pcms][endhact]
*4174|
[fc]
大声で呼んでみるが返事はなかった。[r]
さっきの最上さんたちみたいに、どこかに隠れてるのか？[pcms]
*4175|
[fc]
[【央】]
「心配すんなって！　俺が来たからにはもう安心だから！」[pcms][endhact]
*4176|
[fc]
そんな風に独り言とも呼びかけともつかない言葉を口走りながら俺は[r]
施設内を走り回るが、梨里はどこにも見つからない。[pcms]
*4177|
[fc]
[【央】]
「いったいどこに……」[pcms][endhact]
*4178|
[fc]
床に転がっている見知らぬ誰かの死体を蹴飛ばしていらつく心を鎮めて[r]
いると、ふと窓の外の風景が目に入る。[pcms]
*4179|
[fc]
[【央】]
「あッ？」[pcms][endhact]
*4180|
[fc]
ここは施設の三階だから、それなりには見晴らしがいい。[r]
だから、そこにいる誰かの姿もはっきりと確認できた。[pcms]
[stopbgm]
[backlay][bg storage="BG12b"]
[evcg storage="EV03_01" layer=1 page=back visible=true left=0 top=0]
[trans time=200 method=crossfade][wt2]
[bgm storage="bgm05" time=100]
*4181|
[fc]
[vo_ri s="riri0131"]
[【梨里】]
「このッ！　せやあああッ！」[pcms][endhact]
[se buf=0 storage="seB040"]
[wait2 time=250]
[se buf=0 storage="seB012"]
*4182|
[fc]
その回し蹴りを喰らった男が吹き飛ぶ。[pcms]
*4183|
[fc]
[vo_ri s="riri0132"]
[【梨里】]
「はあああああッ！」[pcms][endhact]
[se buf=0 storage="seB039"]
[wait2 time=250]
[se buf=0 storage="seB008"]
*4184|
[fc]
[【央】]
「お～……すっげぇ、さすがタイガーリリー」[pcms][endhact]
[se buf=0 storage="seB039"]
[wait2 time=250]
[se buf=0 storage="seB012"]
*4185|
[fc]
次は中段の突き。[r]
これでまた別の男が腹を押さえて倒れ込む。[pcms]
[backlay][chara_int][bg storage="BG12b"][trans time=500 method=crossfade][wt2]
*4186|
[fc]
グラウンドには梨里がいた。[r]
そしてあいつを取り囲む男たちの影もある。[pcms]
*4187|
[fc]
鍛えた空手技で襲いかかる連中を撃退する梨里だったが、[r]
どういうわけか男たちはゾンビめいた動きで立ち上がってくる。[pcms]
*4188|
[fc]
梨里は本気で技を使っている。打撃を受けた相手は昏倒して当然[r]
だし、下手をすれば死んでいるダメージのはずだ。[pcms]
[backlay][rir_lo_01_f15 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*4189|
[fc]
[vo_ri s="riri0133"]
[【梨里】]
「キリが無い……ゾンビか何かみたい……どうなってるの？」[pcms][endhact]
*4190|
[fc]
だが男たちは不死身の超人のように、何度打ち倒されても立ち上がって[r]
梨里に襲いかかってくる。[pcms]
[backlay][rir_lo_01_f04 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*4191|
[fc]
[vo_ri s="riri0134"]
[【梨里】]
「もう付き合ってらんないよッ！」[pcms][endhact]
[backlay][chara_int][trans time=150 method=crossfade][wt]
[se buf=0 storage="seA049"]
*4192|
[fc]
思い切り良く、梨里は男たちに背中を見せて、施設を取り囲む深い森に[r]
走り出していった。[pcms]
[stopse buf=0]
[backlay][bg storage="BG03b"][trans time=500 method=crossfade][wt2]
*4193|
[fc]
[【央】]
「待ってろ梨里ッ！　俺が助けに行くからなッ！」[pcms][endhact]
*4194|
[fc]
考えるよりも先に身体が勝手に動いていた。[r]
俺は窓からそのまま身を踊らせて飛び降りていた。[pcms]
[backlay][bg storage="BG12b"]
[trans method=universal rule="TtoD" vague=100 time=200][wt2]
[赤フラ]
[se buf=0 storage="seB012"]
*4195|
[fc]
[quakesp time=500 laynum=0 hmax=0 vmax=20]
[【央】]
「つあああッ……くッ……痛い……ちょっと無理し過ぎた」[pcms][endhact]
*4196|
[fc]
俺は植え込みのところに着地というか、ぶざまに転がっていた。[r]
こんなはずじゃなかった。[pcms]
*4197|
[fc]
とあるリアル格闘マンガの最高峰を参考に、五点接地転回法を使い、[r]
無傷で降りるつもりだった。[pcms]
*4198|
[fc]
[【央】]
「あれ？　なんか痛いと思ったけど気のせいだったか？」[pcms][endhact]
*4199|
[fc]
ほんの少しだけ目がくらくらして視界が揺れているような気も[r]
するけど、それだけだった。[pcms]
*4200|
[fc]
足下がふらふらしているけど、それだけだ。[r]
何も問題無い。[pcms]
*4201|
[fc]
[【央】]
「さすが無敵モードの俺ッ！　なんともないぜッ！」[pcms][endhact]
*4202|
[fc]
さて……さっきの連中も散らばって森に突入していったようだし、[r]
俺も梨里を追いかけよう。急がないと連中に先を越される。[pcms]
[sysbt_meswin clear]
[fadeoutbgm time=500]
[se buf=0 storage="seA050"]
[backlay][black_toplayer]
[trans method=universal rule="LtoR" vague=100 time=500][wt2][hide_chara_int]
[wait2 time=500]
[backlay][bg storage="BG14b"]
[rir_lo_01_f15 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
[bgm storage="bgm12" time=100]
[sysbt_meswin]
*4203|
[fc]
[vo_ri s="riri0135"]
[【梨里】]
「はあっ……はあ……ほんと、いい加減にしてよッ！」[pcms][endhact]
[eval exp="sf.EV41_03 = 1"][backlay][image storage="EV41_03" layer=3 page=back visible=true left=0 top=0][trans time=200 method=crossfade][wt2]
[se buf=0 storage="seB039"]
[wait2 time=250]
[se buf=0 storage="seB008"]
*4204|
[fc]
[vo_ri s="riri0136"]
[【梨里】]
「何人倒しても……何度も急所狙っても……終わらない……。[r]
　キリがない……なんなの……これ？」[pcms][endhact]
[se buf=0 storage="seB040"]
[wait2 time=250]
[se buf=0 storage="seB012"]
[backlay][chara_int][rir_lo_01_f25 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*4205|
[fc]
[vo_ri s="riri0137"]
[【梨里】]
「まずい……もう息が上がってる……ダメ……かも……助けて……[r]
　顕悟……央……」[pcms][endhact]
[backlay][chara_int1][trans time=150 method=crossfade][wt]
[stopbgm]
[se buf=0 storage="seA049"]
[bgm storage="bgm05" time=100]
*4206|
[fc]
[【央】]
「梨里っ！　俺だっ！！　央だッ！　無事かッ？」[pcms][endhact]
*4207|
[fc]
俺が駆け付けたその時、梨里はふらふらになっていて、[r]
今にも倒れ込みそうな状態だった。[pcms]
*4208|
[fc]
辺りにはさっき梨里を取り囲んで襲いかかっていた連中がいて、[r]
まだ倒れていたり、起き上がろうとしていた。[pcms]
[backlay][rir_lo_01_f01 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*4209|
[fc]
[vo_ri s="riri0138"]
[【梨里】]
「央……来てくれたんだ」[pcms][endhact]
*4210|
[fc]
[【央】]
「ああ、梨里をこんな連中の好き勝手にさせるわけにはいかないからな。[r]
　間に合って良かったよ」[pcms][endhact]
*4211|
[fc]
たぶん、俺はドヤ顔ってやつになっているに違いない。[r]
お姫様の危機に駆け付けた白馬の王子様として梨里の目に映ったはず。[pcms]
[backlay][rir_lo_01_f16 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*4212|
[fc]
[vo_ri s="riri0139"]
[【梨里】]
「ちょ、ちょっと央？　アンタ……自分がどうなってるか……わかって[r]
　ないの？」[pcms][endhact]
*4213|
[fc]
切羽詰まった声で梨里がこちらを非難してくる。[r]
俺はドヤ顔のはずだってのに、どうかしたのか？[pcms]
*4214|
[fc]
[【央】]
「なんじゃ。寝癖とか目やにとか、そういうのでも付いてたか？」[pcms][endhact]
[backlay][rir_lo_01_f15 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*4215|
[fc]
[vo_ri s="riri0140"]
[【梨里】]
「アンタ……顔も身体も血だらけで……頭にガラスの破片まで……、[r]
　刺さってるけど……なんともないの？」[pcms][endhact]
*4216|
[fc]
[【央】]
「ありゃ？　そういやなんかヌルっとした感じがあったけど血が出てた[r]
　とはな。ガラスはこれか。抜いておくよ。教えてくれてどうもな」[pcms][endhact]
[backlay][rir_lo_01_f10 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*4217|
[fc]
[vo_ri s="riri0141"]
[【梨里】]
「い、痛くないの？　そんな大ケガしてるのに？」[pcms][endhact]
*4218|
[fc]
[【央】]
「なんともないって。今夜の俺は無敵モードなんだ。そんなことより、[r]
　梨里に大事な話がある。聞いてくれ」[pcms][endhact]
[backlay][rir_lo_01_f04 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*4219|
[fc]
[vo_ri s="riri0142"]
[【梨里】]
「後にして！　それより今はここから逃げ出すか警察に連絡する方法を[r]
　なんとかしないと――」[pcms][endhact]
*4220|
[fc]
[【央】]
「そんなことより大事なことだ。梨里、セックスしようじゃあないか。[r]
　夕べの仕切り直しだ……今度はもっと徹底的にやろう！」[pcms][endhact]
[backlay][rir_lo_01_f16 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*4221|
[fc]
率直に要点だけ伝えると梨里はまた驚き顔でこちらを見つめてくる。[pcms]
*4222|
[fc]
[vo_ri s="riri0143"]
[【梨里】]
「アンタ……今、気が付いたけど……央も……目が赤くなってる……。[r]
　他の人たちと同じ」[pcms][endhact]
*4223|
[fc]
[【央】]
「目が赤くなったやつらなら俺も見てきた。みんな楽しそうだったよ……[r]
　だから俺たちも……愉しもう。夕べの続きだ」[pcms][endhact]
[backlay][rir_lo_01_f04 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*4224|
[fc]
[vo_ri s="riri0144"]
[【梨里】]
「忘れて！　もうあんなことしないんだから！」[pcms][endhact]
[backlay][chara_int][trans time=150 method=crossfade][wt]
[se buf=0 storage="seB010"]
*4225|
[fc]
[quakesp time=500 laynum=0 hmax=20 vmax=20]
梨里は近寄った俺を突き飛ばした。[r]
あやうく転んでしまうところだった。[pcms]
*4226|
[fc]
[【央】]
「そうはいかない……俺は梨里とセックスしたくてたまらないんだ。[r]
　おい、おまえら？」[pcms][endhact]
*4227|
[fc]
のろのろと起き上がってくる男たちに声を掛けた。[pcms]
[backlay]
[kan_wr layer=4 x="&sf.wr_lo_x[4]" y="&sf.wr_lo_y[0]"]
[kan_ru layer=5 x="&sf.ra_lo_x[5]" y="&sf.ra_lo_y[0]"]
[trans method=universal rule="DtoT" vague=300 time=500][wt2]
*4228|
[fc]
[【央】]
「俺がメインになるが……手伝ってくれるなら……お裾分けしてやって[r]
　もいいぞ？」[pcms][endhact]
*4229|
[fc]
飢えた男たちは、俺が梨里に対して何か特別な影響力を持っているとでも[r]
思ったのか、あっさりとその誘いに乗ってきた。[pcms]
[backlay][chara_int][rir_lo_01_f16 layer=3 x="&sf.ri_lo_x[3]" y="&sf.ri_lo_y[0]"][trans time=150 method=crossfade][wt]
*4230|
[fc]
[vo_ri s="riri0145"]
[【梨里】]
「あ、央……アンタ……いったい何するつもりなの？」[pcms][endhact]
[backlay]
[kan_wr layer=1 x="&sf.wr_lo_x[1]" y="&sf.wr_lo_y[0]"]
[kan_ru layer=2 x="&sf.ra_lo_x[2]" y="&sf.ra_lo_y[0]"]
[trans method=universal rule="DtoT" vague=300 time=500][wt2]
*4231|
[fc]
飢えた野獣のようにがっついて梨里を襲っていた連中は統率者を自ら任じた[r]
俺の指示に従い、四方八方から梨里の四肢を拘束してくれた。[pcms]
*4232|
[fc]
[【央】]
「最初っから言ってるだろ？　梨里とセックスするんだってばよッ！」[pcms][endhact]
[backlay][chara_int][trans time=150 method=crossfade][wt]
[se buf=0 storage="seB013"]
*4233|
[fc]
俺は他の連中の力も借りて、もう逃げることさえできなくなっている[r]
梨里を強引に押し倒した。[pcms]
[backlay][rir_up_01_f04 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*4234|
[fc]
[vo_ri s="riri0146"]
[【梨里】]
「やめてよッ！　なんでアンタまで、おかしくなっちゃったのよ！」[pcms][endhact]
*4236|
[fc]
[【央】]
「おかしくなんかなってないッ！　夕べのセックスの続きをしようって、[r]
　それだけだッ！」[pcms][endhact]
;
[backlay][rir_up_01_f15 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*4238|
[fc]
[vo_ri s="riri0147"]
[【梨里】]
「あ、あれは何かの間違いで……流されて……もう絶対に顕悟を裏切らない[r]
　……そう決めてるの！」[pcms][endhact]
*4239|
[fc]
梨里はもう身じろぎする程度だったが、それでも頭を振って、[r]
俺を拒もうとする。[pcms]
[backlay][rir_up_01_f17 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*4240|
[fc]
[vo_ri s="riri0148"]
[【梨里】]
「助けて！　助けて顕悟！　央が……央までおかしくなっちゃったよ！」[pcms][endhact]
*4241|
[fc]
顕悟の名前が梨里の口から出たことで俺は頭に来てしまった。[r]
この場にいない顕悟に救いを求めたことも許せなかった。[pcms]
*4242|
[fc]
[【央】]
「顕悟はいないッ！　梨里の処女を奪ったのも最初に膣内射精したのも、[r]
　顕悟じゃなくてこの俺だッ！　俺の方が先に梨里を好きになってた！」[pcms][endhact]
[backlay][rir_up_01_f16 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*4243|
[fc]
[vo_ri s="riri0149"]
[【梨里】]
「なッ……なんでこんな時に……今さらなんで……どうしてもっと早く[r]
　そういうこと……教えてくれなかったのよ？」[pcms][endhact]
*4244|
[fc]
それは俺がセックスしたいと言った時よりも露骨な動揺だった。[r]
まさか梨里は顕悟よりも俺を……いや、そんなことはどうでもいいッ！[pcms]
*4245|
[fc]
[【央】]
「とにかく梨里は俺のものだッ！　顕悟のことは忘れろッ！」[pcms][endhact]
*4246|
[fc]
梨里のおっぱいを鷲づかみにしてそう怒鳴った。[r]
夕べと同じで手に馴染む素晴らしい触り心地だった。[pcms]
*4247|
[fc]
[vo_ri s="riri0150"]
[【梨里】]
「やめてッ！　これ以上酷いことしないでッ！　アンタのこと嫌いに[r]
　なりたくないから！　これからもあたしと央と顕悟の三人で仲良く――」[pcms][endhact]
*4248|
[fc]
[【央】]
「顕悟のことは忘れろと言ったはずだッ！」[pcms][endhact]
[se buf=0 storage="seB001"]
[赤フラ]
*4249|
[fc]
思わず俺は平手で梨里の顔を叩いていた。[r]
これでもかなり手加減はしているつもりだ。[pcms]
[backlay][rir_up_01_f15 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*4250|
[fc]
[vo_ri s="riri0151"]
[【梨里】]
「忘れない！　あたしは顕悟の彼女で央の彼女じゃない！　もう何もかも[r]
　遅いの！　今さら後出しジャンケンなんて卑怯よッ！」[pcms][endhact]
*4251|
[fc]
[【央】]
「何度も同じこと言わせるなッ！　梨里の処女をもらって膣内射精を最初に[r]
　したのは俺だッ！　つまりこれからは俺の彼女なんだよッ！」[pcms][endhact]
*4252|
[fc]
セックスだ！[r]
とにかくセックスして、既成事実を重ねれば梨里だって納得するはず！[pcms]
*4253|
[fc]
[【央】]
「彼女だから……梨里は俺の彼女だから、また感じさせてやるよ……エロい[r]
　声でアヘアヘわめかせて絶頂させてやるから期待してろよ？」[pcms][endhact]
[backlay][rir_up_01_f17 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*4254|
[fc]
[vo_ri s="riri0152"]
[【梨里】]
「いやああああッ！　やめて央っ！　いつもの央に戻ってえええッ！」[pcms][endhact]
*4255|
[fc]
ジタバタもがいて、梨里はなんとか逃げようとしていた。[r]
それが許せなかった。どうして彼氏である俺を拒むのか理解できない！[pcms]
*4256|
[fc]
[【央】]
「俺はいつもの俺のままだッ！　抵抗するんなら少しキツめのお仕置きを[r]
　する必要がありそうだな……ん？」[pcms][endhact]
[backlay][kan_ma0 layer=3 x="&sf.ma_lo_x[3]" y="&sf.ma_lo_y[0]"][trans time=150 method=crossfade][wt]
*4257|
[fc]
[ns【]感染者１[】nse]
「おまえ……やる気ないなら……俺にその女……寄越せ……俺がチンポを[r]
　突っ込んで……イカせてやるよ……代わりに！」[pcms][endhact]
[se buf=0 storage="seB008"]
[赤フラ]
*4258|
[fc]
[quakesp time=500 laynum=0 hmax=20 vmax=20]
[【央】]
「ぐはあッ？」[pcms][endhact]
*4259|
[fc]
男のひとりが割り込んできて、梨里の身体から俺を引き離そうとする。[r]
そいつの股間は丸出して、勃起したペニスが目に入った。[pcms]
*4260|
[fc]
[ns【]感染者１[】nse]
「引っ込めよ、どけ」[pcms][endhact]
*4261|
[fc]
[【央】]
「うるせえ！　引っ込むのはてめえだッ！」[pcms][endhact]
*4262|
[fc]
俺はそいつの背後に回り込み、両手でその頭をつかんだ。[r]
指先は……目にも届く。[pcms]
*4263|
[fc]
[ns【]感染者１[】nse]
「わ、悪かったッ！　あんたがさっさとチンポぶち込まないから少し、[r]
　がっついただけなんだ。勘弁してくれよ？」[pcms][endhact]
*4264|
[fc]
[【央】]
「引っ込めよ、どけッ！」[pcms][endhact]
[se buf=0 storage="seB076"]
[赤フラ]
*4265|
[fc]
[quakesp time=500 laynum=3 hmax=20 vmax=20]
[ns【]感染者１[】nse]
「おごああああッ……おわああああああッ！」[pcms][endhact]
[se buf=0 storage="seB025"]
[赤フラ]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*4266|
[fc]
快感混じりの悲鳴を上げてそいつは倒れた。[r]
俺はやつの目玉を潰し、頭蓋骨の一部も砕いていた。[pcms]
*4267|
[fc]
[【央】]
「やっぱり今夜の俺は無敵モードだな。素手で人間の頭の骨をぶっ壊す[r]
　なんて普通じゃないしな」[pcms][endhact]
*4268|
[fc]
リアル格闘マンガの最高峰のような作品の登場キャラにでもなった感じで、[r]
いい気分だった。[pcms]
*4269|
[fc]
今ならきっと百メートル９秒を切ったり、野生の象を素手で仕留めたり、[r]
恐竜を捕食する原始人と戦ったり、現代に復活した宮本武蔵に勝てそうだ。[pcms]
*4270|
[fc]
[【央】]
「ッしゃあああああッ！」[pcms][endhact]
*4271|
[fc]
闘技場で雄叫びを上げるような気分で俺は大声を出して、それから死んだ[r]
そいつのシャツで返り血やなんかを拭き取った。[pcms]
[backlay][rir_up_01_f16 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*4272|
[fc]
[vo_ri s="riri0153"]
[【梨里】]
「あ、央ァ……アンタ……自分が何してるのか……何やったのか……[r]
　わかってるの？」[pcms][endhact]
*4273|
[fc]
梨里の目には恐怖がある。[r]
そして、それは間違いなくこの俺に向けられていた。[pcms]
*4274|
[fc]
[【央】]
「梨里……どうしてそんなに怖がってるんだよ？　俺だよ、幼なじみの央[r]
　だよ？　昔からずっとおまえのことが好きな央なんだぞ？」[pcms][endhact]
[backlay][rir_up_01_f14 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*4275|
[fc]
[vo_ri s="riri0154"]
[【梨里】]
「ち、違う……央はそんなことしない……できたとしてもするはずない！[r]
　アンタは央の顔をした別人……ううん、化け物だよ！」[pcms][endhact]
*4276|
[fc]
[【央】]
「いくら梨里でも言っていい事と悪い事があるぞ……お仕置きしてやる。[r]
　二度と彼氏の俺に反抗しない立派な彼女になるためのお仕置きだッ！」[pcms][endhact]
[backlay][black_toplayer][trans time=500 method=crossfade][wt2][hide_chara_int]
[se buf=0 storage="seB072"]
*4276a|
[fc]
俺は梨里の陸上用ウェアを強引に剥ぎ取る。[pcms]
[sysbt_meswin clear]
[fadeoutbgm time=500]
*scene_start
[bgm storage="bgm14" time=100]
[backlay][evcg storage="EV14_01" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
[wait2 time=500]
[sysbt_meswin]
*4277|
[fc]
[vo_ri s="riri0155"]
[【梨里】]
「ぎひいいいいッ？　いやああああッ！　やめてえええええッ！」[pcms][endhact]
*4278|
[fc]
俺は前戯も何も抜きで、濡れてもいない梨里の秘所に勃起したペニスを[r]
あてがうと、強引な挿入を実行していた。[pcms]
[se buf=0 storage="se_sex01"]
[evcg白フラ storage="EV14_03" layer=0 page=back visible=true left=0 top=0]
*4279|
[fc]
[vo_ri s="riri0156"]
[【梨里】]
「ひいいいいいッ！　痛いッ！　やめてえええ央ッ！」[pcms][endhact]
[se buf=1 storage="se_sex02" loop=true]
*4280|
[fc]
梨里は苦痛に泣き叫び身悶えしていた。[r]
少しかわいそうだけど、お仕置きなんだから仕方がない。[pcms]
*4281|
[fc]
[【央】]
「すげえぞ梨里！　まるで濡れてなかったのに、突っ込んだたら、膣内は[r]
　夕べみたいにギチギチに締めてくるしメチャクチャ熱いッ！」[pcms][endhact]
*4282|
[fc]
夢中になって俺は腰を振り、梨里の膣内で快感を愉しむ。[pcms]
[backlay][evcg storage="EV14_04" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4283|
[fc]
[vo_ri s="riri0157"]
[【梨里】]
「くああああッ……あぐあああッ……あぐひいいいいッ！」[pcms][endhact]
*4284|
[fc]
夕べみたいに快感に乱れる梨里もエロかったけど、痛がって泣きわめく[r]
梨里もきれいだと思った。[pcms]
*4285|
[fc]
[【央】]
「きれいだよ梨里……それにエロいし……マンコでも俺のを締め付けて[r]
　くれて……気持ちいいよ……さすが俺の彼女……また膣内射精するぞ」[pcms][endhact]
[backlay][evcg storage="EV14_05" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4286|
[fc]
[vo_ri s="riri0158"]
[【梨里】]
「やめて央っ……もうやめてえっ！　ほんとに央の赤ちゃん……、[r]
　妊娠しちゃう　よおっ！」[pcms][endhact]
*4287|
[fc]
[【央】]
「俺の赤ちゃんはそんなに嫌かッ？　顕悟のならいいってのかよッ？[r]
　決めた……絶対に妊娠させてやる……顕悟以外の男で妊娠させてやるッ！」[pcms][endhact]
[se buf=1 storage="se_sex03" loop=true]
*4288|
[fc]
俺はますます腰の律動を加速させて、梨里の膣内奥深くをえぐり、貫く。[r]
悲嘆する梨里と裏腹に膣内は一刻も早く俺を射精させようとしていた。[pcms]
*4289|
[fc]
[vo_ri s="riri0159"]
[【梨里】]
「ひあああっ……いやああ……赤ちゃん欲しくない……もうやめてえ！」[pcms][endhact]
*4290|
[fc]
だが梨里の引き締まって鍛えられた身体は本人の意思とは無関係に男を[r]
迎え入れて、快楽で縛り付けようとしていた。[pcms]
*4291|
[fc]
やはりなんといっても、この膣内の収縮が絶妙だ。梨里の日頃の鍛錬の賜物[r]
だろう。俺も何人も女と経験してきたが、他の女では味わえない。[pcms]
*4292|
[fc]
[【央】]
「くッ……出すぞ梨里ッ！　俺の精液で妊娠するんだッ！」[pcms][endhact]
*4293|
[fc]
夕べみたいにお互いが快感におぼれるような流れとは違うが、俺は梨里の[r]
膣内の深奥でペニスを微細な肉襞にこすられ、さらに締め上げられ果てた。[pcms]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[射精フラA]
[backlay][evcg storage="EV14_06" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[射精フラB]
*4294|
[fc]
[vo_ri s="riri0160"]
[【梨里】]
「いやあああっ！　央の精液……せーえきまたお腹に出されたあっ！」[pcms][endhact]
*4295|
[fc]
無論、お仕置きなのだから梨里には快感や絶頂は無かったが、それでも、[r]
射精されたことを嘆くその叫びはたまらなく俺を興奮させてくれた。[pcms]
[backlay][evcg storage="EV14_07" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4296|
[fc]
[【央】]
「ふううっ……ふう……やっぱり梨里の梨里マンコがいちばん最高だよ。[r]
　他の女は……累先輩だってこれに比べたら下だな」[pcms][endhact]
*4297|
[fc]
[vo_ri s="riri0161"]
[【梨里】]
「あ、アンタまさか……蘆名先輩にまで乱暴して……」[pcms][endhact]
*4298|
[fc]
[【央】]
「勘違いするな。累先輩が俺を誘惑してきて、それでつい相手したって[r]
　だけだ。あの人は梨里と違ってお従兄様とやらが遊び倒した中古だ」[pcms][endhact]
*4299|
[fc]
[【央】]
「彼氏の俺のために……顕悟にも許さないで処女を守ってくれてた梨里[r]
　とは違う……俺の梨里とは違う……梨里とは……梨里……」[pcms][endhact]
*4300|
[fc]
何かがおかしい。[r]
わずかに目覚めた理性が脳裏で警告を発していた。[pcms]
*4301|
[fc]
自分が何をしているのか、これまで何をやらかしてきていたのか。[r]
そのすべてを俺は理解してしまいそうだった。[pcms]
*4302|
[fc]
だが、理性を取り戻してしまえば梨里とのセックスはまた禁じられて[r]
しまいそうだという予感が、俺に現状維持を選択させた。[pcms]
*4303|
[fc]
[【央】]
「ふううッ……累先輩なんて今は関係ないッ！　梨里、少し休んだら、[r]
　またセックスするぞ！　妊娠するまでだッ！」[pcms][endhact]
[se buf=0 storage="seD017"]
[backlay][evcg storage="EV14_08" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4304|
[fc]
梨里の秘裂の断面から垂れてくる精液は顕悟のものではなく俺のものだ。[pcms]
*4305|
[fc]
[vo_ri s="riri0162"]
[【梨里】]
「ううっ……えううっ……なんで……こんな……央ひどいよ……」[pcms][endhact]
*4306|
[fc]
[【央】]
「お仕置きだからな。まだまだ厳しくするぞ梨里ッ！」[pcms][endhact]
[se buf=0 storage="seA045"]
*4307|
[fc]
さて、次はどうお仕置きしようかと悩んでいると背後から足音が響く。[pcms]
*4308|
[fc]
[【央】]
「誰だッ？」[pcms][endhact]
[stopse buf=0]
[backlay][bg storage="BG14b"]
[sud_lo_03_k01 layer=3 x="&sf.su_lo_x[3]" y="&sf.su_lo_y[0]"]
[trans method=universal rule="LtoR" vague=100 time=300][wt2]
*4309|
[fc]
振り返って確認すると、そいつは我が悪友の須田だった。[pcms]
*4310|
[fc]
[【須田】]
「おおっ？　やっぱり央と清原かよ。俺も混ぜてくれよ？」[pcms][endhact]
*4311|
[fc]
[【央】]
「おまえは子野日さんと遊んでたはずだろ？」[pcms][endhact]
*4312|
[fc]
[【須田】]
「人聞きが悪いこと言うなよ。おまえと先輩たちがお楽しみの後で[r]
　お裾分けしてもらっただけだってば」[pcms][endhact]
*4313|
[fc]
[vo_ri s="riri0163"]
[【梨里】]
「央……子野日さんにまで乱暴……須田も……目が赤い……」[pcms][endhact]
*4314|
[fc]
[【須田】]
「それに子野日さん、さっきからなんか、ぶつぶつなんか言うだけで[r]
　エロい反応してくれないんだ。ぶっ壊れたらしくてな」[pcms][endhact]
*4315|
[fc]
[【央】]
「よってたかって犯りまくるからだよ。調子に乗りすぎだぞ須田」[pcms][endhact]
*4316|
[fc]
[【須田】]
「なあ央、俺にも清原と一発、犯らせてくれよ？　頼むからさ～」[pcms][endhact]
*4317|
[fc]
[vo_ri s="riri0164"]
[【梨里】]
「須田っ！　アンタもやっぱり、頭おかしくなってるの？」[pcms][endhact]
*4318|
[fc]
[【央】]
「まあ須田ならいいか。お仕置きのネタに困ってたとこだし、[r]
　二度と彼氏の俺に逆らうなって教えてやってくれ」[pcms][endhact]
*4319|
[fc]
[【須田】]
「んじゃあ……清原……俺と遊ぼうぜ～♪」[pcms][endhact]
*4320|
[fc]
俺は須田に梨里を譲って身体を離し、二人のセックスを見届けることにした。[pcms]
[sysbt_meswin clear]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
[backlay][evcg storage="EV14_09" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
[sysbt_meswin]
*4321|
[fc]
[vo_ri s="riri0165"]
[【梨里】]
「や、やめてえ須田！　と、友達なのになんでこんなこと！」[pcms][endhact]
*4322|
[fc]
俺はさっきから命令に従ってくれている男どもと須田に梨里を任せて、[r]
一歩引いた場所からその光景を見守っていた。[pcms]
*4323|
[fc]
[【須田】]
「前からずっと……陸上の練習してる清原を見てて……いいなって……[r]
　そう思ってた。なんか妹っぽい感じで俺の趣味に合うっていうかさ」[pcms][endhact]
*4324|
[fc]
俺と入れ替わった須田は精液まみれとなった梨里の秘裂に自分のペニスを[r]
あてがい、そして一気に挿入していく。[pcms]
[se buf=0 storage="se_sex01"]
[evcg白フラ storage="EV14_10" layer=0 page=back visible=true left=0 top=0]
*4325|
[fc]
[vo_ri s="riri0166"]
[【梨里】]
「ひいいッ……いやああ！　顕悟のじゃないのにいッ！　央のでもないのが[r]
　あたしの中に入ってきちゃうう！」[pcms][endhact]
[se buf=1 storage="se_sex02" loop=true]
*4326|
[fc]
事前に俺がたっぷり精液を出してやったこともあり、それが潤滑液として、[r]
作用し、梨里に苦痛を与えない。[pcms]
*4327|
[fc]
[【央】]
「おい須田、おまえ子野日さんを犯った時は、あの子みたいのがタイプとか[r]
　それっぽいこと言ってなかったか？」[pcms][endhact]
*4328|
[fc]
具体的な言葉は忘れたけど、とにかく、それらしき発言があった気がする。[r]
子野日さんは梨里とはタイプが違うはずだ。[pcms]
*4329|
[fc]
[【須田】]
「妹っぽい女の子と一口に言えば簡単だけど、単純な分類だけでも最低で[r]
　十二種類はある。清原は強気で活発な妹っぽさが魅力的なんだよ！」[pcms][endhact]
*4330|
[fc]
こちらからの悪態に反論すると須田は夢中になって腰を振り、梨里の膣内で[r]
ペニスを動かしていた。[pcms]
*4331|
[fc]
[【須田】]
「清原の小麦色に焼けた健康的な肌に俺の白い精液をぶちまけるのをネタに[r]
　オナニーしまくりだったんだ……夢がかなうッ！」[pcms][endhact]
*4332|
[fc]
こいつはたぶん、今夜まで童貞だったような気がするけど、少なくとも[r]
子野日さんと犯って経験を積んだはずだ。[pcms]
*4333|
[fc]
それでもこんな風にがっついているのは以前から梨里にエロい欲望を抱いて[r]
いた証明かもしれない。[pcms]
*4334|
[fc]
[【須田】]
「清原……俺のことお兄ちゃんとか呼んで……それで絶頂とかしてくれよ？[r]
　なあ頼むよ……いいだろ？」[pcms][endhact]
[backlay][evcg storage="EV14_11" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4335|
[fc]
[vo_ri s="riri0167"]
[【梨里】]
「ふ、ふざけないで！　誰がそんなこと！」[pcms][endhact]
*4336|
[fc]
[【央】]
「おい梨里、彼氏である俺からの命令だ。お仕置きの一環として、須田の[r]
　リクエスト通りにしてやれ。お兄ちゃんと呼んでイってやれ」[pcms][endhact]
*4337|
[fc]
[vo_ri s="riri0168"]
[【梨里】]
「変態ッ！　バカっ！　人でなしッ！」[pcms][endhact]
*4338|
[fc]
梨里は須田の顔に唾を吐いて浴びせていた。[r]
梨里らしい言動だと不思議に納得して、そこに俺は魅力を感じ惚れ直した。[pcms]
*4339|
[fc]
[【須田】]
「や、やばっ……清原から直接、唾をぶっかけられちまったぜ央。俺もう[r]
　イキそう……膣内射精しても……いいよなッ？」[pcms][endhact]
*4340|
[fc]
[【央】]
「ダメだッ！　梨里は俺の彼女……膣内射精していいのは俺だけだッ！[r]
　ぶっかけは認めてやるからそうしろッ！」[pcms][endhact]
[backlay][evcg storage="EV14_12" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4341|
[fc]
[vo_ri s="riri0169"]
[【梨里】]
「か、勝手にそんなの決めないでよッ！」[pcms][endhact]
*4342|
[fc]
[【須田】]
「くうううッ……清原ァあああッ！　お兄ちゃんだよおおおおッ！」[pcms][endhact]
*4343|
[fc]
[vo_ri s="riri0170"]
[【梨里】]
「うああああああああああッ？」[pcms][endhact]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[射精フラA]
[backlay][evcg storage="EV14_13" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[射精フラB]
*4344|
[fc]
最後の瞬間、須田は俺との友情を守ってペニスを引き抜き、その精液は[r]
梨里の太ももに浴びせられていた。[pcms]
*4345|
[fc]
[vo_ri s="riri0171"]
[【梨里】]
「ううっ……ひどいよ……央も須田も……友達……なのに……」[pcms][endhact]
[backlay][evcg storage="EV14_14" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4346|
[fc]
[【須田】]
「最後までお兄ちゃんと呼んでくれなかったのは本当に残念だったけど[r]
　それでも良かったよ清原……ああ……少し休むよ」[pcms][endhact]
[backlay][bg storage="BG14b"][trans time=500 method=crossfade][wt2]
*4347|
[fc]
満足げに笑うと須田は梨里から離れて俺の近くに寄ってくる。[pcms]
*4348|
[fc]
[【央】]
「さてと、お仕置きはまだ続くぞ梨里。次は――」[pcms][endhact]
*4349|
[fc]
俺の指示に従ってる連中の誰かに、ご褒美として梨里を抱かせてやるか。[r]
反抗的な梨里を大人しくさせるのに膣内射精させてもいいかもしれない。[pcms]
*4350|
[fc]
そんな風に考えていると、聞き覚えのある声が聞こえた。[r]
夕べ、梨里の幼なじみの純とかいう子とセックスしてた他校の男子だ。[pcms]
[backlay][yuj_lo_04_k01 layer=3 x="&sf.yu_lo_x[3]" y="&sf.yu_lo_y[0]"][trans time=150 method=crossfade][wt]
*4351|
[fc]
[【勇二】]
「さっきから見てた。あんた渋江って人だよな。俺も仲間に入れてくれよ？」[pcms][endhact]
*4351a|
[fc]
[【央】]
「純がいるんじゃないのかよ？　勇二だっけ？　なんでお前[r]
　俺のこと知ってる？」[pcms][endhact]
*4352|
[fc]
[vo_ri s="riri0172"]
[【梨里】]
「勇二って……純はどうしたの……？　それに眼が……赤い……」[pcms][endhact]
[backlay][sud_up_01_k01 layer=3 x="&sf.su_up_x[3]" y="&sf.su_up_y[0]"][trans time=150 method=crossfade][wt]
*4353|
[fc]
[【須田】]
「おい央、こいつ、いきなり出てきてなんだよ？　ヤっちまおうぜ？」[pcms][endhact]
*4354|
[fc]
[【央】]
「まあ落ち着け須田。人間と動物の違いは互いに意思疎通できることだ。[r]
　とりあえず殺し合う前に話だけは聞いてやろう」[pcms][endhact]
[backlay][yuj_lo_04_k01 layer=3 x="&sf.yu_lo_x[3]" y="&sf.yu_lo_y[0]"][trans time=150 method=crossfade][wt]
*4355|
[fc]
[【勇二】]
「梨里ちゃんと一発、犯りたい。話はそれだけだ」[pcms][endhact]
*4356|
[fc]
ある意味でこいつは俺と同様でシンプルだった。[r]
そこに好感を抱いた。[pcms]
*4357|
[fc]
[【央】]
「梨里をどう思う？」[pcms][endhact]
*4358|
[fc]
[【勇二】]
「純から話は何度も聞いてた。あんたのことも含めてな。そして直接、[r]
　目で見て……純と同じようでいてどこか違う……そこに惹かれた」[pcms][endhact]
*4359|
[fc]
[【勇二】]
「ぶっちゃけた話をするとだ……純と犯りたくて探してたんだが、さっぱり[r]
　見当たらない。純の代わりに純に近い梨里ちゃんと犯りたい」[pcms][endhact]
*4360|
[fc]
[【央】]
「一応、聞いておくか。おい梨里、勇二とセックスしたいか？」[pcms][endhact]
*4361|
[fc]
[vo_ri s="riri0173"]
[【梨里】]
「冗談じゃない！　親友の彼氏とセックスなんて、いくらなんでも、[r]
　あり得ない！」[pcms][endhact]
*4362|
[fc]
まあ当然の反応だろう。[r]
俺としても通常であれば論外だとして拒絶する。[pcms]
*4363|
[fc]
[vo_ri s="riri0174"]
[【梨里】]
「ねえ央、アンタがあたしの彼氏気取りするなら……そんなの認めないで[r]
　やめさせてよ？」[pcms][endhact]
*4364|
[fc]
顕悟との関係を主張し、俺を拒んでいたくせに、梨里は今さらここで、俺に[r]
すり寄るようなことを言ってきた。[pcms]
*4365|
[fc]
[【央】]
「わかったよ梨里。その言葉で俺も決心した。安心しろ」[pcms][endhact]
*4366|
[fc]
[vo_ri s="riri0175"]
[【梨里】]
「央……まだ少しだけ……まともな部分もあるんだ……良かった……」[pcms][endhact]
[backlay][yuj_up_04_k01 layer=3 x="&sf.yu_up_x[3]" y="&sf.yu_up_y[0]"][trans time=150 method=crossfade][wt]
*4367|
[fc]
[【勇二】]
「仕方ない……じゃあ、あんたと殺し合ってから梨里ちゃんを犯すか」[pcms][endhact]
*4368|
[fc]
勇二は拳を握って、今にも殴りかかりそうな勢いだった。[r]
こいつと戦うのも魅力的だったが、俺は先に決めたことを優先した。[pcms]
*4369|
[fc]
[【央】]
「いや、その必要は無い。勇二、梨里とセックスしていい。ただし膣内射精[r]
　だけは認めない。それを破ったら殺す」[pcms][endhact]
*4370|
[fc]
[vo_ri s="riri0176"]
[【梨里】]
「央？　どうして？」[pcms][endhact]
*4371|
[fc]
[【勇二】]
「どういうつもりだ？」[pcms][endhact]
*4372|
[fc]
[【央】]
「俺は梨里にお仕置きしてるところなんだ。他の有象無象の男どもより、[r]
　親友の純、その彼氏であるあんたに犯される方が、罰になる」[pcms][endhact]
*4373|
[fc]
[【勇二】]
「なるほどな……しかし俺はあんたの要求を無視して勝手に膣内射精する[r]
　……そういう可能性だってあるんだがな？」[pcms][endhact]
*4374|
[fc]
[【央】]
「その時はその時で、あらためて殺し合おうじゃないか。どうする？」[pcms][endhact]
*4375|
[fc]
[【勇二】]
「了解したぜ渋江。じゃあ俺もお仕置きの手伝いをさせてもらうッ！」[pcms][endhact]
*4376|
[fc]
[vo_ri s="riri0177"]
[【梨里】]
「やめてえ勇二君！　純のこと裏切っちゃダメええええッ！」[pcms][endhact]
[sysbt_meswin clear]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
[backlay][evcg storage="EV14_15" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
[sysbt_meswin]
*4377|
[fc]
だがその悲痛な願いの叫びもむなしく、勇二は梨里に襲いかかった。[r]
俺と須田、他の男どもはそれをニヤニヤ笑いながら見つめていた。[pcms]
*4378|
[fc]
[【勇二】]
「純がどこかに行ったのが悪いんだ！　純の親友だってなら梨里ちゃん、[r]
　責任取って、俺の性欲なんとかしてくれッ！」[pcms][endhact]
[se buf=0 storage="se_sex01"]
[evcg白フラ storage="EV14_16" layer=0 page=back visible=true left=0 top=0]
*4379|
[fc]
[vo_ri s="riri0178"]
[【梨里】]
「ひぎふッ……うはあああッ……ごめん純ッ！」[pcms][endhact]
[se buf=1 storage="se_sex02" loop=true]
*4380|
[fc]
勇二のペニスをその膣内に受け入れてしまった梨里は、[r]
親友に対しての謝罪を口にしながら嘆く。[pcms]
*4381|
[fc]
[【勇二】]
「へええ……純のと違って……ねっとりと肉襞がからみついてくるな……[r]
　もしかしたら純よりも名器かも」[pcms][endhact]
*4382|
[fc]
勇二は須田とは対照的に性急な腰の動きには走らず、梨里の膣内を少しずつ[r]
探るかのように慎重な抜き差しを続けていた。[pcms]
[backlay][evcg storage="EV14_17" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4383|
[fc]
[vo_ri s="riri0179"]
[【梨里】]
「許して純っ……あたし抵抗したけど……嫌だったけど……ああ……」[pcms][endhact]
*4384|
[fc]
梨里はこの場にいない純に対して、空しい言い訳を繰り返す。[r]
そうすることで正気を保とうとしているのだと思った。[pcms]
*4385|
[fc]
[【央】]
「なあ勇二……俺が譲ってやったのには、お仕置き以外にもうひとつ、[r]
　恩返しの側面もあるんだ。感謝してるよ」[pcms][endhact]
*4386|
[fc]
[【勇二】]
「意味がわからないな」[pcms][endhact]
*4387|
[fc]
[【央】]
「当然さ。夕べ、アンタと純がセックスしてた。それをのぞき見して……[r]
　オナニーしてた、いけない女の子がいるんだ」[pcms][endhact]
*4388|
[fc]
[【勇二】]
「さっぱり話が見えないなあ」[pcms][endhact]
[backlay][evcg storage="EV14_19" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4389|
[fc]
[vo_ri s="riri0180"]
[【梨里】]
「うはああッ？」[pcms][endhact]
*4390|
[fc]
膣内奥深くにペニスを到達させながら勇二は不可解そうな顔になる。[r]
梨里の方は苦痛を感じてはいないが俺が振った話題に反応し動揺していた。[pcms]
*4391|
[fc]
[【央】]
「俺はその女の子がエロい反応で乱れてるのに付け込んで……少し強引に[r]
　途中からはお互いの合意でセックスして童貞を捨てた」[pcms][endhact]
*4392|
[fc]
[【勇二】]
「ほう？」[pcms][endhact]
*4393|
[fc]
[【央】]
「その女の子も処女で……お互い、初めてどうしだったけど、最高に熱くて[r]
　気持ちいいセックスになった……だから感謝してお礼なんだ。なあ梨里？」[pcms][endhact]
*4393a|
[fc]
その呼びかけで勇二にも、そして須田にも、純と勇二のセックスを盗み見して[r]
オナニーしていた、いけない女の子が梨里だと理解できたようだった。[pcms]
[backlay][evcg storage="EV14_18" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4394|
[fc]
[vo_ri s="riri0181"]
[【梨里】]
「知らないッ！　あたしそんなの知らない！　純がもう経験してるなんて[r]
　夕べまで知らなかった！」[pcms][endhact]
*4395|
[fc]
[vo_ri s="riri0182"]
[【梨里】]
「央が言ってるエッチないけない女の子じゃない！　あたし違うもん！」[pcms][endhact]
*4396|
[fc]
だがその大声での必死な否定は、その言葉自体に当事者であるという証明を[r]
含んだ矛盾するものでしかなかった。[pcms]
*4397|
[fc]
[【勇二】]
「梨里ちゃん……君は親友の純が男に……俺に抱かれるを盗み見して……[r]
　それをネタにオナニーするような、いやらしい女の子だったのか？」[pcms][endhact]
*4398|
[fc]
[vo_ri s="riri0183"]
[【梨里】]
「違うって言ってるでしょ！　知らない！　感じてなんかなかった！　[r]
　エッチな声も出してない！　オナニーなんかしてない！」[pcms][endhact]
*4399|
[fc]
[【勇二】]
「変態だな梨里ちゃん……やっぱりお仕置きが必要だ……渋江の判断は[r]
　正しいようだ。協力するぞ……俺のチンポで射精して！」[pcms][endhact]
[se buf=1 storage="se_sex03" loop=true]
[backlay][evcg storage="EV14_19" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4400|
[fc]
[vo_ri s="riri0184"]
[【梨里】]
「いやああッ！　おちんちん動かすの速くなってる？」[pcms][endhact]
*4401|
[fc]
梨里が言ったように勇二の腰の動きは急加速していた。膣内射精する[r]
可能性は当然あったが、俺はあえて警告せず見守り続ける。[pcms]
*4402|
[fc]
[vo_ri s="riri0185"]
[【梨里】]
「出されちゃう！　純の彼氏に……親友の彼氏に射精されちゃう！」[pcms][endhact]
*4403|
[fc]
[【勇二】]
「それも悪くないが……俺はずっと前から……純にしたくても、[r]
　できなかったことを……雰囲気が似た梨里ちゃんにさせてもらうッ！」[pcms][endhact]
*4404|
[fc]
その瞬間、勇二はペニスを引き抜くと、梨里のへそ周辺のお腹の部分に[r]
精液を浴びせていた。[pcms]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[射精フラA]
[backlay][evcg storage="EV14_20" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[射精フラB]
*4405|
[fc]
[vo_ri s="riri0186"]
[【梨里】]
「ふひゃああっ……お、お腹に……お腹の上に……？」[pcms][endhact]
*4406|
[fc]
[【勇二】]
「スポーツで引き締まった女の子の腹筋にぶっかける。これがいいのに、[r]
　純のやつ、スポーツを汚すとか冒涜とか言って、させてくれないんだ」[pcms][endhact]
*4407|
[fc]
[vo_ri s="riri0187"]
[【梨里】]
「純は正しいよ……おかしいのは……絶対にそっちだよ……」[pcms][endhact]
*4408|
[fc]
泣きそうな顔で親友の意見に梨里は賛成していた。[pcms]
*4409|
[fc]
[【勇二】]
「もう俺は今夜からは遠慮しない。いずれ純の腹筋にもぶっかける。今夜は[r]
　予行演習させてもらった。純と同格の絞まりでいいマンコだったよ」[pcms][endhact]
*4410|
[fc]
[【須田】]
「良かったな清原？　他校の男子からも名器だとお墨付きが出たんだ」[pcms][endhact]
*4411|
[fc]
[【央】]
「ははははは♪　須田の言う通りだぞ梨里。さ～て次は誰にお仕置き役を[r]
　お願いするか――」[pcms][endhact]
[backlay][evcg storage="EV14_21" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*4412|
[fc]
勇二が梨里の身体から離れ、次のお仕置き相手に悩んでいると、またしても[r]
新たな声が背中から聞こえてくる。[pcms]
*4413|
[fc]
[ns【]佐竹[】nse]
「渋江、おまえら部長の俺を差し置いて、何を騒いでいる？」[pcms][endhact]
*4414|
[fc]
それは我が水泳部の部長、三年生の佐竹先輩だった。[r]
無敵モードの今の俺でさえ戦慄する様な野太く荒々しい声だった。[pcms]
*4415|
[fc]
[【央】]
「さ、佐竹先輩、これは梨里が……梨里にお仕置きしてるところでして！」[pcms][endhact]
*4416|
[fc]
[ns【]佐竹[】nse]
「言い訳無用だッ！　おい清原、大丈夫か？　もう無事だぞ？」[pcms][endhact]
*4417|
[fc]
[vo_ri s="riri0188"]
[【梨里】]
「さ、佐竹先輩……たすけて……ください……」[pcms][endhact]
*4418|
[fc]
[ns【]佐竹[】nse]
「もちろんだとも清原。こんな二年の小僧や他校の男子では不可能な[r]
　真の快楽というものをおまえの身体に叩き込んでやるッ！」[pcms][endhact]
*4419|
[fc]
[vo_ri s="riri0189"]
[【梨里】]
「佐竹先輩……いやあ……佐竹先輩の目も……赤く……なってる」[pcms][endhact]
*4420|
[fc]
須田が登場した時と同じように、ぬか喜びするだけだった梨里は[r]
絶望して、自分の運命に悲嘆するだけだった。[pcms]
[if exp="tf.scene_mode == 1 && tf.all_play == 0"]
	[jump storage="b_scene.ks" target=*back_from_SR]
[endif]
[jump storage="0392_2.ks"]
