*SRP09
[eval exp="sf.SRP09 = 1"]
[eval exp="sf.SRP_all_03 = 1"]
[if exp="tf.scene_mode"]
	
	[bgm storage="bgm10" time=100]
	[jump target=*scene_start]
[endif]
[sysbt_meswin clear]
[fadeoutbgm time=500]
[backlay][black_toplayer][trans time=1000 method=crossfade][wt2][hide_chara_int]
[stopse buf=0]
[wait2 time=500]
[backlay][bg storage="BGskyd"][trans time=500 method=crossfade][wt2]
[bgm storage="bgm10" time=100]
[sysbt_meswin]
*4631|
[fc]
気が付くと夜が明けていた。[r]
遠くからは誰かの叫びや声が聞こえている。[pcms]
[sysbt_meswin clear]
[backlay][black_toplayer][trans time=500 method=crossfade][wt2][hide_chara_int]
*scene_start
[backlay][evcg storage="EV17_01" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
[wait2 time=500]
[sysbt_meswin]
*4632|
[fc]
[vo_ri s="riri0237"]
[【梨里】]
「っ……は……ふ……う……」[pcms][endhact]
[backlay][evcg storage="EV17_02" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[se buf=1 storage="se_sex03" loop=true]
*4633|
[fc]
[【央】]
「梨里ッ……好きだッ……ずっと前から……ごめんな告白遅くなってッ！」[pcms][endhact]
*4634|
[fc]
俺はひたすら梨里と愛し合っていた。[r]
梨里も無口だったけど笑って答えてくれている……たぶんそうだ。[pcms]
*4635|
[fc]
[vo_ri s="riri0238"]
[【梨里】]
「ね、ねえ央ァあ……あたしもずっと……好きだったんだよ？[r]
　もっと早く、こうしてほしかったなぁ～……」[pcms][endhact]
*4636|
[fc]
[【央】]
「わかってるッ！　ごめん、ごめんな梨里ッ！」[pcms][endhact]
*4637|
[fc]
梨里の膣内はどれだけペニスで抜き差しして射精しても、優しく俺を受け[r]
止めて、癒してくれる。[pcms]
*4638|
[fc]
その気持ちよさは他のどん女の子とのセックスよりも鋭くて温かくて、[r]
ずっとつながっていたくて、こうしていた。[pcms]
*4639|
[fc]
須田と同時にマンコを犯したあの直後、さすがに俺も疲れ果てて、他の男[r]
たちに梨里を奪われてしまった。[pcms]
*4640|
[fc]
梨里は泣き叫んだが、次第に快感を楽しんで、男たちを手玉に取っていた。[r]
夜通し穴という穴を犯され、数え切れないほど絶頂と気絶を繰り返した。[pcms]
*4641|
[fc]
ちょうど俺が立ち上がる気力を取り戻した頃には、あんなに大勢いた男ども[r]
は軒並み、ぶっ倒れていた。[pcms]
*4642|
[fc]
死んだのが大半で、まだ痙攣だけしているやつらもいる。[r]
須田や大久保コーチ、佐竹先輩はまだ、ぴくぴく動いていた。[pcms]
*4643|
[fc]
とにかく二人っきりになった俺と梨里は、ひたすらセックスに興じていた。[r]
処女喪失の時と同じでエロく反応してくれたのが、うれしかった。[pcms]
*4644|
[fc]
[vo_ri s="riri0239"]
[【梨里】]
「気持ちいい……感じちゃう……央のおちんちんがいちばん！[r]
　早く！　せーえき早く出してええッ！」[pcms][endhact]
*4645|
[fc]
[【央】]
「ああ……出すぞ梨里ッ……俺の彼女の膣内に出すッ！」[pcms][endhact]
*4646|
[fc]
[vo_ri s="riri0240"]
[【梨里】]
「ふわあああんっ……あったかいようっ！　気持ちいいようっ！　もう[r]
　もうあたし……イクっ……幼なじみの央のおちんちんでイクうっ！」[pcms][endhact]
*4647|
[fc]
[【央】]
「俺もイクっ……精液出すぞッ！　これが……合宿が終わったら……家に[r]
　帰ったら顕悟も呼んで三人でセックスしような？」[pcms][endhact]
*4648|
[fc]
きっと幼なじみ三人でのセックスはすごく気持ちいいはずだ。[r]
俺たち三人がそろえば最高に決まってるッ！[pcms]
*4649|
[fc]
[vo_ri s="riri0241"]
[【梨里】]
「あき……ら……けん……ご……って……だれ……だっけ？」[pcms][endhact]
*4650|
[fc]
[【央】]
「うおおおおおおッ！　好きだ梨里ッ！　愛してるッ！　結婚しようッ！」[pcms][endhact]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[射精フラA]
[backlay][evcg storage="EV17_03" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
[射精フラB]
*4651|
[fc]
これまでで最高に気持ちいい射精を済ませ、その余韻に浸ったが、[r]
なぜか梨里は返事をしてくれない。[pcms]
*4652|
[fc]
[【央】]
「あ、そうか……そうだよな梨里。俺も疲れたってことは梨里だって疲れて[r]
　当然だよな。わかった、休憩しようか」[pcms][endhact]
[se buf=0 storage="seC018"]
*4653|
[fc]
[【央】]
「ん？　ありゃ飛行機……か？」[pcms][endhact]
[backlay][bg storage="BGskyd"][trans time=500 method=crossfade][wt2]
*4654|
[fc]
朝焼けの中、テレビか映画で見た気がする爆撃機っぽいものが飛んでいる。[r]
きれいだ、と思ったが、すぐに否定した。[pcms]
*4655|
[fc]
[【央】]
「今の無し、やっぱりいちばんきれいでかわいいのは俺の梨里――」[pcms][endhact]
[stopbgm]
[sysbt_meswin clear]
[白フラ]
[wait2 time=100]
[backlay][white_toplayer]
[trans method=universal rule="wipe" vague=300 time=150][wt2]
[se buf=0 storage="seB058"]
[wait2 time=1000]
[backlay][black_toplayer][trans time=1000 method=crossfade][wt2][hide_chara_int]
[if exp="tf.scene_mode"]
	[jump storage="b_scene.ks" target=*back_from_SR]
[endif]
[fadeoutbgm time=2000]
[stopse_all]
[wait time=2000 canskip=false]
[eval exp="sf.gameclear = 1"]
[eval exp="sf.g_bad0392 = 1"]
[eval exp="sf.g_clear_300 = 1"]
[cancelskip]
[video visible=true left=0 top=0 width=1280 height=720]
[openvideo storage="badend.mpg"]
[playvideo]
[if exp="sf.bgmplay == 1"]
	
	[video volume=55]
[elsif exp="sf.bgmplay == 0"]
	[video volume=0]
[endif]
[wv canskip=true]
[wait2 time=1000]
[jump storage="title.ks"]
