*0620_TOP
[bgm storage="bgm08" time=100]
[backlay][bg storage="BG18"][trans time=500 method=crossfade][wt2]
[se buf=0 storage="seD003"]
[wait2 time=500]
[sysbt_meswin]
[backlay][sud_up_03_f31 layer=3 x="&sf.su_up_x[3]" y="&sf.su_up_y[0]"][trans time=150 method=crossfade][wt]
*7696|
[fc]
[y{“cz]
u‚Ü‚»‚Á‚ÕIv[pcms][endhact]
*7697|
[fc]
Inside the tent, when I doused Suda with the remaining ice water from[r]
the cooler box, he leapt up with a mysterious scream.[pcms]
*7698|
[fc]
[y{“cz]
"Aaaaah, over there! There's someone over there... No, stop... Ah,[r]
ah...? Huh, where is this...?"[pcms]
[backlay][sud_up_03_f07 layer=3 x="&sf.su_up_x[3]" y="&sf.su_up_y[0]"][trans time=150 method=crossfade][wt]
*7699|
[fc]
[y‰›z]
u{“ccc‚ ‚È‚½”æ‚ê‚Ä‚é‚Ì‚æv[pcms][endhact]
*7700|
[fc]
...I said that reflexively, but given the situation, that line isn't[r]
really a laughing matter.[pcms]
[backlay][chara_int]
[rir_lo_03_f09 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f07 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7701|
[fc]
[vo_ri s="riri0765"]
[y—œ—¢z]
"Suda, are you okay? For now, we're inside an empty tent nearby, so I[r]
think we haven't been found by them..."[pcms]
*7702|
[fc]
Luckily, when Riri and I dragged the unconscious Suda into the tent to[r]
take refuge, there was a cooler box filled with ice water.[pcms]
*7703|
[fc]
Thanks to that, Suda was awakened in a very peaceful manner.[pcms]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f05 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7704|
[fc]
[y{“cz]
"So, I was with that monster-like guy... Thanks, both of you. For[r]
carrying me all the way here."[pcms]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f01 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7705|
[fc]
[y‰›z]
"No, we should be the ones thanking you. Thanks to you, both Riri and[r]
I were saved."[pcms]
[backlay]
[rir_lo_03_f02 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f01 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7706|
[fc]
[vo_ri s="riri0766"]
[y—œ—¢z]
u‚»‚¤‚¾‚æA‚ ‚è‚ª‚Æ‚¤{“c‚Á‚¿v[pcms][endhact]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f01 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7707|
[fc]
For some reason, we ended up thanking each other. Well, it's certainly[r]
better than hurling insults at each other.[pcms]
*7708|
[fc]
[y‰›z]
"But why were you in a place like this? Weren't you sleeping in your[r]
room?"[pcms]
*7709|
[fc]
Suda's complexion is quite bad.[pcms]
*7710|
[fc]
Maybe his summer cold got worse... No, in this situation, it's natural[r]
for anyone's complexion to be poor without being sick.[pcms]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f07 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7711|
[fc]
[y{“cz]
"I ate too much curry and was so full that even when I went back to my[r]
room, my stomach still hurt, so I thought I'd walk around the running[r]
course to settle it."[pcms]
*7712|
[fc]
You were supposed to be resting...[pcms]
*7713|
[fc]
But thanks to that, we were able to meet here, so maybe I should be[r]
grateful for Suda's gluttony...?[pcms]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f08 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7714|
[fc]
[y{“cz]
"Then, I got caught up in this commotion and hurriedly fled into an[r]
empty tent nearby."[pcms]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f06 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7715|
[fc]
[y{“cz]
"After that, I watched the situation outside and managed to escape[r]
here while hiding."[pcms]
*7716|
[fc]
After hearing about Suda's situation, we briefly explained our own[r]
circumstances.[pcms]
*7717|
[fc]
At first, Suda was saying it was the same for him too, but as the[r]
story progressed, his face became grim and tense...[pcms]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f08 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7718|
[fc]
[y{“cz]
"Huh? You guys didn't run away!? If you had gone that far, you should[r]
have just fled towards the town!"[pcms]
[backlay]
[rir_lo_03_f10 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f05 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7719|
[fc]
[vo_ri s="riri0767"]
[y—œ—¢z]
"But Jun and Ashina-senpai are still at the center. That's why we have[r]
to go help them."[pcms]
*7720|
[fc]
[y‰›z]
ucc‚Á‚Ä‚±‚Æ‚¾v[pcms][endhact]
*7721|
[fc]
Riri's words made me nod. Alternately looking at us, Suda's face[r]
turned into one of utter disbelief.[pcms]
[backlay]
[rir_lo_03_f10 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f08 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7722|
[fc]
[y{“cz]
"It's impossible. You saw them too, right? I don't know why it turned[r]
out like this, but it's no small matter."[pcms]
*7723|
[fc]
Suda pressed on us. His exasperation gradually turned into concern,[r]
and his tone shifted to persuasion.[pcms]
[backlay]
[rir_lo_03_f10 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f06 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7724|
[fc]
[y{“cz]
"They won't die easily, and on top of that, they attack people and[r]
bite at them!"[pcms]
*7725|
[fc]
His voice grew rougher by the moment, and his worried face became more[r]
severe.[pcms]
[backlay]
[rir_lo_03_f10 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f04 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7726|
[fc]
[y{“cz]
"Listen... They're not human anymore! They're monsters! How are we[r]
supposed to deal with those things!!"[pcms]
[backlay]
[rir_lo_03_f08 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f04 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7727|
[fc]
[vo_ri s="riri0768"]
[y—œ—¢z]
u‚í‚ÁA‚¿‚å‚Ácc{“c‚Á‚¿Aº‚ÁAº‘å‚«‚¢‚Áv[pcms][endhact]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*7728|
[fc]
Riri quickly covered Suda's mouth and we all held our breath in[r]
silence.[pcms]
*7729|
[fc]
As if triggered by that action, Suda and I also held our breaths just[r]
as a voice that was neither a scream nor a groan approached from[r]
outside the tent along with footsteps.[pcms]
*7730|
[fc]
We continued to listen intently to the voice and footsteps without[r]
moving a muscle.[pcms]
*7731|
[fc]
In the time where my own heartbeat sounded unusually loud, the[r]
groaning and footsteps slowly moved away from us inside the tent.[pcms]
*7732|
[fc]
We kept our breaths held until we could no longer hear them at all,[r]
and when only screams and shouts echoed from afar, we finally let out[r]
a big sigh of relief.[pcms]
[backlay]
[rir_lo_03_f20 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f08 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7733|
[fc]
[y{“cz]
"Haa... Sorry, Riri-chan. But... it's impossible, I'm against it. Even[r]
Riri-chan can't handle them. We should hide in the forest and wait for[r]
help."[pcms]
*7734|
[fc]
I think Suda's opinion is correct. In fact, until a moment ago, I had[r]
the same opinion.[pcms]
*7735|
[fc]
But...[pcms]
*7736|
[fc]
[y‰›z]
u‚Å‚àAƒIƒ}ƒG‚Í‚³‚Á‚«‚â‚Á‚Â‚¯‚½‚¶‚á‚È‚¢‚©B—œ—¢‚Å‚à“G‚í‚È‚©‚Á‚½‚Ì‚Év[pcms][endhact]
[backlay]
[rir_lo_03_f20 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f10 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7737|
[fc]
[y{“cz]
u‚»‚ê‚Íccv[pcms][endhact]
*7738|
[fc]
I hesitated and my words trailed off.[pcms]
[backlay]
[rir_lo_03_f10 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f10 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7739|
[fc]
[vo_ri s="riri0769"]
[y—œ—¢z]
"Those guys seemed not to feel pain. But when their heads were[r]
attacked, they died normally..."[pcms]
[backlay]
[rir_lo_03_f10 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f05 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7740|
[fc]
[y{“cz]
uƒAƒCƒc‚çA“ª‚ªã“_‚È‚ñ‚¾‚æv[pcms][endhact]
*7741|
[fc]
[y{“cz]
"While hiding in the tent and watching outside, even if their limbs[r]
were torn off they moved normally, but if they fell and hit their[r]
heads hard they stopped moving."[pcms]
*7742|
[fc]
being impaled on stakes or having their heads smashed with rocks...[pcms]
*7743|
[fc]
Indeed, even earlier when they were stabbed with pegs and hit with[r]
stones they stopped moving. The head must definitely be their weak[r]
point.[pcms]
[backlay]
[rir_lo_03_f05 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f05 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7744|
[fc]
[vo_ri s="riri0770"]
[y—œ—¢z]
"If we know the enemy's weakness, we can deal with them. Even if the[r]
enemy is a monster."[pcms]
*7745|
[fc]
Clutching her fist and speaking with a strong tone, Riri looked[r]
incredibly reliable.[pcms]
*7746|
[fc]
It's not for nothing that she's been able to overcome opponents bigger[r]
than herself up until now.[pcms]
*7747|
[fc]
[y‰›z]
"The manager and Takahashi-chan are still inside. We have to save[r]
them. We need your keen observation skills."[pcms]
*7748|
[fc]
Even during practice, she would check our forms and always had a sharp[r]
eye for detail.[pcms]
*7749|
[fc]
That's why Suda was able to spot the monsters' weakness. If he comes[r]
with us, he'll be a great asset.[pcms]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f01 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7750|
[fc]
[y{“cz]
ucc‚í‚©‚Á‚½‚æA‚µ‚å‚¤‚ª‚È‚¢B‰´‚à•t‚«‡‚¤‚æv[pcms][endhact]
*7751|
[fc]
[y‰›z]
u‚ ‚è‚ª‚Æ‚¤A{“cv[pcms][endhact]
[backlay]
[rir_lo_03_f02 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f01 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7752|
[fc]
[vo_ri s="riri0771"]
[y—œ—¢z]
u{“c‚Á‚¿A‚ ‚è‚ª‚Æ‚¤v[pcms][endhact]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f02 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7753|
[fc]
[y{“cz]
"Seriously, I also... Once it's decided, let's gather some tools.[r]
Riri-chan is the only one who can face those guys barehanded."[pcms]
*7754|
[fc]
That's certainly true. I couldn't do anything with my bare hands[r]
earlier either.[pcms]
[stopse_all]
[sysbt_meswin clear]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
[wait2 time=500]
[backlay][bg storage="BG18"]
[sud_up_03_f05 layer=3 x="&sf.su_up_x[3]" y="&sf.su_up_y[0]"]
[trans time=500 method=crossfade][wt2]
[sysbt_meswin]
*7755|
[fc]
[y{“cz]
u‚Æ‚è‚ ‚¦‚¸A‚±‚ñ‚È‚à‚ñ‚©ccv[pcms][endhact]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*7756|
[fc]
We avoided being spotted by the monsters, moving from one empty tent[r]
to another, until we reached the tent closest to the ground--[pcms]
*7757|
[fc]
In our hands were tools that seemed reasonably useful.[pcms]
*7758|
[fc]
I brought as much as I could carry, but holding all this will just get[r]
in the way, so we need to select what to take with us.[pcms]
*7759|
[fc]
And so, what we picked out was...[pcms]
*7760|
[fc]
Two cell phones, skyrockets, a portable radio, an LED lantern.[pcms]
*7761|
[fc]
A few chemical lights, medicine and disinfectant, adhesive bandages, a[r]
first aid pouch, and ready-to-eat food like snacks.[pcms]
*7762|
[fc]
A cooler box filled with drinks, a flashlight, a water bottle, a[r]
lighter, oil, and so on.[pcms]
[backlay][rir_up_03_f04 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*7763|
[fc]
[vo_ri s="riri0772"]
[y—œ—¢z]
u‚à‚¤A‚È‚É‚æI‚±‚ÌƒLƒƒƒ“ƒvêI “ú–{“‚à’u‚¢‚Ä‚È‚¢‚ÌIHv[pcms][endhact]
*7764|
[fc]
[y‰›z]
ucc‚ ‚é‚í‚¯‚Ë‚¥‚¾‚ëccv[pcms][endhact]
[backlay][rir_up_03_f05 layer=3 x="&sf.ri_up_x[3]" y="&sf.ri_up_y[0]"][trans time=150 method=crossfade][wt]
*7765|
[fc]
[vo_ri s="riri0773"]
[y—œ—¢z]
ucc‰›AƒAƒ“ƒ^AÀ‚Í•Ğ˜r‚É“‚ğd‚ñ‚Å‚½‚èccv[pcms][endhact]
*7766|
[fc]
[y‰›z]
"I'm not... Even if I did, I don't have the strength to decapitate a[r]
giant crocodile with a 30 cm blade... It won't be of much use..."[pcms]
[backlay][chara_int]
[rir_lo_03_f05 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f10 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7767|
[fc]
[y{“cz]
"...Yeah, I thought so... I was a bit hopeful though... That you would[r]
reveal a hidden blade..."[pcms]
*7768|
[fc]
[y‰›z]
u‚¦‚ÁIHv[pcms][endhact]
[backlay]
[rir_lo_03_g01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f10 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7769|
[fc]
[vo_ri s="riri0774"]
[y—œ—¢z]
u‚Ë[Hv[pcms][endhact]
*7770|
[fc]
[y‰›z]
ucc‚ÈA‚È‚ñ‚©Šú‘Ò‚ğ— Ø‚Á‚Ä‚µ‚Ü‚Á‚½cc‚·‚Ü‚Ë‚¥A‚·‚Ü‚Ë‚¥ccv[pcms][endhact]
[backlay][chara_int][trans time=150 method=crossfade][wt]
*7771|
[fc]
We decided to divide the bulky items among the three of us and carry[r]
them in the shoulder bags we had gathered together.[pcms]
*7772|
[fc]
While doing that, I listened to Suda's observations about the[r]
monsters' behavior patterns.[pcms]
*7773|
[fc]
They move straight towards their target, whether it's people or food,[r]
in an overly direct manner. They don't care about obstacles.[pcms]
*7774|
[fc]
They don't seem very smart. I think they're easier to trick than[r]
normal humans.[pcms]
*7775|
[fc]
That was Suda's observation of their movements.[pcms]
*7776|
[fc]
Knowing how they behave gave us quite a sense of security and sped up[r]
our work.[pcms]
*7777|
[fc]
We took drinks out of the cooler box and put them into bags, checked[r]
and registered each other's phone numbers by looking at the settings.[pcms]
*7778|
[fc]
The cell phones could be used in various ways, like luring them with[r]
the ringtone.[pcms]
*7779|
[fc]
Come to think of it... I suddenly realized and took out my own cell[r]
phone.[pcms]
*7780|
[fc]
There were tons of emails. From my parents and friends, and also from[r]
Ken'go.[pcms]
*7781|
[fc]
If they're coming through, that means the communication lines are[r]
still up.[pcms]
*7782|
[fc]
Feeling relieved that communication was still possible, I opened the[r]
emails.[pcms]
*7783|
[fc]
All of them were concerned about whether I was safe or not.[pcms]
*7784|
[fc]
I replied just in case, but the line was incredibly slow and responses[r]
were not coming through quickly.[pcms]
*7785|
[fc]
I tried calling as well, but there was a line restriction on calls.[pcms]
*7786|
[fc]
Thinking that communication apps might be better, I checked them and[r]
found messages there too.[pcms]
*7787|
[fc]
When I sent a message to the swimming club's group line asking if[r]
everyone was safe, I got an immediate response.[pcms]
*7788|
[fc]
The replies from some who had returned earlier indicated that the town[r]
of Egaikan was in quite a state of chaos, with everyone staying home[r]
and waiting for the situation to settle down.[pcms]
*7789|
[fc]
In the city, there were not only riots but also fires breaking out,[r]
and some people were following police instructions to evacuate with[r]
their families to shelters and join vigilante groups to protect[r]
themselves from mobs.[pcms]
*7790|
[fc]
Riri also contacted her track and field club group line and found out[r]
that they were in a similar situation.[pcms]
*7791|
[fc]
Riri's parents were safe and had moved to a shelter where they were[r]
actively involved in measures against the mobs; several people had[r]
witnessed this and sent photos as well.[pcms]
*7792|
[fc]
That's good... I felt relieved too, but Riri was so relieved she[r]
almost cried.[pcms]
*7793|
[fc]
We took a photo of the three of us and sent it to each of our families[r]
to reassure them.[pcms]
*7794|
[fc]
At the same time, I sent a photo to the group line to let everyone[r]
know we were safe.[pcms]
*7795|
[fc]
However, only Ken'go is not good with these kinds of apps and hasn't[r]
created a group, so I have no choice but to contact him by email.[pcms]
*7796|
[fc]
Since communication conditions are better with apps, I should have[r]
forced him to use it...[pcms]
*7797|
[fc]
I briefly explained the situation at the center on the group line,[r]
sent out my prayers for everyone's safety, and put away my phone.[pcms]
*7798|
[fc]
We must avoid wasting it. I have to constantly be mindful of the[r]
battery level.[pcms]
*7799|
[fc]
Once that task was finished, it was time to look for weapons.[pcms]
*7800|
[fc]
Barbecue skewers. Two wooden bats. A small, portable shovel.[pcms]
*7801|
[fc]
These seem to be the only things that could be used as weapons.[pcms]
*7802|
[fc]
In a situation like this, surely...[pcms]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f05 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7803|
[fc]
[y{“cz]
uŠÈˆÕƒVƒƒƒxƒ‹‚Í‚æ‚¹B‹ğÒ‚Ì‘I‘ğA‘‰‚¹‚½l‚¦ccv[pcms][endhact]
*7804|
[fc]
[y‰›z]
u‚È‚ñcc‚¾‚Æccv[pcms][endhact]
*7805|
[fc]
Suda grabbed my hand as it reached for the shovel and pushed it[r]
towards the bat instead.[pcms]
*7806|
[fc]
[y{“cz]
"A small, collapsible shovel will break easily. A normal, large shovel[r]
would be a versatile weapon, though."[pcms]
[backlay]
[rir_lo_03_f08 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f05 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7807|
[fc]
[vo_ri s="riri0775"]
[y—œ—¢z]
"Ah! I've read about it in manga and books! The best would be one[r]
that's big and sturdy, or one with a special shape that combines with[r]
an axe..."[pcms]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f07 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7808|
[fc]
[y{“cz]
uƒ›ƒgƒ~[‚­‚ñccv[pcms][endhact]
*7809|
[fc]
[y‰›z]
u‚»A‚»‚¤‚È‚Ì‚©ccv[pcms][endhact]
*7810|
[fc]
He's absolutely right. I was about to put myself in danger with half-[r]
baked equipment that's just trendy...[pcms]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f02 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7811|
[fc]
[y{“cz]
u‚â‚Í‚èA“ª‘_‚¢‚È‚çƒRƒCƒc‚¾ccƒLƒ“ƒOEƒIƒuEˆê”Êl•‘•AƒoƒbƒgIv[pcms][endhact]
*7812|
[fc]
[y{“cz]
"It's durable and easy to handle, and it can knock someone out in one[r]
hit, so it's kind of... merciful."[pcms]
*7813|
[fc]
[y‰›z]
u‚È‚ñ‚¾‚»‚è‚áv[pcms][endhact]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f07 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7814|
[fc]
[y{“cz]
"No... If I were in that state, I'd prefer to be knocked out with a[r]
bat in one hit rather than being cut or stabbed."[pcms]
*7815|
[fc]
I don't really understand, but I'd rather not experience either[r]
option...[pcms]
*7816|
[fc]
In any case, we've decided on bats as our weapons.[pcms]
[backlay]
[rir_lo_03_f07 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f07 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7817|
[fc]
[vo_ri s="riri0776"]
[y—œ—¢z]
"Since it's small, why not take the shovel too? It won't be in the way[r]
if you disassemble it."[pcms]
*7818|
[fc]
[y‰›z]
u‚»‚¤‚¾‚ÈB‚â‚Á‚Ï‚èƒƒCƒ“•Ší‚ÆƒTƒu•Ší‚ª•K—v‚¾‚æ‚Èv[pcms][endhact]
*7819|
[fc]
Accepting Riri's suggestion, we decided to take the shovel as well.[pcms]
*7820|
[fc]
Riri chose the skewers. Maybe she prefers something shorter since she[r]
mainly practices karate.[pcms]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f01 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7821|
[fc]
[vo_ri s="riri0777"]
[y—œ—¢z]
u“¯‚¶“Ë‚­‚È‚çA‚Ù‚ñ‚Æ‚ÍŠÛ‘¾‚ª‚ ‚ê‚Îˆê”Ô‚¾‚¯‚Ç‚Ëv[pcms][endhact]
*7822|
[fc]
[y‰›z]
u‚¢‚âAd‚½‚­‚Ä‘å•Ï‚¾‚¼A‚½‚Ô‚ñccv[pcms][endhact]
*7823|
[fc]
As Riri thrusts the skewer out several times while saying this, she[r]
seems to have completely returned to her usual self.[pcms]
*7824|
[fc]
In contrast to Riri, this guy is getting unusually excited.[pcms]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f30 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7825|
[fc]
[y{“cz]
"Heh heh heh, with this I'll crack their skulls open and splatter[r]
their brains on the back screen in a triple play...!"[pcms]
[backlay]
[rir_lo_03_f08 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f30 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7826|
[fc]
[vo_ri s="riri0778"]
[y—œ—¢z]
"Hold on a sec, Suda-chi, what are you going to do being so[r]
bloodthirsty... wait, huh? Suda-chi, you're not coughing."[pcms]
*7827|
[fc]
[y‰›z]
u‚»‚¤‚¢‚¦‚Î‚»‚¤‚¾‚ÈB‚È‚ñ‚©–ò‚Å‚àˆù‚ñ‚¾‚Ì‚©Hv[pcms][endhact]
*7828|
[fc]
I realized when she mentioned it. He hasn't been coughing at all[r]
lately.[pcms]
*7829|
[fc]
It doesn't seem possible that he could recover in such a short time.[pcms]
[backlay]
[rir_lo_03_f01 layer=4 x="&sf.ri_lo_x[4]" y="&sf.ri_lo_y[0]"]
[sud_lo_03_f01 layer=5 x="&sf.su_lo_x[5]" y="&sf.su_lo_y[0]"][trans time=150 method=crossfade][wt]
*7830|
[fc]
[y{“cz]
"It must be that. The effect of the spices in the curry and a special[r]
situation has awakened his body and spirit."[pcms]
*7831|
[fc]
That's ridiculous.[pcms]
*7832|
[fc]
His excitement has gotten so high that it seems like even his[r]
stupidity has been boosted.[pcms]
*7833|
[fc]
[y‰›z]
"Anyway, if we're ready, let's go. We don't have time to dawdle."[pcms]
*7834|
[fc]
I put my hand on the tent entrance and opened it slightly to check[r]
outside.[pcms]
*7835|
[fc]
Alright, looks like we can go...[pcms]
*7836|
[fc]
[y‰›z]
u‚¢‚­‚¼A“ñl‚Æ‚àccIv[pcms][endhact]
[stopse_all]
[sysbt_meswin clear]
[backlay][black_toplayer][trans time=501 method=crossfade][wt2][hide_chara_int]
[fadeoutbgm time=500]
[wait2 time=500]
[jump storage="0630.ks"]
