*SRP21
[eval exp="sf.SRP21 = 1"]
[if exp="tf.scene_mode"]
	
	[bgm storage="bgm07" time=100 cond="tf.all_play == 0"]
	[jump target=*scene_start]
[endif]
[sysbt_meswin clear]
[backlay][black_toplayer][trans time=500 method=crossfade][wt2][hide_chara_int]
*scene_start
[backlay][evcg storage="EV28_01" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
[wait2 time=500]
[sysbt_meswin]
*10205|
[fc]
Risato did as she was told, pressing her hands against the wall and[r]
presenting her behind, but inwardly she wasn't feeling good about it.[pcms]
*10206|
[fc]
Why does this guy have to act so high and mighty? I just want to feel[r]
good.[pcms]
*10207|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
u‚æ[‚µA‚æ‚µ‚æ‚µB‚¨‚Ü‚¦‚Ì‚¢‚¢‚Æ‚±‚ë‚ÍƒPƒc‚¾‚¯‚¾‚©‚ç‚Èv[pcms][endhact]
*10208|
[fc]
The club member started to stroke the sharply raised behind with a[r]
grin, but his touch was far from a caress, rough and careless.[pcms]
*10209|
[fc]
[vo_ri s="riri0545"]
[y—œ—¢z]
u‚Ş‚©‚Â‚­‚È‚ŸccB‚»‚è‚áA‚ ‚½‚µ‚Í‚¨‚Á‚Ï‚¢‚Æ‚©T‚¦‚ß‚¾‚¯‚Ç‚³ccv[pcms][endhact]
*10210|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"Hah, modest? It's that kind of half-hearted attitude that's the[r]
worst. But well, I'll give you a passing grade."[pcms]
*10211|
[fc]
He began a rough caress as if grabbing her buttocks, laughing[r]
scornfully.[pcms]
*10212|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"Hey, it's your fault, you know. You're always shaking that ass when[r]
you run, and it's made me totally into butts. You've been tempting me[r]
with this all along, haven't you?"[pcms]
*10213|
[fc]
Risato's mood plummeted with his entangling words, but the man himself[r]
continued his tirade, oblivious.[pcms]
*10214|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"I'm praising you here, you know? Everyone has at least one good[r]
point. Heh, even smeared in semen, an ass is an ass. I'll make you[r]
feel good."[pcms]
*10215|
[fc]
Risato didn't answer. She disliked everything about the man's behavior[r]
and speech.[pcms]
*10216|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"What's the matter with you, huh? Are you angry!? Pfft! Acting all[r]
high and mighty after getting wet and moaning, don't get all stuck-up[r]
now!"[pcms]
[backlay][evcg storage="EV28_02" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10217|
[fc]
With no reaction from Risato, the club member bared his teeth and[r]
pressed his fully erect penis against her twitching hole.[pcms]
*10218|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"You want it, don't you, Kiyohara!? You're sticking out your ass just[r]
like you're told, you want me to thrust into you quickly! Hey, say[r]
something!"[pcms]
*10219|
[fc]
But Risato didn't answer. Part of it was out of anger, but she also[r]
realized she was shivering with excitement from the man's rough words.[pcms]
[backlay][evcg storage="EV28_03" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10220|
[fc]
Why does my pussy start to heat up? Why don't I kick this guy away...?[pcms]
*10221|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"What's the matter, Kiyohara? You're glaring but your face is red.[r]
Hehehe, in the end, you're just a fucking bitch, huh?"[pcms]
*10222|
[fc]
Noticing Risato's reaction, he twisted his face into a grin and[r]
mercilessly slammed his penis through the gap of the rolled-up crotch[r]
cloth.[pcms]
[se buf=0 storage="se_sex01"]
[evcg”’ƒtƒ‰ storage="EV28_04" layer=0 page=back visible=true left=0 top=0]
*10223|
[fc]
[vo_ri s="riri0546"]
[y—œ—¢z]
u‚ñcc‚Á‚Á‚ÁI@‚«‚á‚¤‚¤‚¤‚¤‚Á‚Á‚ÁIII@‚­‚Ó‚ÁA‚­‚§‚¨‚§‚Á‚ÁIIv[pcms][endhact]
[se buf=1 storage="se_sex02" loop=true]
*10223a|
[fc]
The club member laughed at the cry of joy that easily escaped her[r]
lips, and a sense of shame spread through Risato's chest.[pcms]
*10224|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"Ohh! I finally got Kiyohara's ass! Man, I've always wanted to fuck[r]
you from behind!"[pcms]
*10225|
[fc]
The club member began a rough thrusting as if overcome with emotion.[pcms]
*10226|
[fc]
With each movement of the penis, the frothy mix of fluids flowed down,[r]
further exciting him.[pcms]
*10227|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"Oh man, this is the best! To think I could graduate from virginity[r]
with Kiyohara! Hey hey, you like it too, right? If it feels good, say[r]
so!!"[pcms]
*10228|
[fc]
While furiously thrusting his hips, he tried to draw words from[r]
Risato. But she said nothing, only letting out uncontrollable moans.[pcms]
*10229|
[fc]
[vo_ri s="riri0547"]
[y—œ—¢z]
u‚Ğ‚®‚ÁA‚Ícc‚®‚¤‚¤‚ÁI@‚ñ‚®‚ÁA‚ñ‚Ó‚£‚£‚Á‚ÁI@‚­‚Ğ‚¡‚¡cc‚Áv[pcms][endhact]
*10230|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"Hey! I can tell you're feeling it even if you're silent! There's a[r]
squelching sound coming from this bitch hole!!"[pcms]
*10231|
[fc]
[vo_ri s="riri0548"]
[y—œ—¢z]
u‚ñ‚ÁA‚­‚¤‚¤‚¤‚ÁA‚Ícc‚¤‚ñ‚ÁB‚­cc‚ÁA‚ñ‚¤‚¤‚¤‚¤cc‚Á‚Áv[pcms][endhact]
*10232|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"Damn it! You hate me that much!? But hey, you're getting fucked in[r]
the ass by a guy you hate and feeling it! You perverted bitch!!"[pcms]
*10233|
[fc]
[vo_ri s="riri0549"]
[y—œ—¢z]
u‚­‚¤‚¤‚¤cc‚Á‚ÁII@‚ñ‚®‚ÁA‚ñ‚ÁA‚Ğ‚¤‚ÁI@‚«‚á‚¤‚¤‚¤‚¤‚Á‚ÁIIv[pcms][endhact]
*10233a|
[fc]
The sight of Risato continuing to resist drove him into a fierce rage.[r]
That rage transformed into the movement of his hips and the verbal[r]
abuse he hurled at her.[pcms]
*10234|
[fc]
Knowing what would happen, she still didn't respond. Unconsciously[r]
raising her ass, she was getting into a position to accept him.[pcms]
*10235|
[fc]
[vo_ri s="riri0550"]
[y—œ—¢z]
u‚¨‚Ğ‚ÁA‚¨‚ÁA‚¨‚¨‚¨‚Á‚ÁI@‚ñ‚ÁA‚Ğ‚®‚ÁI@‚ñ‚¢‚¡‚¡‚ÁI@‚ñ‚ñ‚ÁIv[pcms][endhact]
*10235a|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
u‚¾‚Á‚½‚çA–³—–î—‚É‚Å‚à“š‚¦‚³‚¹‚Ä‚â‚é‚æccI@‚¨‚ç‚¨‚ç‚¨‚ç‚ŸIIv[pcms][endhact]
[se buf=1 storage="se_sex03" loop=true]
*10235b|
[fc]
The moment the enraged club member thrust violently as if it were an[r]
act of violence, Risato trembled with a pleasure that numbed her mind.[pcms]
*10236|
[fc]
[vo_ri s="riri0551"]
[y—œ—¢z]
"Ahhee!! Ohh, ohh! Nooo!! I'm going to cum... I'm cumming!!"[pcms]
*10237|
[fc]
It was humiliating for her, but once she started speaking, she[r]
couldn't stop. Sweet moans and pleading voices spilled out[r]
immediately.[pcms]
*10238|
[fc]
[vo_ri s="riri0552"]
[y—œ—¢z]
"It's frustrating but it feels good! Nngh, nghhô Being raped in the[r]
ass so hard, I'm cumming... I'm cumming!!"[pcms]
*10239|
[fc]
With her cries bursting forth, the club member's excitement reached[r]
its peak. He grabbed her buttocks and began thrusting his hips with[r]
even more ferocity...[pcms]
*10240|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"Kuu---!! Yeah, cum! I'm cumming too! I'm going to shoot it in![r]
Ohhh!!"[pcms]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[Ë¸ƒtƒ‰A]
[backlay][evcg storage="EV28_05" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[Ë¸ƒtƒ‰B]
*10241|
[fc]
In her tight vagina that painfully squeezed him, he released all his[r]
feelings. It struck Risato's precious place and exploded into[r]
tremendous pleasure.[pcms]
*10242|
[fc]
[vo_ri s="riri0553"]
[y—œ—¢z]
u‚ñ‚ÁA‚Ù‚¨‚¨‚§‚¨‚¨‚§‚Á‚ÁII@ƒCƒN‚ÁAƒCƒO‚£‚¤‚£‚¤‚£‚£‚£‚ÁIIIv[pcms][endhact]
*10243|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
u‚­‚ÁA‚¤‚¤‚¤‚¤cc‚ÁI@‚¨‚çA‚±‚Á‚¿‚É‚à‚­‚ê‚Ä‚â‚éIIv[pcms][endhact]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[Ë¸ƒtƒ‰A]
[backlay][evcg storage="EV28_06" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[Ë¸ƒtƒ‰B]
*10244|
[fc]
While driven by the urge to pour everything inside her, he pulled out[r]
his penis and began to splatter the rest on her ass.[pcms]
*10245|
[fc]
[vo_ri s="riri0554"]
[y—œ—¢z]
"Kuh...iiii!! My ass... my ass is getting hot... Higuhh, it's hot...[r]
it's so hot... nkyuuuu...!"[pcms]
*10246|
[fc]
Shivering under the downpour of hot rain, Risato regretted having come[r]
in such a pathetic way.[pcms]
[backlay][evcg storage="EV28_07" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10247|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"Nn... phew. Kekeke, why are you glaring? You enjoyed it too, didn't[r]
you Kiyohara? Kekekekeke!"[pcms]
*10248|
[fc]
Even as she glared at the laughing club member, Risato couldn't help[r]
but relax her lips with the hot excitement. Despite being annoyed with[r]
him, her body had felt good.[pcms]
*10249|
[fc]
And she was surprised to find herself thinking that maybe this wasn't[r]
so bad after all.[pcms]
*10250|
[fc]
[nsy]—¤ã•”‚Ìæ”y[znse]
u‚³‚ÄAŸ‚Í–l‚Ì”Ô‚Å‚·BƒLƒ~A‚³‚Á‚³‚ÆêŠ‚ğ‹ó‚¯‚È‚³‚¢v[pcms][endhact]
*10251|
[fc]
Risato's ears caught a new voice just as she was about to be driven by[r]
a bewitching impulse. It was the voice of a senior who had watched her[r]
practice several times before.[pcms]
*10252|
[fc]
[vo_ri s="riri0555"]
[y—œ—¢z]
"Is it my turn next? Umm, please don't do anything too unpleasant...[r]
Kyaa!!"[pcms]
[backlay][evcg storage="EV28_08" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10253|
[fc]
The senior, smiling cheerfully, pulled down her shorts and then firmly[r]
grasped the panties that were biting into her buttocks.[pcms]
[backlay][evcg storage="EV28_09" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10254|
[fc]
[nsy]—¤ã•”‚Ìæ”y[znse]
"Ah, sorry about that. I don't want to touch anything dirty, you see.[r]
But... hehe, are you wearing such erotic underwear?"[pcms]
*10255|
[fc]
Although his tone was polite, there was a clear mockery behind his[r]
words. Even as she sensed this, Risato continued to speak amiably.[pcms]
*10256|
[fc]
[vo_ri s="riri0556"]
[y—œ—¢z]
"Th-that's not true. More importantly, could you please not say such[r]
things...?"[pcms]
*10257|
[fc]
[nsy]—¤ã•”‚Ìæ”y[znse]
"Such things? Like how you wear erotic underwear under your gear and[r]
get your pussy wet from our gazes?"[pcms]
*10258|
[fc]
The senior was smiling refreshingly, but his eyes were swirling with a[r]
deep madness. In that moment, Risato realized that he was the same[r]
kind.[pcms]
*10259|
[fc]
[nsy]—¤ã•”‚Ìæ”y[znse]
"What's with that defiant look? You've always been like that. Even[r]
though I've been teaching you, you still talk back so insolently."[pcms]
*10260|
[fc]
So this is punishment, he continued... and then he thrust his hips in[r]
one swift motion.[pcms]
[se buf=0 storage="se_sex01"]
[evcg”’ƒtƒ‰ storage="EV28_10" layer=0 page=back visible=true left=0 top=0]
*10261|
[fc]
[vo_ri s="riri0557"]
[y—œ—¢z]
"Kyahiiiiii!! Kuh, it's digging in!! Senpai, suddenly like that,[r]
nguuuu!!"[pcms]
[se buf=1 storage="se_sex03" loop=true]
*10262|
[fc]
[nsy]—¤ã•”‚Ìæ”y[znse]
"Kuh... what a nice pussy! No wonder you tempt us...! It's warm and,[r]
kuh, way tighter than his... You're too lewd!"[pcms]
*10263|
[fc]
Revealing his true nature, the senior began to verbally abuse Risato[r]
while synchronizing with the assault on her vaginal opening.[pcms]
*10264|
[fc]
[nsy]—¤ã•”‚Ìæ”y[znse]
"Kuhuhu, you really have a nice ass! Your thighs and legs are[r]
irresistible too! But you're lacking in the chest department. It'd be[r]
better if you had as much as Ashina!"[pcms]
*10265|
[fc]
While showering her with such insults, the senior roughly kneaded her[r]
breasts. It was an act as if he was dealing with a doll, ignoring her[r]
feelings completely.[pcms]
[backlay][evcg storage="EV28_11" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10266|
[fc]
[vo_ri s="riri0558"]
[y—œ—¢z]
u‚­‚¤cc‚Á‚ÁI@ƒqƒh‚¢ccƒbI@‹C‚É‚µ‚Ä‚é‚Ì‚ÉIv[pcms][endhact]
*10267|
[fc]
[nsy]—¤ã•”‚Ìæ”y[znse]
"Hehehe, so you were concerned about that. But hey, it's your fault.[r]
For glaring at me like that... Yo!"[pcms]
[backlay][evcg storage="EV28_13" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10268|
[fc]
[vo_ri s="riri0559"]
[y—œ—¢z]
u‚Ó‚®‚£ƒbI@‚ñ‚ÁA‚ñ‚Ö‚ÁA‚ñ‚¨‚§‚¨‚¨[[[‚ÁIIv[pcms][endhact]
*10269|
[fc]
Penetrated even deeper, Risato's eyes bulged as she let out a roar.[r]
Such a shameful sight only accelerated his excitement.[pcms]
*10270|
[fc]
[nsy]—¤ã•”‚Ìæ”y[znse]
"Kuhuhu, still glaring at me? You're really something, Tiger Lily,[r]
huh? How many people have you saved with that karate of yours, huh?"[pcms]
*10271|
[fc]
[nsy]—¤ã•”‚Ìæ”y[znse]
"I hate that attitude of yours. Getting all full of yourself!! But[r]
hey, it's been my dream to thoroughly fuck a strong-willed woman like[r]
you!"[pcms]
*10272|
[fc]
While exposing his vulgar nature, the senior dug into Risato's hole[r]
and raised a voice of pleasure at the sensation of the hot flesh folds[r]
entwining around him.[pcms]
[backlay][evcg storage="EV28_12" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10273|
[fc]
[vo_ri s="riri0560"]
[y—œ—¢z]
"Hagu, haguuu... You're the worst... the worst!! Kuh, kuunnn,[r]
fuguuu... But... this!!"[pcms]
*10274|
[fc]
[nsy]—¤ã•”‚Ìæ”y[znse]
"What's this, holding back your moans? Come on, moan nicely for me![r]
I'll thrust even more! Here, this is what you like!!"[pcms]
*10275|
[fc]
[vo_ri s="riri0561"]
[y—œ—¢z]
"Kuh, kuunnn! I refuse... I said nooo, nnh, kuunnn... I refuse[r]
that...! Ah, kuh, kuuuun!!"[pcms]
*10276|
[fc]
Risato desperately tried to endure the pleasure, but what overflowed[r]
unstoppably could not be contained. Drool and moans leaked out[r]
together, doubling the pleasure.[pcms]
*10277|
[fc]
[nsy]—¤ã•”‚Ìæ”y[znse]
"Kuhuhu, you've become completely soaked. Tiger Lily-sama has turned[r]
into just a lewd cat! Kuhuhuhu!!"[pcms]
[backlay][evcg storage="EV28_13" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10278|
[fc]
[vo_ri s="riri0562"]
[y—œ—¢z]
"That's not... trueee. Hagu, nguuuu... I'm not... a lewd cat...[r]
kuhin!? Ah, aguuu...!"[pcms]
*10279|
[fc]
Now even the verbal abuse had become something that stoked Risato's[r]
pleasure. With each insult, her body throbbed and the depths of her[r]
vagina quivered with joy.[pcms]
[backlay][evcg storage="EV28_14" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10280|
[fc]
[vo_ri s="riri0563"]
[y—œ—¢z]
"Hih... this is... no... it's different... it's not like this! Why am[r]
I... becoming so strange... ah, ahhh!!"[pcms]
*10280a|
[fc]
[nsy]—¤ã•”‚Ìæ”y[znse]
u‚­‚Ğ‚Ğ‚ÁI@‚»‚ë‚»‚ëƒVƒ‚¾I@ƒGƒ‚¢ƒƒX”L‚ÉƒvƒŒƒ[ƒ“ƒg‚¾‚ ‚ IIv[pcms][endhact]
*10281|
[fc]
[vo_ri s="riri0564"]
[y—œ—¢z]
"No! No no no no! This is weird!! Nooooo!!"[pcms]
*10282|
[fc]
He twisted his hips in accordance with his surging impulses and began[r]
to fiercely toy with the soft spot that his glans bumped against.[pcms]
*10283|
[fc]
[vo_ri s="riri0565"]
[y—œ—¢z]
"Nnaaaaa!! Good, it feels so good!! Oohh, oguuhh, agiiihh! I'm[r]
cummingggg!!"[pcms]
*10284|
[fc]
The moment an incredible pleasure greater than ever before struck her[r]
head like a thick spear, Risato was climaxing with her tongue sticking[r]
out.[pcms]
*10285|
[fc]
But it didn't stop at once; it pierced through her head over and over[r]
again.[pcms]
*10286|
[fc]
[vo_ri s="riri0566"]
[y—œ—¢z]
"Ugiiihh! I'm cummingggg! It's too muchhhhh!! Nguhh! It's too[r]
muchhhhh!!"[pcms]
*10287|
[fc]
[nsy]—¤ã•”‚Ìæ”y[znse]
u‚­‚Ğ‚Ğ‚Ğ‚ÁI@‚¨‚çAƒvƒŒƒ[ƒ“ƒg‚¾‚ŸI@—L‚è“ï‚­ó‚¯‚Æ‚êIIv[pcms][endhact]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[Ë¸ƒtƒ‰A]
[backlay][evcg storage="EV28_15" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[Ë¸ƒtƒ‰B]
*10288|
[fc]
[vo_ri s="riri0567"]
[y—œ—¢z]
"Aoooonnnn!! Semen!! Ahh, ahhh! It's spurting right into my good[r]
spot... I'm cummingggg!!"[pcms]
[backlay][evcg storage="EV28_16" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10289|
[fc]
In rapid succession of climaxes added to the impact of ejaculation,[r]
Risato kept screaming in half-madness. She was caught in a whirlpool[r]
of pleasure from which there was no return.[pcms]
[backlay][evcg storage="EV28_17" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10290|
[fc]
[nsy]—¤ã•”‚Ìæ”y[znse]
"Kuh, kuhuhu. You've got quite the face now, you lewd kitty. Hey, next[r]
guy come on! Don't let this bitch rest!!"[pcms]
[backlay][evcg storage="EV28_18" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10291|
[fc]
At the senior's call, one of the club members leaped out of the circle[r]
and pounced on Risato's ass with drool-worthy eagerness.[pcms]
*10292|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
u‚¤‚í‚í‚ícc‚ÁI@‚±‚ê‚ª´Œ´‚Ì¶Kcc¶ƒ}ƒ“ƒR‚È‚ñ‚¾‚ cc‚ÁIv[pcms][endhact]
*10293|
[fc]
With cheeks flushed red with freckles, he began to caress and stroke[r]
her buttocks as if he were petting a cat.[pcms]
*10294|
[fc]
[vo_ri s="riri0568"]
[y—œ—¢z]
"Ah... hiinnn. You're... Kenji's... friend... right? Ahh, ahaha...[r]
ahah! This is kind of funny..."[pcms]
*10295|
[fc]
Her consciousness was nearly blown away by the repeated climaxes she[r]
had suffered, but she realized that the one caressing her ass was her[r]
lover's classmate.[pcms]
*10296|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"Yeah, but... it's fine, isn't it? Ugh, such erotic underwear too! Was[r]
Daichi always massaging an ass like this...!"[pcms]
*10297|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"But maybe, he never even touched her ass. Because, because, they[r]
never had sex, right?!"[pcms]
*10298|
[fc]
Without waiting for Risato's answer, the classmate rambled on and[r]
pressed his erect penis against her melted hole.[pcms]
*10299|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"It's okay, right? You're not a virgin anymore, and who cares about[r]
Daichi? I want you to take my virginity, Kiyohara-san!"[pcms]
*10300|
[fc]
[vo_ri s="riri0569"]
[y—œ—¢z]
"Huh...? It's okay... I'll take it with my pussy. I think Kenji[r]
would... want me to do that too..."[pcms]
*10301|
[fc]
A fleeting image of her lover's smiling face crossed her fuzzy mind,[r]
but it quickly dissolved into a red mist.[pcms]
*10302|
[fc]
What remained was an endlessly expanding desire.[pcms]
*10303|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
u‚ A‚ ‚è‚ª‚Æ‚¤II@‚»‚ê‚¶‚á“ü‚ê‚é‚æcccc‚­‚¤‚¤‚¤‚ÁIIv[pcms][endhact]
[se buf=0 storage="se_sex01"]
[evcg”’ƒtƒ‰ storage="EV28_19" layer=0 page=back visible=true left=0 top=0]
*10304|
[fc]
[vo_ri s="riri0570"]
[y—œ—¢z]
u‚ñcc‚Ó‚ ‚ ‚ ‚ cc‚ÁB‚Ü‚½cc“ü‚Á‚Ä‚«‚½‚ ccB‚­‚Ó‚¤‚¤‚¤ccv[pcms][endhact]
[se buf=1 storage="se_sex03" loop=true]
*10305|
[fc]
The thoroughly loosened hole easily accepted the classmate, beginning[r]
to pour in a pleasure too stimulating for a virgin.[pcms]
*10306|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"Ugh, it feels so good, Kiyohara-san... Why didn't Daichi do this...[r]
it feels so amazing..."[pcms]
*10307|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"Hey... hey, you haven't even given a blowjob? Didn't you like[r]
Daichi?"[pcms]
*10308|
[fc]
Once he had thrust inside her, his possessiveness surged. While[r]
trembling with the heat of their entwined flesh, he threw an[r]
impertinent question at Risato.[pcms]
[backlay][evcg storage="EV28_20" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10309|
[fc]
[vo_ri s="riri0571"]
[y—œ—¢z]
"I liked him... That's why... before the training camp... I wanted to[r]
do it, ahn, he always talked about Megumi... I wanted to give a[r]
blowjob too..."[pcms]
*10310|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"I see, Daichi is such a fool. Not using such a pleasurable hole. Hey,[r]
if you had done it... would you have let him cum inside?"[pcms]
[backlay][evcg storage="EV28_21" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10311|
[fc]
[vo_ri s="riri0572"]
[y—œ—¢z]
"Haun! Maybe, I might have let him... no condoms, but I liked Kenji so[r]
much... mmm, I definitely would have wanted him to cum inside... ah!"[pcms]
*10312|
[fc]
While answering the runaway questions, Risato felt her chest heat up.[r]
After this was over, she would be desperate to have sex with Kenji.[pcms]
*10313|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
u‚Ó‚¤‚ñA‘Å–î‚Ì¸‰t—~‚µ‚¢‚ñ‚¾B‚Ç‚Ì‚®‚ç‚¢—~‚µ‚¢‚Ì‚©A‹³‚¦‚Ä‚æv[pcms][endhact]
[backlay][evcg storage="EV28_22" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10314|
[fc]
[vo_ri s="riri0573"]
[y—œ—¢z]
"I can't say that out loud. I want it so badly, so very badly! I want[r]
to do it with Kenji, I want Kenji's cock, Kenji's semen!!"[pcms]
*10315|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"Kuuuh! Then I'll cum inside you instead!! I'll give you lots...[r]
instead of Daichi!!"[pcms]
*10316|
[fc]
He must have been close to his limit. The classmate trembled his hips[r]
and without being able to hold back, he ejaculated.[pcms]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[Ë¸ƒtƒ‰A]
[backlay][evcg storage="EV28_23" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[Ë¸ƒtƒ‰B]
*10317|
[fc]
[nsy]—¤ã•”‚Ì•”ˆõ[znse]
"Sorry... Daichi, I'm cumming inside your girlfriend!!! I'm making[r]
your girlfriend pregnant!!"[pcms]
*10318|
[fc]
[vo_ri s="riri0574"]
[y—œ—¢z]
"If you say that, I'm going to cummmmm!! Getting fertilized by someone[r]
else's sperm other than Kenji's!! Cummingggg!!"[pcms]
[ƒƒXƒtƒ‰]
*10318a|
[fc]
While uttering words of apology to her lover, Risato reached climax.[r]
There was no trace of guilt, only pure pleasure.[pcms]
*10319|
[fc]
[vo_ri s="riri0575"]
[y—œ—¢z]
"Kenji... I'm getting pregnant with your friend's sperm... kuhii, I'm[r]
sorry, sorry Kenji... hahh, I'm cumming againnnnô"[pcms]
*10319a|
[fc]
While being tossed about by unbearable pleasure, Risato let out hot[r]
breaths in her unending excitement.[pcms]
[backlay][evcg storage="EV28_24" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10320|
[fc]
[vo_ri s="riri0576"]
[y—œ—¢z]
"Hii... Thank you for being Kenji's substitute... But it's still not[r]
enough... please violate me more..."[pcms]
*10324|
[fc]
[nsy]—¤ã•”‚ÌŒã”y[znse]
"Senpai's ass is so beautiful! It's shiny and slippery with semen,[r]
and... it's so firm...!!"[pcms]
;;
*10326|
[fc]
[vo_ri s="riri0577"]
[y—œ—¢z]
"Nfufu... Thank you for the compliment. Hey, you can take off my[r]
panties if you want?"[pcms]
*10327|
[fc]
[nsy]—¤ã•”‚ÌŒã”y[znse]
u‚ÜAƒ}ƒW‚Á‚·‚©I@‚»‚ÁA‚»‚ê‚¶‚á‰“—¶–³‚­cc‚Á‚Áv[pcms][endhact]
[backlay][evcg storage="EV28_25" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10328|
[fc]
As her panties soaked with semen and love juices were dragged down, a[r]
wave of heat immediately spilled out.[pcms]
*10329|
[fc]
[nsy]—¤ã•”‚ÌŒã”y[znse]
"Amazing... so amazing! If you show me such an erotic ass, I can't[r]
hold back anymore! Senpai, please take my virginity too!!"[pcms]
[backlay][evcg storage="EV28_26" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10330|
[fc]
[vo_ri s="riri0578"]
[y—œ—¢z]
"It's okay. Look... mmmh, put your junior cock in me? You know where[r]
it is, right? Hurry up and put it in..."[pcms]
*10331|
[fc]
The moment her tight ass shook, his self-control vanished. Gripping[r]
his hot throbbing cock, he slammed it into her dripping wet hole.[pcms]
[se buf=0 storage="se_sex01"]
[evcg”’ƒtƒ‰ storage="EV28_27" layer=0 page=back visible=true left=0 top=0]
[se buf=1 storage="se_sex03" loop=true]
*10332|
[fc]
[vo_ri s="riri0579"]
[y—œ—¢z]
"Kyaaaahnnnô If you're that hasty, it's no good. Ahh, your cock is[r]
trembling inside my pussy; it's still not time yet..."[pcms]
*10333|
[fc]
But Risato's tightness seemed too much for the virgin. The junior bit[r]
his lip as if he was about to cry but quickly reached his limit with[r]
ease.[pcms]
[se buf=0 storage="se_sex01"]
[Ë¸ƒtƒ‰A]
[backlay][evcg storage="EV28_28" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[Ë¸ƒtƒ‰B]
*10334|
[fc]
[nsy]—¤ã•”‚ÌŒã”y[znse]
u‚­‚ ‚ ‚ [[[‚Á‚ÁII@‚ÅAo‚Ä‚écc‚¤‚¨‚¨cc‚Á‚Áv[pcms][endhact]
*10335|
[fc]
Even as his body convulsed violently, he continued to thrust his hips.[pcms]
*10336|
[fc]
[nsy]—¤ã•”‚ÌŒã”y[znse]
"Please let me do more! It's frustrating like this! I owe you Senpai![r]
Do you remember?!"[pcms]
[backlay][evcg storage="EV28_29" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10337|
[fc]
[vo_ri s="riri0580"]
[y—œ—¢z]
"Woww, moving while cumming! This feels good! It feels so good so keep[r]
going!!"[pcms]
*10338|
[fc]
[nsy]—¤ã•”‚ÌŒã”y[znse]
"I'll do it! I'm grateful to Senpai so I'll do it many times!! Senpai[r]
is my angel, my idol of justice!!"[pcms]
*10339|
[fc]
Their conversation didn't match up but their bodies were deeply[r]
intertwined. Not their hearts but their bodies mingled together as[r]
pleasure enveloped them.[pcms]
[backlay][evcg storage="EV28_30" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10340|
[fc]
[vo_ri s="riri0581"]
[y—œ—¢z]
"Saying things like that makes me embarrassed...! But is it okay? To[r]
have such an erotic idol?"[pcms]
*10341|
[fc]
[nsy]—¤ã•”‚ÌŒã”y[znse]
"It's the best!! An erotic idol is amazing! To be thrilled by such an[r]
idol, to admire her!!"[pcms]
*10342|
[fc]
[vo_ri s="riri0582"]
[y—œ—¢z]
"I'm so happy! Look, thrust more here... here!! If you do that, I'll[r]
feel even better!!"[pcms]
*10343|
[fc]
While guiding his cock to the most pleasurable spot inside her, her[r]
vagina's depths, Risato's face crumbled into a smile of ecstasy.[pcms]
*10344|
[fc]
[nsy]—¤ã•”‚ÌŒã”y[znse]
"Is it here, is it here?! Kuu, the tip of the cock is hitting... it[r]
feels good!!"[pcms]
*10345|
[fc]
Thrusting vigorously into the depths of her vagina, right at the[r]
entrance to her womb, he dug his nails into the twitching flesh of her[r]
buttocks.[pcms]
[backlay][evcg storage="EV28_31" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
*10346|
[fc]
[vo_ri s="riri0583"]
[y—œ—¢z]
"Haah, hiiiiii!! Yes, right there! It feels good!! It feels too good,[r]
I'm going to come again on a cock that's not Kengo's!!"[pcms]
*10347|
[fc]
Risato felt her excitement increase every time she mentioned Kengo's[r]
name. And with each apology to him, that excitement became more pure.[pcms]
*10348|
[fc]
[vo_ri s="riri0584"]
[y—œ—¢z]
"I'm sorry, I'm so sorry, Kengo!! But I can't help it!! My body's hot,[r]
my pussy's throbbing, and without a cock I'd go crazy!!"[pcms]
*10349|
[fc]
[nsy]—¤ã•”‚ÌŒã”y[znse]
"Then, we'll give you our cocks!! Until Senpai is satisfied, as much[r]
as you want... guuuu!!"[pcms]
*10350|
[fc]
Whether he got used to the thrusting or not, the junior's movements[r]
became more precise. He accurately hit Risato's spot and thrust up[r]
into her descended womb.[pcms]
*10351|
[fc]
[vo_ri s="riri0585"]
[y—œ—¢z]
"Fuhiiiiin!! I'm... I'm coming! My womb is being hit, I'm coming![r]
Coming... coming coming coming, I'm cuuummming!!"[pcms]
*10352|
[fc]
Her body shook violently, and Risato easily reached climax. After[r]
that, each thrust brought on repeated climaxes.[pcms]
*10353|
[fc]
[nsy]—¤ã•”‚ÌŒã”y[znse]
u‚¤cc‚®‚ÁI@‰´‚àAƒCƒNcc‚ÁI@‚ñ‚®‚ ‚ ‚ ‚ ccIIv[pcms][endhact]
*10354|
[fc]
With each climax, he continued to resist the tightening assault, but[r]
the idol's screaming pleas shattered any futile effort.[pcms]
[stopse buf=1]
[se buf=0 storage="se_sex01"]
[Ë¸ƒtƒ‰A]
[backlay][evcg storage="EV28_32" layer=0 page=back visible=true left=0 top=0][trans time=300 method=crossfade][wt2]
[Ë¸ƒtƒ‰B]
*10355|
[fc]
[vo_ri s="riri0586"]
[y—œ—¢z]
"Nnhooohhh!! I'm cuuummming!! Over and over... over and over again,[r]
I'm cuuummming!! Oh heeehh!!"[pcms]
*10355a|
[fc]
Sticking out her tongue, Risato screamed out her climax as if she was[r]
being pushed up by the semen hitting her cervix.[pcms]
*10356|
[fc]
[nsy]—¤ã•”‚ÌŒã”y[znse]
u‚Í‚Ğcc‚¡‚¡A‚¹ccæ”ycc‚â‚Á‚Ï‚èAÅ‚‚ÌƒGƒƒAƒCƒhƒ‹‚Á‚·ccv[pcms][endhact]
[backlay][evcg storage="EV28_33" layer=0 page=back visible=true left=0 top=0][trans time=500 method=crossfade][wt2]
*10357|
[fc]
While listening to the melted junior's words of praise, Risato felt a[r]
new desire welling up inside her.[pcms]
*10358|
[fc]
It still wasn't enough. She wanted more and more cocks. Besides, there[r]
were still many people who wanted to have sex with her.[pcms]
*10359|
[fc]
As semen dripped from her hole where the cock had slipped out, Risato[r]
dove into the circle of men waiting for her.[pcms]
[if exp="tf.scene_mode == 1 && tf.all_play == 0"]
	[jump storage="b_scene.ks" target=*back_from_SR]
[endif]
[jump storage="0750_3.ks"]
